### ISSUE TITLE
script.backup.php fails to create backups

### ISSUE THREAD

**Issue by gwstj** [nilsteampassnet/TeamPass#2130] opened 2018-02-21 14:23 UTC
### Steps to reproduce
1. `su -l tp_user`
2. `cd $tp_backup_dir; php'$_GET["key"]="secret"; require_once("/mnt/crypt/teampass/backups/script.backup.php");' `
3. `ls -l`

### Expected behaviour
I would expect that the script creates an encrypted .sql file. Instead it prints the following warnings:

````
PHP Warning:  unlink(/mnt/crypt/teampass/backups/bck_cpassman-1519221196.sql): No such file or directory in /mnt/crypt/teampass/backups/script.backup.php on line 113
PHP Warning:  rename(/mnt/crypt/teampass/backups/bck_cpassman-1519221196.encrypted.sql,/mnt/crypt/teampass/backups/bck_cpassman-1519221196.sql): No such file or directory in /mnt/crypt/teampass/backups/script.backup.php on line 117
````

### Actual behaviour
It doesn't create a file.

### Server configuration
**Operating system**:
````
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
````
**Web server:**
````
# apache2ctl -V
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Sep 18 2017 16:37:54
Server's Module Magic Number: 20120211:27
Server loaded:  APR 1.5.1-dev, APR-UTIL 1.5.3
Compiled using: APR 1.5.1-dev, APR-UTIL 1.5.3
Architecture:   64-bit
Server MPM:     event
  threaded:     yes (fixed thread count)
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"
````

**Database:**
````
# mysql --version
mysql  Ver 14.14 Distrib 5.5.59, for debian-linux-gnu (x86_64) using readline 6.3
````

**PHP version:**
````
# php --version
PHP 5.5.9-1ubuntu4.23 (cli) (built: Feb  8 2018 21:59:47) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
````

**Teampass version:** 
````
# grep teampass_version includes/config/tp.config.php
    'teampass_version' => '2.1.27',
````

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** updated from 2.1.26

### Client configuration
Not involved.

[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1744291/tp.config.php.txt)

**Comment by nilsteampassnet** [comment] 2018-02-21 20:37
Thank you.

Duplicate of #2115

**Closed by nilsteampassnet** 2018-02-21 20:37 UTC
