### ISSUE TITLE
Access Denied for personal folder

### ISSUE THREAD

**Issue by newburns** [nilsteampassnet/TeamPass#1960] opened 2017-10-10 13:00 UTC
### Steps to reproduce
1. Upgraded from 2.1.27 to 2.1.27.9
2. Prompted to change encryption method. Must put in SALT KEY. Only two options, Start or Cancel
3. Clicked start before inputting SALT Key.
4. Personal items all say password denied. However, copy password icon next to item works just fine after correct SALT key.

### Expected behaviour
Tell us what should happen

1. Only close option is allowed until SALT Key is input for the encryption change warning.
B. Personal folders cannot be altered by any administrator user. No way to edit.

### Actual behaviour
Clicked Start on encryption warning window.
Input my SALT Key.
Access to all personal passwords and folders are denied.
Passwords are still there, confirmed by the copy password icons next to each item.

### Server configuration
**Operating system**:
CentOS 7
**Web server:**
Virtualmin
**Database:**
MySQL
**PHP version:**
PHP 7.0.1
**Teampass version:** 
2.1.27.9
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 7
### Logs
This error log is unrelated, but it is the only thing I have in there. This error log presents itself from the main admin window. Not related to the above issue.
#### Web server error log
```
[Tue Oct 10 08:56:33.359407 2017] [fcgid:warn] [pid 1339] [client 166.141.55.198:61141] mod_fcgid: stderr: PHP Notice:  Undefined index: item_extra_fields in /home/********************/public_html/sources/main.functions.php on line 1154, referer: https://security.********.com/index.php?page=manage_main
```

**Comment by newburns** [comment] 2017-10-10 17:13
So it doesn't seem to have anything to do with the time the SALT key was created. Had another user perform the proper SALT Key encryption order, and it has blocked that user from personal folders.

**Comment by newburns** [comment] 2017-10-10 17:22
This is the restricted message. It has no user as the owner
![image](https://user-images.githubusercontent.com/5234107/31400558-a0227ac6-adb5-11e7-887e-866b749af466.png)

**Comment by newburns** [comment] 2017-10-10 17:30
Same error happens on a brand new user.

**Comment by jcoquery** [comment] 2017-10-12 14:11
Hi,
Look at the issue #1955 and try to do the modifications listed in my last comment.

**Comment by newburns** [comment] 2017-10-12 14:30
@jcoquery 
Doesn't seem to work. Gives a 500 error.
Not entirely sure what your comment is proposing...
I commented out the last 3 lines of that code, but it did not give good results. Below is the comment I made
```
            // check user is admin
            if ($_SESSION['user_admin'] === '1' && $dataItem['perso'] != 1 && (isset($SETTINGS_EXT['admin_full_right']) && $SETTINGS_EXT['admin_full_right'] === true) || !isset($SETTINGS_EXT['admin_full_right'])) {
                $arrData['show_details'] = 0;
            // Check if actual USER can see this ITEM
            } elseif ((
                (in_array($dataItem['id_tree'], $_SESSION['groupes_visibles']) || $_SESSION['is_admin'] === '1') && ($dataItem['perso'] === '0' || ($dataItem['perso'] === '1' && $dataItem['id_tree'] === $_SESSION['user_id'])) && $restric
tionActive === false)
                ||
                (isset($SETTINGS['anyone_can_modify']) && $SETTINGS['anyone_can_modify'] === '1' && $dataItem['anyone_can_modify'] === '1' && (in_array($dataItem['id_tree'], $_SESSION['groupes_visibles']) || $_SESSION['is_admin'] === '1'
) && $restrictionActive === false)
                ||
                (null !== $post_folder_id
                    && isset($_SESSION['list_restricted_folders_for_items'][$post_folder_id])
                //    && in_array($post_id, $_SESSION['list_restricted_folders_for_items'][$post_folder_id])
                //    && $post_restricted === '1'
                //    && $user_in_restricted_list_of_item === true)
                ||
                (isset($SETTINGS['restricted_to_roles']) && $SETTINGS['restricted_to_roles'] === '1'
                    && $restrictionActive === false
                )

```

**Comment by jcoquery** [comment] 2017-10-12 14:54
carefull tto the ")" at the end of `//    && $user_in_restricted_list_of_item === true)`
Try something like `// check user is admin
            if ($_SESSION['user_admin'] === '1' && $dataItem['perso'] != 1 && (isset($SETTINGS_EXT['admin_full_right']) && $SETTINGS_EXT['admin_full_right'] === true) || !isset($SETTINGS_EXT['admin_full_right'])) {
                $arrData['show_details'] = 0;
            // Check if actual USER can see this ITEM
            } elseif ((
                (in_array($dataItem['id_tree'], $_SESSION['groupes_visibles']) || $_SESSION['is_admin'] === '1') && ($dataItem['perso'] === '0' || ($dataItem['perso'] === '1' && $dataItem['id_tree'] === $_SESSION['user_id'])) && $restrictionActive === false)
                ||
                (isset($SETTINGS['anyone_can_modify']) && $SETTINGS['anyone_can_modify'] === '1' && $dataItem['anyone_can_modify'] === '1' && (in_array($dataItem['id_tree'], $_SESSION['groupes_visibles']) || $_SESSION['is_admin'] === '1') && $restrictionActive === false)
                ||
                (null !== $post_folder_id
                    && isset($_SESSION['list_restricted_folders_for_items'][$post_folder_id])
                //    && in_array($post_id, $_SESSION['list_restricted_folders_for_items'][$post_folder_id])
                //    && $post_restricted === '1'
                //    && $user_in_restricted_list_of_item === true
                )
                ||
                (isset($SETTINGS['restricted_to_roles']) && $SETTINGS['restricted_to_roles'] === '1'
                    && $restrictionActive === false
                )`

**Comment by newburns** [comment] 2017-10-12 15:03
Made the change.
Still gives the same error
```
 Access to password item denied!
Author: rburns
Restricted to: 

Request access to modify
```
However, I can see the password through the copy and paste icon... Not sure why.
![image](https://user-images.githubusercontent.com/5234107/31503169-95ff51d8-af34-11e7-8d1f-8241fc0ca86d.png)

**Comment by nilsteampassnet** [comment] 2017-10-12 19:29
Can we arrange a screen sharing session?

**Comment by newburns** [comment] 2017-10-12 19:34
Yes. What time for the screen share? Would it be best if I gave you credentials for login? It's a virtualmin host.
How do you want to share the credentials?

**Comment by nilsteampassnet** [comment] 2017-10-12 19:55
It can be by email : nils@teampass.net

**Comment by roru69** [comment] 2017-10-13 11:47
Sort of the same problem here with LDAP Windows AD enabeled.

### Steps to reproduce
1. Clean install of the latest Master commit f7828f2
2. under settings enabled LDAP for windows AD.
3. Set the timezone to Europe/Amsterdam
4. Settings: enabled Personal Folders
5. Settings: enabled Personal Salt key in browser Cookie
6. Settings: disabled mainenance mode.
7. Logged in as normal AD user - Account gets created and screen refreshes
8. Logged in again. - Now in main screen.
9. Set personal salt key
10. Add a personal password item and save it. (Ok)
11. View the personal password item - This fails.

### Expected behaviour
The personal item should have opened.

### Actual behaviour
Access to password item denied!
Author: edwin
Restricted to:

Request access to modify

### Server configuration
**Operating system** Debian 8
**Web server:** Apache
**Database:** Maria DB
**PHP version:** PHP 7

**Teampass version:** Master commit f7828f2
**Teampass configuration file:**

    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/mydomain.com/public_html/teampass',
    'cpassman_url' => 'https://www.mydomain.com/teampass',
    'favicon' => 'https://www.mydomain.com/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/mydomain.com/public_html/teampass/upload',
    'url_to_upload_folder' => 'https://www.mydomain.com/teampass/upload',
    'path_to_files_folder' => '/var/www/mydomain.com/public_html/teampass/files',
    'url_to_files_folder' => 'https://www.mydomain.com/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => 'windows',
    'ldap_suffix' => '@my.domain',
    'ldap_domain_dn' => 'OU=Users,OU=Prive,DC=my,DC=domain',
    'ldap_domain_controler' => 'myserver.my.domain',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'dutch',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1505283311',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '1',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'mail.my.domain',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => 'noreply-teampass@mydomain.com',
    'email_from_name' => 'Teampass-Admin',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/mydomain.com/public_html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Amsterdam',

### Client configuration
**Browser:** Firefox
**Operating system:** Windows 10

**Comment by newburns** [comment] 2017-10-13 12:11
@roru69 
Are your passwords accessible through the copy password icon? Similar to my issue...
Or are your passwords completely inaccessible?

**Comment by newburns** [comment] 2017-10-13 12:44
@nilsteampassnet 
I've emailed you.

**Comment by dinesh8642** [comment] 2017-10-16 05:13
hi guys @nilsteampassnet  .. any update on this issue..I am having the same issue on a new user who is just managed by Administrator. I am able to create personal folder but when I try to access it say :  Access to password item denied! 

Dinesh

**Comment by roru69** [comment] 2017-10-16 09:30
@newburns 

My personal passwords are completely inaccessible. See screenshot. (It is in Dutch, but you'll get the picture). I Use Active Directory as an LDAP provider.

![noaccess](https://user-images.githubusercontent.com/9691381/31604948-22185d12-b265-11e7-8499-173263315da1.PNG)

Regards,

Roru69

**Comment by roru69** [comment] 2017-10-16 10:38
I did a clean testinstall without LDAP (AD), and i get the same warning.
Log says:

[Mon Oct 16 12:31:04.161745 2017] [:error] [pid 3050] [client 192.168.28.5:54967] PHP Notice:  Use of undefined constant SALT - assumed 'SALT' in /var/www/mydomain.com/public_html/teampass/sources/main.functions.php on line 226, referer: https://www.mydomain.com/teampass/index.php

The same entry in the log is made when using LDAP b.t.w.

Regards,

Roru69

**Comment by newburns** [comment] 2017-10-16 15:18
@roru69 
Are you able to access your password through the copy icon?

**Comment by roru69** [comment] 2017-10-16 17:45
@newburns 
No.
I tried with an install with LDAP and without. The same behaviour. No access at all. I don't have a copy icon.. See below screenshot.

![afbeelding](https://user-images.githubusercontent.com/9691381/31626565-8588b2da-b2aa-11e7-9fee-71a35e9f9e51.png)

**Comment by nilsteampassnet** [comment] 2017-10-19 19:13
@roru69 Do you think I could have access to your teampass instance?

**Comment by roru69** [comment] 2017-10-20 08:41
@nilsteampassnet 

No problem, I will email the credentials to: nils@teampass.net

**Comment by nilsteampassnet** [comment] 2017-10-21 05:56
I could reproduce also locally now.

Investigation in progress.

**Comment by roru69** [comment] 2017-10-21 06:12
Ok. Well nice to hear in a way. Hopefully this gets sorted out soon... If you need access to the server just let me know..

**Comment by roru69** [comment] 2017-10-21 07:45
Power outage where i live. Just booted the server again.. (never happened before).. So my teampass instance is available again..

**Comment by roru69** [comment] 2017-10-23 09:23
@nilsteampassnet 

Tested with the latest developement version "commit 0f6a743" Still the error:

![afbeelding](https://user-images.githubusercontent.com/9691381/31881636-70e78f2e-b7e4-11e7-935e-c92a0646d7f0.png)

You can use the same credentials i earlier sent by email.

Regards, Roru69

**Comment by nilsteampassnet** [comment] 2017-10-24 04:09
@roru69 
oops I didn't commit the fix for this issue.
I will now.

**Comment by roru69** [comment] 2017-10-24 10:19
Just tested a clean installation (commit a7990cf). I can confirm that the fix works for me! Thanks!!

**Comment by nilsteampassnet** [comment] 2017-10-24 19:50
Great

**Closed by nilsteampassnet** 2017-10-24 19:50 UTC
Labels: Under investigation
