### ISSUE TITLE
html entities get interpreted inside passwords

### ISSUE THREAD

**Issue by Tmkrth** [nilsteampassnet/TeamPass#2244] opened 2018-05-03 14:12 UTC
Hello. Teampass seems to interpret html entities inside passwords. Noticed with 2.1.27.12

### Steps to reproduce
1. create a new object, give it a name and fill in a password
2. use some html entities inside this password
3. after creating the object looking at it with the eye button or copying it will have interpreted characters

Example: created a password `"hello&uuml;&gt;"`, got "helloü>" back

**Comment by Tmkrth** [comment] 2018-05-03 14:13
I have not tested sql syntax, sorry.

**Comment by nilsteampassnet** [comment] 2018-05-08 16:02
Absolutely!

Duplicate of #2244.

Quick fix: in file `items.load.php`, replace
`$("#hid_pw").html(unsanitizeString(data.pw));`
by
`$("#hid_pw").text(unsanitizeString(data.pw));`

**Closed by nilsteampassnet** 2018-05-08 16:02 UTC
