### ISSUE TITLE
2.1.26.18 LDAP Problems

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#1486] opened 2016-09-12 07:05 UTC
### Steps to reproduce
1. Install New version of teampass
2. Configure LDAP settings using Windows AD
3. ADD AD user
4. Try to login using AD User

### Expected behaviour
"Please identify yourself" loading bar spinning and nothing happens. 

### Server configuration
**Operating system**:
Ubuntu 14.04.4 LTS
**Web server:**
Apache/2.4.7 (Ubuntu)
**Database:**
Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3
**PHP version:**
PHP 5.5.9-1ubuntu4.16 (cli) (built: Apr 20 2016 14:31:27)
**Teampass version:** 
2.1.26.18
**Updated from an older Teampass or fresh install:**
Fresh or Update from 2.1.26.16
### Client configuration
**Browser:**
FF or IE
**Operating system:**
Windows 10 x64 Ent
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
http://........................../sources/identify.php?data=jlDWV%2BXl5eUcALP8pswGW5Zu%2ByDdL67npcBnrC8%2FMaX%2BIgwtcH%2Ba97RY3k99qkjOollZGYb9WT5UT18y%2B9YfPU5IM3hvD5wA%2F1m%2FfqD9MiUPrmbxjaeTcZwvc49rdn8q6YsP0ZPUhlK%2FWYqRHxL0MW42QfVr0RS3y%2Bq4%2BT%2FP%2Bvh63U71ZpFOgFDnMBzMkfvupdjkZ4I%3D&f7460c64a2912ec628a563de45e0be01624269f405a290983a=b3aefc479a113d1fabf643a68bb32590638dbd7a99997ce2a7&type=identify_user

```
![untitled](https://cloud.githubusercontent.com/assets/4628571/18427347/1e218faa-78d0-11e6-9f8a-85f4ce7ed20d.jpg)

**Comment by reginfo** [comment] 2016-09-12 07:41
Hi, is there any changes to LDAP configurations from earlier versions?

### Steps to reproduce
1. Install New version of teampass
2. Configure LDAP settings using Windows AD
3. ADD new user from AD (deniss as login)
4. Try to login using AD User (deniss as login)

Then I receive "Login credentials do not correspond"

If I use domain\deniss - all OK. 

But in version 2.1.26.16 I use deniss only as login name. And all working fine

**Comment by tehnotronic** [comment] 2016-09-12 07:46
Confirmed, after updating to release 18-19, I cannot log in with LDAP users. I see changes in adLDAP library...


 includes/libraries/LDAP/adLDAP/adLDAP.php                               | 3317 +++++++++++++++++++++++++++++++++---------------------------------------------------------------------------------------------------------------------------
 includes/libraries/LDAP/adLDAP/classes/adLDAPComputers.php              |  147 +++++++
 includes/libraries/LDAP/adLDAP/classes/adLDAPContacts.php               |  283 ++++++++++++++
 includes/libraries/LDAP/adLDAP/classes/adLDAPExchange.php               |  376 ++++++++++++++++++
 includes/libraries/LDAP/adLDAP/classes/adLDAPFolders.php                |  175 +++++++++
 includes/libraries/LDAP/adLDAP/classes/adLDAPGroups.php                 |  690 +++++++++++++++++++++++++++++++++
 includes/libraries/LDAP/adLDAP/classes/adLDAPUsers.php                  |  658 +++++++++++++++++++++++++++++++
 includes/libraries/LDAP/adLDAP/classes/adLDAPUtils.php                  |  287 ++++++++++++++
 includes/libraries/LDAP/adLDAP/collections/adLDAPCollection.php         |  134 +++++++
 includes/libraries/LDAP/adLDAP/collections/adLDAPComputerCollection.php |   45 +++
 includes/libraries/LDAP/adLDAP/collections/adLDAPContactCollection.php  |   45 +++
 includes/libraries/LDAP/adLDAP/collections/adLDAPGroupCollection.php    |   45 +++
 includes/libraries/LDAP/adLDAP/collections/adLDAPUserCollection.php     |   45 +++

**Comment by tehnotronic** [comment] 2016-09-12 08:04
[12-Sep-2016 08:02:03 UTC] PHP Fatal error:  Class 'LDAP\adLDAP\adLDAP' not found in /srv/www/htdocs/sources/identify.php on line 297

**Comment by reginfo** [comment] 2016-09-12 11:01
Also I realise that is I will try to logon using my email address and my AD password TEAMPASS will create new user as email address. 
Is it correct?

**Comment by nilsteampassnet** [comment] 2016-09-12 12:01
LDAP is difficult for me as I cannot debug. 
But here I think that the fix us easy. 

Open file sources/identify.php.

Line 297, change to '$adldap = new adLDAP(' 

Can you please confirm

**Comment by TheKingKai** [comment] 2016-09-12 12:36
Same problem after I change it to '$adldap = new adLDAP(' .. :(

**Comment by tehnotronic** [comment] 2016-09-12 12:58
@nilsteampassnet you can use public ldap servers, like one of these: http://www.forumsys.com/en/tutorials/integration-how-to/ldap/online-ldap-test-server/ 

This didn't fix it for me also, login requests still get error 500, but in the log I can see different error messages. I don't know if they even have anything to do with this or not. Previous error about adLDAP is no more showing up.

[12-Sep-2016 13:05:47 Europe/Tallinn] PHP Notice:  Undefined variable: link in /srv/www/htdocs/includes/libraries/Database/Meekrodb/db.class.php on line 618
[12-Sep-2016 13:05:47 Europe/Tallinn] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /srv/www/htdocs/includes/libraries/Database/Meekrodb/db.class.php on line 618
[12-Sep-2016 12:24:51 UTC] PHP Warning:  require_once(/includes/language/estonian.php): failed to open stream: No such file or directory in /srv/www/htdocs/index.php on line 110
[12-Sep-2016 12:24:51 UTC] PHP Fatal error:  require_once(): Failed opening required '/includes/language/estonian.php' (include_path='.:/usr/share/php:/usr/share/pear') in /srv/www/htdocs/index.php on line 110
(language file is there and has correct read permissions and UI is displayed in Estonian)

**Comment by reginfo** [comment] 2016-09-12 14:38
If we are takling about this:
![capture2](https://cloud.githubusercontent.com/assets/4628571/18439896/ad673702-790f-11e6-8ed2-b0feca07f36f.PNG)
then we receive the same error  500

**Comment by fudcompliance** [comment] 2016-09-12 14:45
Hello,
I managed to fix the issue by keeping the old includes/libraries/LDAP from teampass 2.1.25 .

**Comment by reginfo** [comment] 2016-09-12 15:00
> fudcompliance,

I`ve copied adLDAP folder from 2.1.25(2) version. 500 Error is gone, but I still unable logon as user without entering domain in front. 
It sais : Login credentials do not correspond!

**Comment by fudcompliance** [comment] 2016-09-12 15:04
Try to check also if in sources/identify.php at line 297 you have:
            $adldap = new LDAP\adLDAP\adLDAP(
or something else.

**Comment by reginfo** [comment] 2016-09-12 15:10
Yep, I have it:
$adldap = new LDAP\adLDAP\adLDAP(
                array(
                    'base_dn' => $_SESSION['settings']['ldap_domain_dn'],
                    'account_suffix' => $ldap_suffix,
                    'domain_controllers' => explode(",", $_SESSION['settings']['ldap_domain_controler']),
                    'use_ssl' => $_SESSION['settings']['ldap_ssl'],
                    'use_tls' => $_SESSION['settings']['ldap_tls']
                )

**Comment by reginfo** [comment] 2016-09-12 16:07
With 2.1.26.19 I was able to login as user without entering domain if:

1. keeping the old includes/libraries/LDAP from teampass 2.1.25(2)
2. keeping the old identify.php from 2.1.26.19 production environment

But I think it is not a method. 

With clean install of 2.1.26.19 I was unable to login also using domain\username. 500 error.

**Comment by mweber88** [comment] 2016-09-12 16:27
Nils et al--

There are two problems going on here.

#1:  please see final comment on issue #1433. When left as default Windows/Active Directory in the configuration settings, the value of "windows" is not set in the settings and the logic in identify.php doesn't work.  The settings have the value of "0" instead of "windows" and changing to another Posix value and back sets the proper value.  We need a default value, not "0", or change these settings values to be numeric aliases ("0", "1", "2", etc) and have it default to "0" as it already does.

#2:  Please see final comments on issue #1440.  I recommend putting in a different adLDAP library, leaving the library intact, and making a couple small changes to identify.php.

I would do this for you but I'm not aware how to make changes which you could merge in.  You can tell me how to do it and I'll do it, or make the changes I've listed.  Doing so will eliminate issues #1433, #1440, #1486.

:)

Mike

**Comment by nilsteampassnet** [comment] 2016-09-12 16:49
@mweber88, please attach the files here.

Nevertheless, what is strange here, is that I've updated the the library to 4.0.5 and done the change we discussed in #1440. But clearly the issue is related the namespace ...

**Comment by mweber88** [comment] 2016-09-12 18:05
Nils--

Thank you for putting those changes into .19.  I apologize though as I forgot to give you one additional piece of information in #1440:

In identify.php, line 297, change

 $adldap = new LDAP\adLDAP\adLDAP(

to

 $adldap = new adLDAP\adLDAP(

That should eliminate those namespace errors.

reginfo and fudcompliance:

I'm assuming you both are using Active Directory LDAP.  If so, can you check your _misc table in your mysql databases and check what the value of ldap_type is, then report those back here?

Also, would you mind checking if the users listed in your _users table in mysql have just the local part (i.e. mweber) rather than the entire email username (i.e. mweber@domain.tld), then report back what you see in these tables?

We'll get to the bottom of this and move forward.

**Comment by reginfo** [comment] 2016-09-12 18:24
Yep, I`m using AD LDAP.

 _misc table:
ldap_type ->windows
_users table:
| 10000000 | deniss |

I performed it using all modifications (upper) I made to get it work.
Or you prefer that I did clean install and try?

**Comment by mweber88** [comment] 2016-09-12 19:15
reginfo--

Thank you for the feedback.  Your tables are as I would expect them to be for correct function.

Are you saying that with the change I suggested to line 297 in identify.php that it is now working?

Mike

**Comment by reginfo** [comment] 2016-09-12 19:20
I was talking about:
> keeping the old includes/libraries/LDAP from teampass 2.1.25(2) (thanks fudcompliance)
>     keeping the old identify.php from 2.1.26.16 production environment

So, clean install and LDAP configuration gives me this:
![capture5](https://cloud.githubusercontent.com/assets/4628571/18449154/cf6455fc-7936-11e6-994a-79fbc1033834.PNG)
But when I add AD user I see this:
![capture6](https://cloud.githubusercontent.com/assets/4628571/18449227/0d8ebcd2-7937-11e6-82ab-9340c3029675.PNG)

**Comment by reginfo** [comment] 2016-09-12 19:23
If i change
> $adldap = new LDAP\adLDAP\adLDAP(
to
$adldap = new adLDAP\adLDAP(

I will be able to login but using "domain\login" patern. 
But what about only with "login"?

**Comment by mweber88** [comment] 2016-09-12 19:25
reginfo--

Ahh.  I see.

If you wouldn't mind doing two things to your clean install:

1.  Change line 297 in identify.php from:

$adldap = new LDAP\adLDAP\adLDAP(

to

$adldap = new adLDAP\adLDAP(

2.  In your LDAP settings, change your LDAP type from Windows/Active Directory to one of the Posix types, then back to Windows/Active directory.

#2 is needed to change your ldap_type from '0' to 'windows' (please confirm this change as well).

Once you do these, you should be able to log in with only 'login' rather than 'DOMAIN\login.'

Please test and report back.  Thank you so much for your help!

Mike

**Comment by reginfo** [comment] 2016-09-12 19:34
So my results are:
1. I`ve mage changes to $adldap
2. Change LDAP type from Windows/Active Directory to one of the Posix types, then back to Windows/Active directory
 
![capture7](https://cloud.githubusercontent.com/assets/4628571/18449722/0422d9a6-7939-11e6-9a44-ead1fa9e10df.PNG)

It changed ldap_type from 0 to windows. 
But I can logon only using DOMAIN\login pattern. 
Login credentials do not correspond message. =(

**Comment by mweber88** [comment] 2016-09-12 19:50
OK.  The ldap_type is now set correctly.

What are the values for your ldap_suffix and ldap_domain_dn in your _misc table?

Mike

**Comment by reginfo** [comment] 2016-09-12 19:57
ldap_suffix = @demo.lv
ldap_domain_dn = dc=demo,dc=lv

**Comment by mweber88** [comment] 2016-09-12 20:11
That's very strange.  After clearing my browser cache, if I try to login with the domain:

mweber@domain.tld

If fails with "Login credentials do not correspond"

If I use only

mweber

it succeeds.

Can you go into the identify.php file and enable LDAP debugging:

$debugLdap = 1; //Can be used in order to debug LDAP authentication

Your debug file will be in the <teampass>/files directory, named ldap.debug.txt.

Please sanitize (if needed) and paste the contents of that file here for review.

Mike

**Comment by reginfo** [comment] 2016-09-12 20:17
Hmmmm... I was using in-private mode. 
I cleaned cahce several times and nothing. 
But after your words I cleaned one more time and voila. IT WORKS. :)
A can logon with login or DOMAIN\Login.

**Comment by mweber88** [comment] 2016-09-12 20:35
Perfect.

Nils--

The outstanding issue that we somehow need to address is the LDAP-settings problem.

On clean install, ldap_type defaults to '0'.  When setting up LDAP, the default choice for 'LDAP Server Type' is 'Windows/Active Directory' in the drop-down selection, which has a value of 'windows' according to the code, but it does not change the value for the settings to 'windows' unless the user changes it to one of the other options first, then changes it back to 'Windows/Active Directory' option.

There are three possible ways it could be fixed:

Option 1.  It could be fixed by defaulting the ldap_type value in settings to 'windows' choice, but that would be a problem for people upgrading to a newer version of Teampass and later setting up LDAP.  It could be fixed by issuing a test and change in upgrade scripts to look for '0' in ldap_type and set it to 'windows' instead.

Option 2.  Change the selection values from being names (i.e. 'windows', 'posix', etc) to numbers ('0' (for ad), '1' (for posix), '2' (for posix-search)), which would fix the clean install issue.  However, it would still need an upgrade script to change any name values currently set in settings.

Option 3.  Change the selection values to include a non-setting value, such as '---Make your selection---', which would not have a value and would correspond to the default ldap_type value of '0' for clean install.  However, this would require input validation to make sure if LDAP is enabled, LDAP server type is set to a valid value and it would require a language translation input for the corresponding language used.  It would remove any issues with upgrading and changing from current database values to using LDAP in the future.

From what I have seen, it appears that you have chosen to avoid situations like Option 3, so maybe options 1 or 2 would be your desired path.

What are your thoughts?  I can explore doing a pull request and making the updates needed if you have a desired choice.

Mike

**Comment by nilsteampassnet** [comment] 2016-09-13 05:56
Thank you Mike for your analysis. 
Option 3 is the best one I think. Indeed adding an option in the select list is easy and the string exists in language files. 
It seems the most simple solution with the most effective one. 
I will commit this soon.

**Comment by reginfo** [comment] 2016-09-13 07:03
Thank Nil, but I still can`t logon with username only.
I`ve changed 2 files from the fix. 
So in admin LDAP settings I see new drop menu value  --select--. If I chance it to AD then in mysql all changes correct. 
I add AD user, clear browser cache but Login credentials do not correspond!. Only working with DOMAIN\login. 
But what I saw is that if I open LDAP settings page from admin i see LDAP server type as --select--. 

--Mike, can you test this fix?
Maybe I overworked.......

**Comment by tehnotronic** [comment] 2016-09-13 07:13
I have tested Nils fix today and I can now login with username only, no domain needed. So for me, it is working. Please do a git pull from development, discard local changes and clear browser cache and see if it is working for you too.

**Comment by reginfo** [comment] 2016-09-13 07:54
I think I found my problem. My AD user was BLOCKED. 
But anyway I reinstall from scratch development package and now it works! Thanks!

**Comment by nilsteampassnet** [comment] 2016-09-13 19:29
Thanks for your feedback

I'm closing this.

**Closed by nilsteampassnet** 2016-09-13 19:29 UTC
Labels: bug

**Comment by TheKingKai** [comment] 2016-09-19 08:26
Nils, do you release version 2.1.26 (20) with this corrected bug in the next few days?
