### ISSUE TITLE
Update 2.1.15 => 2.1.23

### ISSUE THREAD

**Issue by djatwork** [nilsteampassnet/TeamPass#875] opened 2015-02-03 09:39 UTC
Hi
We updated our install and now the users can´t use there private folder any more.
There is no place to enter the personal salt key!?
After klicking "home" after the "You should enter your personal saltkey if you need to use your personal items." We are logged out and forwarded to the login screen!
is there any trick to enter the key? 

I tried also the "use your password as saltkey"  after that the folder is accessable but the users can´t add item. ==> You are not allowed to do that....

Version 2.1.23
AD Auth
Timezone: Europe/Vienna

thx

**Comment by nilsteampassnet** [comment] 2015-02-03 11:52
In 2.1.23, the home page has been removed.

The "saltkey" can be entered from the top menu right icon (on the left of
the language flag).
This will give you access to a sub-menu. Select the Saltkey one.

2015-02-03 10:39 GMT+01:00 djatwork <notifications@github.com>:

**Comment by djatwork** [comment] 2015-02-03 12:14
![salt1](https://cloud.githubusercontent.com/assets/10827638/6019944/3e752288-aba6-11e4-8644-7dd857071853.JPG)
Is there a icon missing? There´s space.....

![salt2](https://cloud.githubusercontent.com/assets/10827638/6019947/40d23f7a-aba6-11e4-88c8-ce169dbadf93.JPG)
i don´t have the menu item.
Is it normal that i´m logged out after a language change?

thx

**Comment by ynnsn** [comment] 2015-02-04 14:21
I have the same behaviour. There is not other icon left of the language flag.

**Comment by nilsteampassnet** [comment] 2015-02-05 07:32
No there is no icon missing in the screenshots I can see.

2015-02-04 15:21 GMT+01:00 ynnsn <notifications@github.com>:

**Comment by djatwork** [comment] 2015-02-05 08:37
ok, but where i should enter the key?

**Comment by ynnsn** [comment] 2015-02-05 08:38
And where? 
![salt](https://cloud.githubusercontent.com/assets/5175896/6057122/acde9fd6-ad1a-11e4-806d-be4157bb5a33.png)
I tried to change the language, but I can't find the salt key sub menu.

**Comment by nilsteampassnet** [comment] 2015-02-05 11:49
​It seems that personal folder feature is not enabled.
Can you check this from the administration settings page?​

**Comment by ynnsn** [comment] 2015-02-05 15:16
The personal folder feature is enabled.

**Comment by djatwork** [comment] 2015-02-06 12:22
checked again, pf is enabled

**Comment by jensdepuydt** [comment] 2015-02-10 10:02
We're having the same issues. Personal folder is enabled.
With the option enabled to use the password, users can't create new items (You are not allowed to do that!). With the option disabled, there is no possibility to enther the salt-key.

When changing line 225 in index.php from:
(isset($_SESSION['settings']['ldap_mode']) && $_SESSION['settings']['ldap_mode'] == 1) || $_SESSION['user_admin'] == 1 ? '' :
                                isset($_SESSION['settings']['enable_pf_feature']) && $_SESSION['settings']['enable_pf_feature'] == 1 ? '

to

(isset($_SESSION['settings']['ldap_mode']) && $_SESSION['settings']['ldap_mode'] == 1) &&    isset($_SESSION['settings']['enable_pf_feature']) && $_SESSION['settings']['enable_pf_feature'] == 1 ? '

I do manage to get the menu but it's still not working since I get the message: You should enter your personal saltkey if you need to use your personal items. Even after setting the salt-key. And creating an item gives me: You are not allowed to do that!

When using the password as salt, what happens when a user changes it's password? Because since the upgrade, I've got some users that can't access their personal folder items anymore. All changed their password.

**Comment by Ni0b1ite** [comment] 2015-02-24 14:55
Had the same problem, 
I did also the changes above in index.php and now I have no problems setting the salt-key but got also the message "You are not allowed to do that!" when i tried to add a new personal item or edit an existing one.

Following changes have fixed that for me:

sources\main.functions.php
line 489 from: 

```
489:  if (!in_array($folderId, $listReadOnlyFolders) || (isset($pf) && $folderId != $pf['id'])) {

```
to 

```
489:   if (!in_array($folderId, $listReadOnlyFolders)) {
490:    	 if (isset($pf) && $folderId != $pf['id']){
..
502:   }
```
Additionally it is necessary to authorize to have several items with the same name in admin settings. Otherwise the save button will be disabled after you insert a label (regardless it is duplicated or not).

**Comment by Ni0b1ite** [comment] 2015-02-27 17:12
After all that changes is one problem left. 
Personal Items are listed in personal folder although they are deleted. (editing is not possible anymore). 
In sources\items.queries.php after line
```
1825:   $items_to_display_once = "max";
```
I added
```
1826: $where->add('i.inactif=%i', 0);
```

**Comment by if-kenn** [comment] 2015-03-03 19:27
I am having a problem after upgrading as well. While I can set the SaltKey, I still get the "You should enter your personal saltkey if you need to use your personal items." after doing so.

![screen shot 2015-03-03 at 11 25 29 am](https://cloud.githubusercontent.com/assets/5553161/6470380/3b8e3eb2-c198-11e4-9650-5cc29fed23ba.png)

![screen shot 2015-03-03 at 11 25 50 am](https://cloud.githubusercontent.com/assets/5553161/6470381/3f018626-c198-11e4-8f4e-2a85845aba10.png)

**Comment by Ni0b1ite** [comment] 2015-03-09 15:41
I had the same issue with 2.1.22 only for one user, but suddenly it was gone with 2.1.23.

Try to turn off the function "store salt in cookie" (or something like that)  in admin panel. 
I am not sure but it could be that this solved my problem, especially if you say that it is still present in 2.1.23.

**Comment by toptnc** [comment] 2015-03-20 14:10
If I understand, looking at index.php, line 225

`(isset($_SESSION['settings']['ldap_mode']) && $_SESSION['settings']['ldap_mode'] == 1) || $_SESSION['user_admin'] == 1 ? '' :
                                isset($_SESSION['settings']['enable_pf_feature']) && $_SESSION['settings']['enable_pf_feature'] == 1 ? '`

If ldap_mode is enabled, PF is disabled. Am I wright?

**Comment by fgn-git-hub** [comment] 2015-03-26 16:50
I tried the index change as well but it did not show the saltkey menu option after that. 
I use LDAP enabled as well as PF enabled. 
no changes at all.

**Comment by fgn-git-hub** [comment] 2015-04-02 10:45
Am I missing something?
I checked everything once again and I even copied the files from 
 2.1.23
Fix for #881 - #900 - #890 - #910
Which did not solve anything. Is there an already checked in file which solves this issue?

**Comment by dopegaar** [comment] 2015-04-13 07:33
Hi, fgn-git-hub!
Do you have solve it?
Do you have any workaround for this issue?
TIA

**Comment by fgn-git-hub** [comment] 2015-04-13 08:40
Nothing so far, no one answered and I didn't find any solution till now. 
Any help would be great.

**Comment by dopegaar** [comment] 2015-04-13 09:23
Sorry, i cannot help you!
I have the same issue...

**Comment by fgn-git-hub** [comment] 2015-04-22 15:20
I've checked it out now, it's definitly a problem connected to the ldap integration. 
Without ldap the Salt Password button shows up without any problem, and works like a charm. 
Someone in here who does know what could fix that problem? I'm not sure if I understand that LDAP code part so I am out of ideas for the time being.

**Comment by Ackak** [comment] 2015-04-27 20:59
If you remplace the code (line 227 file index.php), the menu appears :
`(isset($_SESSION['settings']['ldap_mode']) && $_SESSION['settings']['ldap_mode'] == 1) || $_SESSION['user_admin'] == 1 ? ' ' :`
with
`(isset($_SESSION['settings']['ldap_mode']) && $_SESSION['settings']['ldap_mode'] == 1) || $_SESSION['user_admin'] == 1 ? '  ' :`

The only change, i have add a space between the two apostrohpe at the end of the line.

**Comment by fgn-git-hub** [comment] 2015-05-05 13:21
Wow, great thank you, that's the solution.

**Comment by dopegaar** [comment] 2015-05-14 08:36
With this change I agree with jensdepuydt (comment on 10 feb). The button is visible but not the behaviour. It's only for me?
TIA

**Comment by fgn-git-hub** [comment] 2015-05-14 13:24
It's strange, I could fill that space with new entries but after logging out an renewed login I can't access them anymore. "You don't have permisssion ...."

**Comment by mobilefactor** [comment] 2015-06-26 22:10
Anybody figured out how to get this to work in 2.1.22?  Thanks.

**Comment by alikkon** [comment] 2015-07-08 00:51
Looking at the code, toptnc is correct. Currently, if you are using ldap_mode or are an administrator, the application seems to assume that you don't want to be able to set a salt key and just doesn't display that bit of text. Honestly, I'm not entirely sure how the code is working with Ackak's recommended change.

(isset($_SESSION['settings']['ldap_mode']) && $_SESSION['settings']['ldap_mode'] == 1)
||
$_SESSION['user_admin'] == 1
?
''
:

This says:
Check to see if ldap_mode is set, and if so, if it's enabled.
And/Or
Check to see if the user is an administrator.
If either of the above is true
then print nothing
Otherwise continue to the next bit.

The addition of a space here shouldn't actually do anything, unless I'm misreading the statement or it's not doing what it's supposed to be doing.  The check that should probably be happening here, instead of ldap_mode, is whether "Use the login password as SALTkey" is checked, rather than ldap_mode, regardless.

My personal recommendation is to remove the ldap_mode check entirely

**index.php line 227**
`(isset($_SESSION['settings']['ldap_mode']) && $_SESSION['settings']['ldap_mode'] == 1) || $_SESSION['user_admin'] == 1 ? '' :`
replace with:
`$_SESSION['user_admin'] == 1 ? '' :`

Comment out the link to the home page - it's no longer useful. While I didn't remove it entirely, it won't display anymore.
**items.php line 557**
`<u><a href="index.php">'.$LANG['home'].'</a></u>`
replace with:
`<!--<u><a href="index.php">'.$LANG['home'].'</a></u>-->`

Apply the fix so deleted items don't show in the personal folders.
**sources/items.queries.php line 1826**
Add:
`$where->add('i.inactif=%i', 0);`

Flip a permissions check regarding read only access, which prevents personal folder users from adding items. I assume the bang here was negating the entire if, rather than just the first part. Flipping which one is first fixes the issue.
**sources/main.functions.php line 489**
`if (!in_array($folderId, $listReadOnlyFolders) || (isset($pf) && $folderId != $pf['id'])) {`
replace with:
`if ((isset($pf) && $folderId != $pf['id']) || !in_array($folderId, $listReadOnlyFolders)) {`

I also changed the string that's used by Teampass to make it a little clearer (IMHO) that you're not setting a new password, but entering the currently used one.
**includes/language/[language].php**
`'home_personal_saltkey_button' => 'Enter Saltkey',`

I'll try and figure out how to actually contribute properly on Github so I can submit this to the codebase proper. I can't tell how active the project really is right now, so I'll have to nail down whether anyone's paying attention as well.

**Comment by jyemeier** [comment] 2015-07-29 16:26
I have a ro issue with personal folders on a fresh 2.1.23.  I did some hammering on it this morning.  I did alikkon's changes and still had issues.

If I am reading this right,  **main.functions.php lines 489:501** is checking if the folder in question is a personal folder or not in the list of read only folders, and then checking the database to see if it has a write parameter set.  But the array **$listReadOnlyFolders** is empty at the beginning of that foreach block, and so that if statement always evaluates to true for every iteration of the foreach block because of the **or**.  Since we are adding folders to the $listReadOnlyFolders array if they don't have a w in the DB::query statement, it seems redundant to check $listReadOnlyFolders as part of the if, and logically an error.

So, I suggest, in **main.functions.php line 489** to replace
`if (!in_array($folderId, $listReadOnlyFolders) || (isset($pf) && $folderId != $pf['id'])) {`
with 
`if ((isset($pf) && $folderId != $pf['id'])) {`

That would say, then, that if it's not a personal folder, check the DB to see if it's got write permissions.  If it doesn't, then add it to the $listReadOnlyFolders array.

I tested this on my fresh install of 2.1.23, and I watched my personal folders change from RO to W and I was able to add an entry.  I also did the rest of alikkon's changes.

**Comment by lsascha** [comment] 2015-09-01 12:08
had the same issue with a fresh 2.1.23 install.

@jyemeier
only changed your part in sources/main.functions.php in line 489 and bam. personal folders work and there is no eye anymore in front of it in the tree.

Thanks

**Comment by fgn-git-hub** [comment] 2015-09-13 03:15
Thank you for that hint about the $listReadOnlyFolders, but it worked only for the entries I already had in that personal folder. After I added a new folder, I got a readonly access for the new folder once again. Any idea how to get that folder rw again?

**Comment by nilsteampassnet** [comment] 2015-09-13 09:38
Coming back to this issue.
Indeed the ldap condition is wrong to enable saltkey dialogbox.

See #1024 for new folder in PF

**Comment by ItecorSupport** [comment] 2015-09-17 13:22
After applied alikkon's changes  and last jyemeier's modification and change Teampass config to allow item, folders etc.. to have same name. The personal folder worked! I can create items without problems. I work like this during 10 days. but if I delete in my Internet browser cookies. I can't access my personal folder that's a normal situation because there no cookie with my salt key. So I need to enter it but after that I can't access it. Teampass tell me "You should enter you personal saltkey ...". Same way if I disable cookies option in Teampass.

**Comment by pojanisu** [comment] 2015-10-24 13:52
I'm in the same place with ItecorSupport. I've done the changes mentioned on this issue and personal items work, I can edit and add them. 

But from other browser (without the cookie) I can only see that I have personal items. Setting the salt key does not work. I can't really make out what it does when clicking Save. It reloads, but I can't see the Done text. Maybe the issue is related to storing the salt key?

**Comment by fpaquet** [comment] 2015-10-25 16:58
Entering saltkey in current Git master (2.1.23.4) still has problems.

We have checked out several browsers: 
- Chromium 42.0.2311.152, Chrome 46.0.2490.80
  Opera 12 and Opera 32.0.1948.69,  Arora 0.11.0, Firefox 38.3.0
- in Arora it worked 1 time, stored to cookie
  when setting the key again, the previous key is displayed as ******
- in all other Browsers, i wasn't able to store the salt key, 
  when setting the key again, the no previous key is visible
- in Arora, a Cookie named 'TeamPass_PFSK...' is still there
- in all other Browsers, there is NO cookie named 'TeamPass...'

Clearing web data (including cookies) doesn't help.
The Text 'Done!' is displayed, but the key isn't stored (wherever it shoud be).

Settings: 
- PF enabled
- Use the login password as SALTkey - OFF  (changing the pw will kill all items)
- Enable personal SALTKey to be stored in a cookie - doesn't matter ON or OFF
- Personal SALTKey cookie DAYS life time before expiration - 31 or 0 (doesnt matter)

This bug is a killer, because it prevents us from migrating to TeamPass!

**Comment by nilsteampassnet** [comment] 2015-10-26 07:37
​I've performed tests on Firefox (41) and Chrome (44) on next 2.1.24​.
I've tried with PSK not stored in COOKIE (it is a SESSION used), and stored
in a COOKIE, and I could not reproduce this isue you have.

​Can you have a try to use the package from branch "development"?

**Comment by fpaquet** [comment] 2015-10-26 09:04
Hello Nils

Wie pulled the master branch from GitHub
git clone https://github.com/nilsteampassnet/TeamPass.git
git checkout master

Cookie storage doesn't depend on any Browser-Plugins ?

**Comment by fpaquet** [comment] 2015-10-26 14:56
Checkt out development branch  - git checkout development
- Browser: Chromium Version 42.0.2311.152 custom (64-bit)
- Cleared all Broswer-Cookies
- Reconfigured TeamPass to store PF Keypass in Cookies

After setting the Passkey, the following data is stored in the Browser:
Cookies
- KEY_PHPSESSID
- PHPSESSID
- jstree_select Content 7

Local Storage
- https://cms.opag.ch

Session Storage
- https://cms.opag.ch

The keypass doesn't set any cookies.

**Comment by fpaquet** [comment] 2015-10-26 15:07
I've recorded all HTTP Headers while setting the passkey.

There are 75 https requests, all of them sending this:

KEY_PHPSESSID=4Qtc%2BZfWrBgjrFaNX3ZJRWVJONp5HH8Q0qlkC50sPlU%3D%3AU1oVk8tQ%2FHyMfQtW3l94GjP0ZCGFQ5IXCv8lKEpop%2FM%3D;
PHPSESSID=bm21gstv8sg78cverejtm9pf06;
jstree_select=7

Only Request No 73 sets the following cookie:

Set-Cookie	jstree_select=7; expires=Thu, 26-Nov-2015 15:01:00 GMT; Max-Age=2678400; path=/

Thus, the Keypass Cookie is never sent by the server.

**Comment by nilsteampassnet** [comment] 2015-10-26 15:47
​As I can't reproduce, it is really hard to work on this issue.

Can you provide me an access to your teampass instance (contact by email)?​

**Comment by fpaquet** [comment] 2015-10-26 17:03
Yes, no problem. Sent your login credentials to teampass

**Comment by fpaquet** [comment] 2015-10-26 17:05
Sent you login credentials to nils@teampass.net
Pse let me know if we can do anything further...

**Comment by fpaquet** [comment] 2015-10-27 09:35
If you could point me to the php code that generates the keypass cookie, we could do further investigations and generate a trace of what happens.

**Comment by nilsteampassnet** [comment] 2015-10-27 12:34
​The cookie for PSK is set in sources/main.queries.php file in case
"store_personal_saltkey".

I'm wondering if your cookie duration​ is defined to value 0. Indeed in
this case, the code is not protected and the cookie is created but deleted
just after because its duration is expired.

You can try to replace
```
setcookie(
                "TeamPass_PFSK_".md5($_SESSION['user_id']),
                encrypt($_SESSION['my_sk'], ""),
                time() + 60 * 60 * 24 *
$_SESSION['settings']['personal_saltkey_cookie_duration'],
                '/'
            );
```
​by
​```setcookie(
                "TeamPass_PFSK_".md5($_SESSION['user_id']),
                encrypt($_SESSION['my_sk'], ""),

(!isset($_SESSION['settings']['personal_saltkey_cookie_duration']) ||
$_SESSION['settings']['personal_saltkey_cookie_duration'] == 0) ? time() +
60 * 60 * 24 : time() + 60 * 60 * 24 *
$_SESSION['settings']['personal_saltkey_cookie_duration'],
                '/'
            );
```

**Comment by fpaquet** [comment] 2015-10-27 17:45
Ups, this produces errors in the log:
[Tue Oct 27 18:37:34 2015] [error] [client 157.161.148.229] PHP Parse error:  syntax error, unexpected ':' in /var/www/html/TeamPass/sources/main.queries.php on line 535, referer: https://cms.opag.ch/TeamPass/index.php?page=items

**Comment by fpaquet** [comment] 2015-10-27 17:48
Here's a hint:

Changing the code in main.queries.php line 535ff to:

    case "store_personal_saltkey":                                                                                              
error_log("1");                                                                                                                 
        $dataReceived = prepareExchangedData(str_replace("'", '"', $_POST['data']), "decode");                                  
error_log("2");                                                                                                                 
        if ($dataReceived['psk'] != "") {                                                                                       
error_log("3");                                                                                                                 
            $_SESSION['my_sk'] = str_replace(" ", "+", urldecode($dataReceived['psk']));                                        
error_log("4");                                                                                                                 
            $x = setcookie(                                                                                                     
                "TeamPass_PFSK_".md5($_SESSION['user_id']),                                                                     
                encrypt($_SESSION['my_sk'], ""),                                                                                
                time() + 60 * 60 * 24 * $_SESSION['settings']['personal_saltkey_cookie_duration'],                              
                '/'                                                                                                             
            );                                                                                                                  
error_log("setkookie = $x");                                                                                                    
        }                                                                                                                       
        break;                                                                                                                  

---- this results in the error log 

[Tue Oct 27 18:46:36 2015] [error] [client 157.161.148.229] 1, referer: https://cms.opag.ch/TeamPass/index.php?page=items
[Tue Oct 27 18:47:07 2015] [error] [client 157.161.148.229] 1, referer: https://cms.opag.ch/TeamPass/index.php?page=items
[Tue Oct 27 18:47:07 2015] [error] [client 157.161.148.229] 2, referer: https://cms.opag.ch/TeamPass/index.php?page=items

**Comment by fpaquet** [comment] 2015-10-27 17:51
The folloging condition is not met:
if ($dataReceived['psk'] != "") {

**Comment by nilsteampassnet** [comment] 2015-10-28 09:44
​Can you tell me if you have any quote in your PSK?

**Comment by nilsteampassnet** [comment] 2015-10-28 09:54
​Can you please try to change
```
        $dataReceived = prepareExchangedData(str_replace("'", '"',
$*POST['data']),
"decode");*
```​

​```
        $dataReceived = prepareExchangedData($_POST['data'], "decode");
        $dataReceived['psk'] = str_replace("'", '"', $dataReceived['psk']);
```​

**Comment by fpaquet** [comment] 2015-10-28 10:37
No, there is no quote in the PSK i entered, just a simple dictionary word, just small letters.

if $dataReceived['psk'] contains the previous PSK, isn't the condition simply wrong?
In order to set a fresh psk, we do not need to have an old psk ?

**Comment by nilsteampassnet** [comment] 2015-10-28 11:41
​You should not change the PSK.
The PSK is used to encrypt the personal passwords.
If you don't use the same PSK for encoding and decoding, then the result is
empty.

If a user wants to change the PSK, it is required to use "Change it"
feature from the PSK sub-menu.​

**Comment by fpaquet** [comment] 2015-10-28 12:37
Yes, this is clear, but you have 3 Situations there:

1. Store the personal saltkey Line 538
   if ($dataReceived['psk'] != "") --> if it is not empty

2. change salt Line 590
   if ($_POST['key'] != $_SESSION['key']) break on Line 553

3. Reset the personal saltkey Line 629
   if (!empty($_SESSION['user_id']) && !empty($_POST['sk']))  --> if not empty

---
i'm not quite sure what's stored in $dataReceived ?
What is the difference between $dataReceived['psk'] and $_SESSION['my_sk'] ? Line 530/539

**Comment by fpaquet** [comment] 2015-10-31 09:24
What PHP version do you use ? 
We use php 5.5.29.

**Comment by fpaquet** [comment] 2015-10-31 14:53
Pulled your quoting changes from development branch 
(commit 2db1592e20cdc1e496dac9fe0398ab9189d07d61)

Great - setting the PSK works now !!!

**Comment by fpaquet** [comment] 2015-10-31 15:13
Now, when trying to change the PSK, it says --> "No personnal saltkey provided"

I'm slowly starting to understand what happens:

The code for "change_personal_saltkey" only works if encrypted communication is turned OFF.

First of all, i've modified main.queries.php line 550 
-  $dataReceived = prepareExchangedData(str_replace("'", '"', $_POST['data_to_share']), "decode");
+ $dataReceived = prepareExchangedData($_POST['data_to_share'], "decode");
+ $dataReceived['psk'] = str_replace("'", '"', $dataReceived['psk']);

Switching encrypted communication OFF, we found out that json_decode() fails because of wrong quotes (Webserver is sending  single quotes while JSON uses double quotes)

Thus we need 1. decrypt 2. replace quotes 3. json_decode

**Comment by nilsteampassnet** [comment] 2015-11-02 12:30
​Well I've checked the complete code for "PSK features", and there was some
bad things.I've made expected changes to make this part more robust​ and
performed a couple of tests.

But those changes will have an impact on existing personal items in the
case that the PSK contains a single or double quotes. In such case, the
passwords will be lost.

So before applying the release 2.1.24, it will be required to warn your
users and ask them to change their saltkey by one that doesn't contain a
single quote or a double quotes.

I've commited the changes.

**Comment by fpaquet** [comment] 2015-11-03 09:16
Hello Nils, to thank you for your cooperation, we have donated $250 today.

Next weekend, I will set up a test server to check out the fixed in 2.1.24.

**Comment by pojanisu** [comment] 2015-11-03 11:47
Nils/fpaquet thanks for your efforts. I just grabbed the development branch and I'm trying to test it. Question: do I need the database migration for this, so do I need to run /install/upgrade.php?

The reason I'm asking is that I did that and run into some issues. Seems that the user gets in but is then thrown out immediately. Also admin login does not work, it just complains "this user does not exist", even though the user is in the database and is not disabled.

I'll try again with fresh database copy, but if there are testing tips, I'm all ears.

**Comment by nilsteampassnet** [comment] 2015-11-03 11:57
​Hello Fredy,

Many thanks for your support for this projet.​

Don't hesitate to come back to me.

**Comment by fpaquet** [comment] 2015-11-03 12:22
@pojanisu - try looking at the Webserver-logs, 
are there any messages while trying to login?

**Comment by pojanisu** [comment] 2015-11-03 12:58
I restored the database, logged in as admin and saw the "you should update"-notice. Then run .../install/upgrade.php which went through fine.

After that I was able to log in with my user and saw the personal key dialog. Selected cancel, went to enter the personal key. Then did the upgrade.

After that I can see the personal items with correct passwords. Hooray!

The bad news is that the user interface is garbled, icons missing etc. Only chrome works regardless of how much F5/Ctrl+F5 I'm hitting. Probably nothing too major. Ssl_error_log tells me 
PHP Fatal error:  require_once(): Failed opening required '/includes/language/english.php'

index.php line 108 seems to be the problem. I'll try to debug that, I don't think it's useful to spam this issue with ui things that might not be related to this at all.

**Comment by nilsteampassnet** [comment] 2015-11-03 14:49
​@pojanisu, Good to read!

This error you get seems related the language file. Perhaps a bad upload?
Can you try to get the english.php file from latest commit in "development"
branch and reup to your server.

​Now concerning​ the badlooking, it is perhaps related to a server cache.

**Comment by fpaquet** [comment] 2015-11-07 14:39
Hello Nils, I've tested 2.1.24 pre-production 
development commit a9cd3b8c1361a86603899e31532a6fd6082e8017

Looks, good
- setting personal SALTKEY with or without encrypted communication - works
- changing personal SALTKEY with or without encrypted communication - works
- changing communication encrpytion setting - doesn't kill personal SALTKEY - works

Moving "change personal SALTKEY" into personal profile was really a good idea!

--- found a few bugs
- in the item list icons for login, password and favourite are displayed, 
  the tooltip on the password icon is wrong, it's the same as on the login icon, "copy username"

- moving items from personal directory to public directory or back kills the password
- copying items from personal directory to public directory results in scrambled password

**Comment by nilsteampassnet** [comment] 2015-11-09 12:13
​@fpaquet, Thank you for your feedback.

I've just committed the correction for the bugs you identified.​

**Comment by fpaquet** [comment] 2015-11-21 16:30
Tested
- move item from personal to public folder and back
- copy item from personal to public folder and back
working fine now.

Thank you.

**Comment by Sailing74** [comment] 2015-12-12 19:36
Not sure if this is the right place, or if I should rather open a new issue. I just upgraded from 2.1.20 to 2.1.24.4, and I have a similar or even the same issue: The private folder is read-only. I cannot create or delete anything, just see things.

What works, though, is moving items from the personal to public folders. In public folders, I cannot move anything, but there I can create and delete...?!

The user is not flagged as "read only" in the admin settings for the user.

Happy to take any hint or run tests.

**Comment by Sailing74** [comment] 2015-12-13 09:54
Update: I could work around the issue with public folders by changing the rights in the role definition. Apparently something was converted there differently during the update.

Update2: The issues with the personal folder appear to relate to the fact that I have sub folders in the personal folder. On the main/root level of the personal folder. I can create and delete items. I also cannot find an option to create further or delete existing sub folders in the personal folder. Is this not meant to be used at all? I'm using TeamPass since many versions, so maybe creating sub-folders was possible at some time, but is not anymore?

**Comment by fpaquet** [comment] 2015-12-13 11:53
Creating subfolders in the personal folder has been disabled by nils.

You might want temporary go back to 2.1.20 to move subfolder contents to toplevel, 
before switching to 2.1.24.4 again. 
but be sure to back up your database before trying this.

**Comment by Sailing74** [comment] 2015-12-13 15:53
Thanks, that explains it. I have multiple backups from my attempts, and moving items around works. But how can I remove the old sub-folders in the personal folder? Manually delete them from the teampass_nested_tree table?

**Comment by fgn-git-hub** [comment] 2016-01-30 20:49
I have the same issue using 2.1.23 at the moment I could create new entries in my subdir on my personal folder but now I get those entries with yellow exclamation marks and they won't show up. The other entries in there are readable. Is there any way to get to the new ones?

**Comment by Sailing74** [comment] 2016-01-31 09:19
I could move the entries from the subfolders into the main private folder, and there you can view, modify etc. them ok.
I guess it's just not the design anymore to have subfolders in the private folder.

**Comment by fgn-git-hub** [comment] 2016-01-31 10:26
I could move it as well, but in the main folder it didn't show the details too. Eventhough to the opposite it showed up one time only in the subfolder. Can someone tell me what the bookmark sign with the exclamation mark is meant to say?

**Comment by Sailing74** [comment] 2016-01-31 15:50
I have the exclamation mark as well, but it is working for me. I only do not see the details, if I did not enter the right key.

**Closed** 2017-07-29 06:16 UTC
