### ISSUE TITLE
No error message when duplicate item names at personal keys

### ISSUE THREAD

**Issue by Jurik81** [nilsteampassnet/TeamPass#1828] opened 2017-07-26 09:02 UTC
### Steps to reproduce
1. Create item in personal folder
2. Name it like an item someone already has in his personal folder

Settings "Items may have duplicate name" should be turned off.

### Expected behaviour
Show error message that explains what went wrong

### Actual behaviour
There is a message shown for approx 0.2 seconds - see attachment.
It was quite a challenge to get this screenshot.
![accesstopassworditemdenied](https://user-images.githubusercontent.com/5330316/28613114-b723c46e-71f1-11e7-8250-3fe343322d5d.png)

### Server configuration
**Operating system**:
Debian
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
5.6
**Teampass version:** 
2.1.27
**Updated from an older Teampass or fresh install:**
fresh install
### Client configuration
**Browser:**
Chrome
**Operating system:**
MacOSX & Linux Debian
#### Web server error log
no entries that belong to this 

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
Link for how to does not work anymore.

**Comment by nilsteampassnet** [comment] 2017-07-26 11:05
Thank you for reporting.

I will investigate.

**Comment by nilsteampassnet** [comment] 2017-07-26 16:37
I cannot reproduce.

I have set to off the option `Items may have duplicate name`.
Then I created item `perso1` with User1.
And created item `perso1` with User2 without any issue.

Perhaps an other option combination.
Can you attach your file `/includes/config/tp.config.php`?

**Comment by Jurik81** [comment] 2017-07-27 08:54
Here we go - at this config "Items may have duplicate name" is on, but was off, when the error occurred. 

```
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'Y-m-d',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/srv/teampass',
    'cpassman_url' => 'https://xxx',
    'favicon' => 'https://xxx/favicon.ico',
    'path_to_upload_folder' => '/srv/teampass/upload',
    'url_to_upload_folder' => 'https://xxx/upload',
    'path_to_files_folder' => '/srv/teampass/files',
    'url_to_files_folder' => 'https://xxx/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '5',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '1',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '1',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1498307020',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'smtp.xxx',
    'email_smtp_auth' => '1',
    'email_auth_username' => 'teampass@xxx',
    'email_auth_pwd' => 'xxx',
    'email_port' => '587',
    'email_security' => 'tls',
    'email_server_url' => '',
    'email_from' => 'teampass@xxx',
    'email_from_name' => 'Teampass Admin',
    'pwd_maximum_length' => '128',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '10',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/srv/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'copy_to_clipboard_small_icons' => '1',
);

**Comment by nilsteampassnet** [comment] 2017-07-27 16:37
I found a improvement possibility.

I have committed a fix in a commit in `Development` branch.

Thank you

**Closed by nilsteampassnet** 2017-07-27 16:37 UTC
Labels: 2.1.27, bug
