### ISSUE TITLE
In CSV import from keepass, Don't respect  1st label "label" and set ZERO

### ISSUE THREAD

**Issue by otrochavon** [nilsteampassnet/TeamPass#1388] opened 2016-07-19 18:57 UTC
Hi Nils!!! 
Im using teampass 2.1.26 and I have a problem..  

In keepass import, dissapears  1st column.

CSV example: 
```

"label","Login","Password","URL","Comments"
"label2","login2","unapass123","www.something.com","some comment2"
```

![teampass1](https://cloud.githubusercontent.com/assets/3331520/16962678/00ce187e-4dc9-11e6-9ced-0cfa53fa8844.png)

And the label **label2** disappears and in it place I see ZERO

![teampass2](https://cloud.githubusercontent.com/assets/3331520/16962763/793d3470-4dc9-11e6-94ac-d48989c85f0f.png)

Love your soft!
Congrats. 
Javier from Argentina.

**Comment by otrochavon** [comment] 2016-07-19 19:43
Hi, 

in https://github.com/nilsteampassnet/TeamPass/blob/master/sources/import.queries.php
I see line 259
* in git:
`    'label' => substr($item[0], 0, 500),`
in my code
`           'label' => substr($item[0], 500),     `

I correct this and work fine!

**Comment by nilsteampassnet** [comment] 2016-07-19 20:12
Duplicate of #1380
Corrected in package 14

**Closed by nilsteampassnet** 2016-07-19 20:12 UTC
Labels: Duplicate

**Comment by otrochavon** [comment] 2016-07-19 20:21
Yeah, I don't see #1380 Thanks!!
