### ISSUE TITLE
Blank page after enabling LDAP

### ISSUE THREAD

**Issue by meoso** [nilsteampassnet/TeamPass#2023] opened 2017-11-17 20:04 UTC
### Steps to reproduce
1. Fresh install: Ubuntu 16.04, LEMP
2. Initial config then Manage Settings>Options>LDAP>
3. Enable LDAP.  Enter configs, click-away.
3b.  May have something to do with clicking into Administrator's profile, As i have done this at several places and it corrupts the current logged-in session.

`    'ldap_new_user_is_administrated_by' => '0'` is created without a trailing comma (`,`)

### Expected behaviour
website working

### Actual behaviour
website was a blank page. (empty iframe)

### Resolution / Fix
Manually edit `includes/config/tp.config.php` to include comma behind `ldap_new_user_is_administrated_by`

### Server configuration
**Operating system**:
Ubuntu 16.04.3 LTS
Linux teampass 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
nginx version: nginx/1.10.3 (Ubuntu)

**Database:**
mariadb-server 10.0.31-MariaDB-0ubuntu0.16.04.2

**PHP version:**
PHP 7.0.22-0ubuntu0.16.04.1

**Teampass version:**
Release 2.1.27.10

**Teampass configuration file:**

**Fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1483653/tp.config.php.txt)

### Client configuration
**Browser:**
Firefox 64bit 56.0.2

**Operating system:**
Debian 9

#### Web server error log
`/var/log/nginx/error.log`
```
2017/11/17 13:50:45 [error] 1197#1197: *161 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ''copy_to_clipboard_small_icons' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /var/www/html/teampass/includes/config/tp.config.php on line 121" while reading response header from upstream, client: 10.50.5.47, server: teampass.DOMAIN.TLD, request: "GET /index.php?page=manage_settings&language= HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "teampass.DOMAIN.TLD", referrer: "https://teampass.DOMAIN.TLD/index.php?page=manage_settings"
```

**Comment by nilsteampassnet** [comment] 2017-11-18 09:07
Thank you for reporting.

In fact this issue is not related to LDAP but to the feature that updates the config file.
Nevertheless I have fixed this in a previous commit.

I would like to know when did you download the 2.1.27.10 package? The date is important because it will help me to know if this is a new bug or if a more recent package would fix it.

Thanks

**Comment by meoso** [comment] 2017-11-20 16:56
The download was Fri Nov 17 AM CST.

**Comment by nilsteampassnet** [comment] 2017-11-22 20:48
This embarrassing me as I cannot reproduce and after careful code review I cannot understand how this could happen.

Can you attach here the file main.functions.php? perhaps doesn't it include the fix I've previously done.

**Comment by nilsteampassnet** [comment] 2017-11-23 12:00
Duplicate of #2027

I think I found the reason and will commit a fix.

**Comment by nilsteampassnet** [comment] 2017-12-07 19:59
No news.
I'm closing it
Please reopen if needed

**Closed by nilsteampassnet** 2017-12-07 19:59 UTC
Labels: Answered
