### ISSUE TITLE
Upgrading from 2.1.27.36 to 3.0.0.20 -> Once loged in as admin, all menu options not working 

### ISSUE THREAD

**Issue by amilhub** [nilsteampassnet/TeamPass#3404] opened 2022-11-07 17:32 UTC
### Steps to reproduce
1. Upgrade from 2.1.27.36 to 3.0.0.20
2. Upgrade process successful.
3. I can login with admin account, but in menu options none works. The link is always 'index.php?page=admin#'

### Expected behaviour
Working menu

### Actual behaviour
Menu options not working. All links goes to 'index.php?page=admin#' and this do nothing.

### Server configuration
**Operating system**: CentOS 7 

**Web server:** Apache httpd 2.4.6

**Database:** mysql  Ver 15.1 Distrib 10.2.44-MariaDB

**PHP version:** 7.4.33

**Teampass version:** 3.0.0.20

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Upgrade from 2.1.27.36 to 3.0.0.20

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
No webserver errors

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Firefox:
Uncaught SyntaxError: '' string literal contains an unescaped line break

Chrome:
Uncaught SyntaxError: Invalid or unexpected token (at index.php?page=admin:1197:29)
```

**Comment by amilhub** [comment] 2022-11-08 09:21
Update:
This happens with '/includes/config/tp.config.php' setting default language in spanish:

'default_language' => 'spanish',

With english, menu is working as expected:

'default_language' => 'english',

**Comment by Virtosaurus** [comment] 2023-01-10 05:10
Fresh install Debian 11.6 and Teampass, after Admin login and changing "default language" from "english" to "russian", Log out, Log in  and menu not working. Change '/includes/config/tp.config.php' 'default_language' => 'english' - all works again.

**Comment by Kyogre** [comment] 2023-02-02 11:31
Same here on TP 3.0.0.22 with "russian" as default language, fresh install. No problems for "french" or "english".

Web server: apache 2.4.5.4-1.el7.3
Database: MariaDB 10.10.2-2.el7 + mysqlnd 7.4.33
PHP version: 7.4.33-1.el7
Teampass version: 3.0.0.22 (downloaded 02.02.23)

Also I suppose it is duplicate of https://github.com/nilsteampassnet/TeamPass/issues/3430

**Comment by Kyogre** [comment] 2023-03-28 09:37
As I see, for Russian language the issue is fixed by upcoming https://github.com/nilsteampassnet/TeamPass/pull/3616
@vokamut Thank you!

@nilsteampassnet hi! Maybe we could expand this PR for other languages?

**Comment by nilsteampassnet** [comment] 2023-04-01 06:43
Thank you.
Please languages are managed from https://poeditor.com/projects/view?id=433631

**Closed by nilsteampassnet** 2023-04-01 06:43 UTC
