### ISSUE TITLE
After latest pull and re-running upgrade new folders can't be created

### ISSUE THREAD

**Issue by BelgarathS** [nilsteampassnet/TeamPass#3560] opened 2023-03-01 12:06 UTC
Folders cannot be added anymore

### Steps to reproduce
Try to create a folder

### Expected behaviour
Folders should be created

### Actual behaviour
Error is thrown in the backend and nothing happens

### Server configuration
Ubuntu 22.04
Apache2.4
Mariadb10.6

**PHP version: 8.1**

**Teampass version:3.0.23** 

**Updated from an older Teampass or fresh install:updated**

#### Web server error log
```
[Wed Mar 01 09:24:21.657970 2023] [php:warn] [pid 65850] [client 192.168.231.201:59218] PHP Warning:  Undefined variable $folder in /var/www/html/pass/sources/folders.queries.php on line 711, referer: https://banda.pl/pass/index.php?page=folders
[Wed Mar 01 09:24:21.658100 2023] [php:warn] [pid 65850] [client 192.168.231.201:59218] PHP Warning:  Attempt to read property "id" on null in /var/www/html/pass/sources/folders.queries.php on line 711, referer: https://banda.pl/pass/index.php?page=folders
[Wed Mar 01 09:24:21.659005 2023] [php:warn] [pid 65850] [client 192.168.231.201:59218] PHP Warning:  Trying to access array offset on value of type null in/var/www/html/pass/sources/folders.queries.php on line 732, referer: https://banda.pl/pass/index.php?page=folders
[Wed Mar 01 09:24:21.659090 2023] [php:error] [pid 65850] [client 192.168.231.201:59218] PHP Fatal error:  Uncaught TypeError: json_decode(): Argument #1 ($json) must be of type string, null given in /var/www/html/pass/sources/folders.queries.php:732\nStack trace:\n#0 /var/www/html/pass/sources/folders.queries.php(732): json_decode()\n#1 {main}\n  thrown in /var/www/html/pass/sources/folders.queries.php on line 732, referer: https://banda.pl/pass/index.php?page=folders```

**Comment by nilsteampassnet** [comment] 2023-03-02 07:41
Duplicate of #3557

**Closed by nilsteampassnet** 2023-03-02 07:41 UTC
