### ISSUE TITLE
Not allowed to delete a password

### ISSUE THREAD

**Issue by river29** [nilsteampassnet/TeamPass#2583] opened 2019-03-27 08:39 UTC
<!--
Thanks for reporting issues back to Teampass! 
This is ONLY for ISSUE / DEFECT / BUG.

### Steps to reproduce
1. Fresh Install on Debian9.8
2. Create a users, roles,.... and passwords
3. Try to delete a password in user role RW directory and get this message ( You are not allowed to do that!)
(In 2 times i deteted a password successfully (Once after force reload page the other just after closed the user popup).

### Expected behaviour
When i clic on delete item, the item was deleted.

### Actual behaviour
When i clic on delete item, i get the message "You are not allowed to do that!"

### Server configuration
**Operating system**: Linux V-YO 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64

**Web server:** Apache/2.4.25 (Debian)

**Database:** 5.5.5-10.1.37-MariaDB-0+deb9u1

**PHP version:** 7.0.33-0+deb9u3

**Teampass version:** 2.1.27.35

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '1',
'log_connections' => '0',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '1',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '1',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/html/teampass',
'cpassman_url' => 'http://<anonym_url>/teampass
'favicon' => 'http://<anonym_url>/teampass/favicon.ico',
'path_to_upload_folder' => '/var/www/html/teampass/upload',
'url_to_upload_folder' => 'http://<anonym_url>/teampass/upload',
'path_to_files_folder' => '/var/www/html/teampass/files',
'url_to_files_folder' => 'http://<anonym_url>/teampass/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '2.1.27',
'ldap_mode' => '0',
'ldap_type' => '0',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'ldap_port' => '389',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '1',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '1',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'french',
'send_stats' => '0',
'send_statistics_items' => '',
'send_stats_time' => '1550593607',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '1',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '',
'email_smtp_auth' => '',
'email_auth_username' => '',
'email_auth_pwd' => '<removed>'
'email_port' => '',
'email_security' => '',
'email_server_url' => '',
'email_from' => '',
'email_from_name' => '',
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '1',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '1',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '60',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/html/teampass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '1',
'create_item_without_password' => '1',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Paris',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'bck_script_passkey' => '<removed>'
'admin_2fa_required' => '1',
'can_create_root_folder' => '1',
'teampass_version' => '2.1.27',
);
```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:** Firefox - 66.0

**Operating system:** Windows Server 2008 R2 / 7 - 64bits

#### Web server error log
```
Constant COST already defined - /var/www/html/teampass/includes/config/settings.php (19)
```

#### Teampass 10 last system errors
```
 * 21/03/2019 17:31:24 - Query: SELECT i.id as id, i.restricted_to as restricted_to, i.perso as perso, i.label as label,
        i.description as description, i.pw as pw, i.login as login, i.anyone_can_modify as anyone_can_modify,
        l.date as date
    FROM teampass_items as i
    INNER JOIN teampass_log_items as l ON (i.id = l.id_item)
    WHERE i.inactif = 0
    AND (l.action = 'at_creation' OR (l.action = 'at_modification' AND l.raison LIKE 'at_pw :%'))
    AND i.id_tree IN ()
    ORDER BY i.label ASC, l.date DESC<br />Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
    ORDER BY i.label ASC, l.date DESC' at line 8<br />@ /teampass/index.php?page=kb
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
``` none
Insert the log here and especially the answer of the query that failed.
```

**Comment by river29** [comment] 2019-03-27 08:56
HI, 


I get this message when i try to delete a password with User allowed to RW in directory and childs : 

report was created with user **reseau2**

Screenshots was made under admin account

![Teampass bug 1](https://user-images.githubusercontent.com/27784681/55061756-d155cb80-5074-11e9-89c7-afaaac9d2422.png)


the admin configuration was under :+1: 

![Teampass bug 2](https://user-images.githubusercontent.com/27784681/55061836-fcd8b600-5074-11e9-9e18-2dab9fe17e86.png)


![Teampass bug 3](https://user-images.githubusercontent.com/27784681/55062077-8092a280-5075-11e9-9521-dfdcf7fa084f.png)


![Teampass bug 4](https://user-images.githubusercontent.com/27784681/55062086-838d9300-5075-11e9-9c67-0c51771878bc.png)







### Steps to reproduce
1. Fresh install of teampass
2. Create directory users roles and password
3. try to delete a password (you get this message : " You are not allowed to do that!")

### Expected behaviour
When i clic on "delete Item" i get the popup "You are not allowed to do that!"


### Actual behaviour
When i clic on "delete Item " the Item was deleted

### Server configuration
**Operating system**: Linux V-YO 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64

**Web server:** Apache/2.4.25 (Debian)

**Database:** 5.5.5-10.1.37-MariaDB-0+deb9u1

**PHP version:** 7.0.33-0+deb9u3

**Teampass version:** 2.1.27.35

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '1',
'log_connections' => '0',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '1',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '1',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/html/teampass',
'cpassman_url' => 'http://<anonym_url>/teampass
'favicon' => 'http://<anonym_url>/teampass/favicon.ico',
'path_to_upload_folder' => '/var/www/html/teampass/upload',
'url_to_upload_folder' => 'http://<anonym_url>/teampass/upload',
'path_to_files_folder' => '/var/www/html/teampass/files',
'url_to_files_folder' => 'http://<anonym_url>/teampass/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '2.1.27',
'ldap_mode' => '0',
'ldap_type' => '0',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'ldap_port' => '389',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '1',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '1',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'french',
'send_stats' => '0',
'send_statistics_items' => '',
'send_stats_time' => '1550593607',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '1',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '',
'email_smtp_auth' => '',
'email_auth_username' => '',
'email_auth_pwd' => '<removed>'
'email_port' => '',
'email_security' => '',
'email_server_url' => '',
'email_from' => '',
'email_from_name' => '',
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '1',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '1',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '60',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/html/teampass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '1',
'create_item_without_password' => '1',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Paris',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'bck_script_passkey' => '<removed>'
'admin_2fa_required' => '1',
'can_create_root_folder' => '1',
'teampass_version' => '2.1.27',
);
```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:** Firefox - 66.0

**Operating system:** Windows Server 2008 R2 / 7 - 64bits

### Logs

#### Web server error log
```
Constant COST already defined - /var/www/html/teampass/includes/config/settings.php (19)
```

#### Teampass 10 last system errors
```
 * 21/03/2019 17:31:24 - Query: SELECT i.id as id, i.restricted_to as restricted_to, i.perso as perso, i.label as label,
        i.description as description, i.pw as pw, i.login as login, i.anyone_can_modify as anyone_can_modify,
        l.date as date
    FROM teampass_items as i
    INNER JOIN teampass_log_items as l ON (i.id = l.id_item)
    WHERE i.inactif = 0
    AND (l.action = 'at_creation' OR (l.action = 'at_modification' AND l.raison LIKE 'at_pw :%'))
    AND i.id_tree IN ()
    ORDER BY i.label ASC, l.date DESC<br />Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
    ORDER BY i.label ASC, l.date DESC' at line 8<br />@ /teampass/index.php?page=kb
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```


PS1, i put the description in the issue oppening, but i see a message "No description provided" So i put the rewrite description just upper this text


PS2, Sorry for my english, it's not my language, and i try to keep comprehensible

Best regards 

Yoann RIVIERE

**Comment by pe1rjw** [comment] 2019-03-27 09:51
I have the exact same problem as decribed as above.
I can delete items as a user when using mass-update (search) but deleting 1 item from the passwordlist gives exactly the same error.
Nothing is added to the apache-logs.

**Comment by IlluminatorCologne** [comment] 2019-04-04 05:54
I can confirm the issue, that items cannot be deleted using a clean installation of 2.1.27.35. -> 'error_not_allowed_to'

In addition I cannot see the cross at the left of items for drag and drop items - even if I just created them. This seems to be a similar permission issue and might be caused by the same bug.

**Comment by Antyrael** [comment] 2019-04-04 06:52
Same problem here, upgraded from an older version. currently on 2.1.27.
User is Manager and everything is allowed on the target folder.

**Comment by lulakmk** [comment] 2019-04-10 15:42
I did the new installation and same problem. I need delete the folder to delete items together. :(

**Comment by UserI404** [comment] 2019-04-17 06:24
Same Problem here. :/ Version 2.1.27.33

**Comment by unki** [comment] 2019-04-18 06:59
I'm experiencing something similar now - for me on _2.1.27.35_.

I'm creating _folders_ and _items_ via the API - with a _global_ API key, not a _personal_ one.

Then - as a _user_ that has apparently all permissions on that folder and also it's parent folders - I'm not allowed to delete an item out of one of these _API-created_ folders.

Of course I'm allowed to add _add_ and _update_ items in one of these folders.

**Comment by unearthlyjester** [comment] 2019-04-26 23:50
So after a lot of troubleshooting and going through the code. I found this worked for me. See my note below.  

User gets an error message that they are not allowed to do the delete.  It appears based off testing that accessLevel always stays 2.  I think this is because variable $accessLevel is never updated with a new value.

I made this change in source/items.queries.php and it seemed to resolve the issue. Fix follows //RBR fix. Now my write (W) user can delete items in my test folder, but my "ND" user can not.  I am sure my array handling there is not the greatest, but php is not my strongest language.  

       // check role access on this folder (get the most restrictive) (2.1.23)
                $accessLevel = 2;
                $arrTmp = [];
                foreach (explode(';', $_SESSION['fonction_id']) as $role) {
                    if (empty($role) === false) {
                        $access = DB::queryFirstRow(
                            "SELECT type FROM ".prefix_table("roles_values")." WHERE role_id = %i AND folder_id = %i",
                            $role,
                            $post_id
                        );
                        if ($access['type'] === "R") {
                            array_push($arrTmp, 1);
                        } elseif ($access['type'] === "W") {
                            array_push($arrTmp, 0);
                        } elseif ($access['type'] === "ND") {
                            array_push($arrTmp, 2);
                        } else {
                            // Ensure to give access Right if allowed folder
                            if (in_array($post_id, $_SESSION['groupes_visibles']) === true) {
                                array_push($arrTmp, 0);
                            } else {
                                array_push($arrTmp, 3);
                            }
                        }
                    }
                }
                // RBR fix
                if ( sizeof($arrTmp) === 0) {
                        $accessLevel = 2;
                } else {
                        $accessLevel = array_pop($arrTmp);
                }

**Comment by anth69** [comment] 2019-05-07 10:19
Got the same issue on a fresh install. This is a real problem. I tried your code, but it seems the 2 permissions :
Write allowed + Delete forbidden + Edit Allowed (add & delete but don't edit)
Write allowed + Delete forbidden + Edit forbidden (add only)

are not working properly => users get all permissions (R+W+ delete + edit) in both cases.

**Comment by victorbcredidio** [comment] 2019-05-13 14:00
Hey there.
I also tried @unearthlyjester code, and just like @anth69 I can confirm that anyone can delete it.
Even so, that was a really good temporary solution, so thank you @unearthlyjester. 

Still waiting for a response or fix from @nilsteampassnet on this one!

**Comment by estefanoveronesse** [comment] 2019-05-20 14:11
question for @unearthlyjester 
Wich user is the "ND" user? What "ND" means?

**Comment by nilsteampassnet** [comment] 2019-05-25 15:08
Duplicate of #2601

Tracking will be done on this other ticket.

**Closed by nilsteampassnet** 2019-05-25 15:08 UTC
Labels: Under investigation

**Comment by phillipscc** [comment] 2019-05-30 00:57
Ubuntu: 18.04 LTS
TeamPass 2.1.27.35

I'm trying to delete a an Item and I get a message stating that I was not allowed to do that.

![image](https://user-images.githubusercontent.com/51181485/58600893-3f686b80-823b-11e9-80ce-2f8554328121.png)
