### ISSUE TITLE
Can't search items

### ISSUE THREAD

**Issue by c0r3dump3d** [nilsteampassnet/TeamPass#3120] opened 2022-04-05 10:12 UTC
### Steps to reproduce
1. Search an Item from the item toolbar
![image](https://user-images.githubusercontent.com/5602401/161731272-aa88d30b-7fa9-4204-bd0d-17deecd1d921.png)

2. It doesn't work 
### Expected behaviour
Try to search items

### Actual behaviour
The message "Searching ..." continually appears, and the search doesn't return any results:

![image](https://user-images.githubusercontent.com/5602401/161729814-ff95b22a-7ecc-486b-af86-da46773549c6.png)

The search from the other toolbar it works

![image](https://user-images.githubusercontent.com/5602401/161731459-552c8912-3064-42f8-9ca3-984e0c476f79.png)

### Server configuration
**Operating system**: AlmaLinux release 8.5 (Arctic Sphynx)
**Web server:** Server version: Apache/2.4.37 (AlmaLinux)

**Database:** MariaDB 10.3.28-1

**PHP version:** PHP 7.4.28

**Teampass version:** 3.0.0.17

**Teampass configuration file:**

```
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/TeamPass',
    'cpassman_url' => 'https://pwmanager',
    'favicon' => 'https://pwmanager',
    'path_to_upload_folder' => '/var/www/html/TeamPass/upload',
    'path_to_files_folder' => '/var/www/html/TeamPass/files',
    'url_to_files_folder' => 'https://pwmanager/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.14',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '5',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '1',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1645458739',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
     'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/TeamPass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Madrid',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => '*******',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '0',
    'duo_akey' => '',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'teampass_version' => '',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '1',
    'email_debug_level' => '0',
    'can_create_root_folder' => '1',
);
```

**Updated from an older Teampass or fresh install:** Fresh install

### Client configuration
**Browser:** Firefox 98.0.2

**Operating system:** Manjaro Linux 

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

**Comment by nilsteampassnet** [comment] 2022-04-06 04:39
A fix has been committed.
Please reopen if needed.

**Comment by c0r3dump3d** [comment] 2022-04-06 11:36
Hi, I have made `git pull ` 

![image](https://user-images.githubusercontent.com/5602401/161965747-f0173c37-23db-45c4-b76f-9847ac1d8a50.png)

but problem continues:

![image](https://user-images.githubusercontent.com/5602401/161965980-e87e2e55-f78d-47c8-b55f-52e39c28939e.png)

**Comment by nilsteampassnet** [comment] 2022-04-06 16:03
Can you please you provide the error log from apache?
or the output of a tail -f while you are performing this.

Indeed I cannot reproduce.

**Comment by c0r3dump3d** [comment] 2022-04-19 08:40
Hi, when I try to search, now I see these errors in php log file:

```
Trying to access array offset on value of type null in /var/www/html/TeamPass/sources/find.queries.php on line 564
Trying to access array offset on value of type null in /var/www/html/TeamPass/sources/find.queries.php on line 566
Trying to access array offset on value of type null in /var/www/html/TeamPass/sources/find.queries.php on line 568
Trying to access array offset on value of type null in /var/www/html/TeamPass/sources/find.queries.php on line 570
Trying to access array offset on value of type null in /var/www/html/TeamPass/sources/find.queries.php on line 572
```

**Comment by nilsteampassnet** [comment] 2022-04-30 07:56
A fix has been committed.
Please reopen if needed.

**Closed by nilsteampassnet** 2022-04-30 07:56 UTC

**Comment by c0r3dump3d** [comment] 2022-05-03 16:15
Hi, now I see this error and TeamPass it's not working:

`PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/html/TeamPass/sources/main.functions.php on line 3236
`

**Comment by c0r3dump3d** [comment] 2022-05-03 16:38
Hi, now it's working but I have needed to update php to a version 8:

```
# php -v
PHP 8.0.18 (cli) (built: Apr 13 2022 02:45:05) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.18, Copyright (c) Zend Technologies

```

**Comment by nilsteampassnet** [comment] 2022-05-03 16:43
what was your php previously ?

**Comment by c0r3dump3d** [comment] 2022-05-03 18:15
7.4

**Comment by sistemistaitaliano** [comment] 2026-02-03 14:12
After last upgrade to 3.1.6.3 search is broken remain Searching

web browser developer
<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgba(253, 252, 251, 0.1); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: monospace; white-space: pre-wrap; font-size: 12px !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://MYURL/plugins/jquery/jquery.min.js?v=3.1.6.3:2" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; color: rgb(168, 199, 250); text-decoration: underline; outline-offset: 2px; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; background: none; flex: 0 0 auto; white-space: nowrap; cursor: pointer; outline: none; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;"><br class="Apple-interchange-newline">jquery.min.js?v=3.1.6.3:2</button> <devtools-request-link-icon class="resource-links" style="display: inline-block; white-space: nowrap; color: inherit; font-size: inherit; font-family: inherit; box-sizing: border-box; min-width: 0px; min-height: 0px; margin-top: -1px; margin-bottom: -2px;"><button class=" link " title="Click to open the network panel and show request for URL: https://MYURL/sources/find.queries.php?type=search_for_items&amp;limited=false&amp;search=dxi&amp;start=0&amp;length=10&amp;totalItems=0&amp;key=c0add9867e92113413fc2da1df71fdb6" jslog="Link; context: request; track: click" style="border: none; background: transparent; margin: 0px; padding: 0px; font-family: inherit; font-size: inherit; color: inherit; cursor: pointer;"><devtools-icon name="arrow-up-down-circle" role="presentation" style="flex-grow: 0; flex-shrink: 0; display: inline-block; width: 16px; height: 16px; color: rgb(124, 172, 248); vertical-align: middle; position: relative;"><span style="display: block; width: 16px; height: 16px; background-color: currentcolor; mask: url(&quot;devtools://devtools/bundled/Images/arrow-up-down-circle.svg&quot;) 50% 50% / contain no-repeat; --icon-url: url(&quot;devtools://devtools/bundled/Images/arrow-up-down-circle.svg&quot;);"></span></devtools-icon></button></devtools-request-link-icon> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(249, 222, 220) !important;">GET <button class="devtools-link text-button link-style" jslog="Link; context: network-request; track: click" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; color: rgb(168, 199, 250); text-decoration: underline; outline-offset: 2px; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; background: none; flex: 0 0 auto; white-space: nowrap; cursor: pointer; outline: none; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">https://MYURL/sources/find.queries.php?type=search_for_item<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>ch=dxi&amp;start=0&amp;length=10&amp;totalItems=0&amp;key=c0add98<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span></button> 500 (Internal Server Error)</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgba(253, 252, 251, 0.1); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="vbox flex-auto monospace stack-preview-container width-constrained" style="display: inline-block; width: 743px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: monospace; font-size: 12px !important; position: relative; flex-direction: column !important; flex: 1 1 auto;"><div class="widget" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: style;">
  | send | @ | jquery.min.js?v=3.1.6.3:2
-- | -- | -- | --
  | ajax | @ | jquery.min.js?v=3.1.6.3:2
  | S.<computed> | @ | jquery.min.js?v=3.1.6.3:2
  | finishingItemsFind | @ | index.php?page=items:7648
  | searchItems | @ | index.php?page=items:7633
  | (anonymous) | @ | index.php?page=items:6822
  | dispatch | @ | jquery.min.js?v=3.1.6.3:2
  | v.handle | @ | jquery.min.js?v=3.1.6.3:2

</div></div></div>
</body>
</html>
