### ISSUE TITLE
2.1.27.8 - Change language is not possible

### ISSUE THREAD

**Issue by benjamin2501** [nilsteampassnet/TeamPass#1927] opened 2017-09-26 07:41 UTC
after upgrading from 2.1.27.7 to 2.1.27.8 users can't change their language.
This message appears:
![grafik](https://user-images.githubusercontent.com/27355139/30848198-a7cd16ea-a29e-11e7-9723-c9181c16f797.png)
And after that the session gets closed

**Comment by nilsteampassnet** [comment] 2017-09-26 16:32
Im' sorry I cannot reproduce this.
At what moment this message appears?
Can you describe the steps the users are doing to get this?

**Comment by benjamin2501** [comment] 2017-09-27 05:51
@nilsteampassnet 
- Login as LDAP User
- Go to "My Profile"
- Click on the language
- Choose your favorite language (it doesn't matter wich language)
- Click on the green hook
- The message "You are not allowed to see this page" appears

P.S.: With the local admin account I can change my langauge. This error seem only to appear with LDAP users.

![grafik](https://user-images.githubusercontent.com/27355139/30897694-e3172506-a357-11e7-888d-16ac75ba3594.png)

**Comment by byeight** [comment] 2017-09-27 12:52
I have the same error, I use only local accounts, no ldap. A user who is manager has no error, only normal user or readonly.

**Comment by nilsteampassnet** [comment] 2017-09-27 16:27
Could reproduce.

Fix will be committed.

**Closed** 2017-09-27 16:32 UTC
Labels: bug
