### ISSUE TITLE
Constantly displays a sign when entering a personal folder. or when updating the page.

### ISSUE THREAD

**Issue by free-14** [nilsteampassnet/TeamPass#1921] opened 2017-09-23 21:09 UTC
If you select a personal folder or task in a personal folder. Then when you refresh the page or press the button, the window always pops up.
![bug](https://user-images.githubusercontent.com/28634449/30777114-9a9df1c6-a0bc-11e7-8677-1fed6d4f43a4.jpg)

### Steps to reproduce
1. Upgrade 27.7 to 27.8
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
Ubuntu server 16.04

**Web server:Apache: 2.4

**Database: Mysql 5.6

**PHP version: 7.0

**Teampass version: 27.8

**Teampass configuration file:

**Updated from an older Teampass or fresh install: Updated from an older
PLEASE attach to this message the file /includes/config/tp.config.php.

Client configuration

**Browser: OPera 46

**Operating system: Win10

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment] 2017-09-24 07:46
Couldn't reproduce.
Provide the config file

**Comment by free-14** [comment] 2017-09-24 19:05
If you install a new and clean teampass everything works fine. Tell me if it's possible to install a clean teampass and restore from a backup copy of the database (not upgrade)?

**Comment by free-14** [comment] 2017-09-24 19:07
And I'm already tired of downloading .txt make it possible to open them in the browser as jpg.

**Comment by free-14** [comment] 2017-09-24 19:09
So many releases. And there is not one normal without glitches. if something works then in the next version when updating something that happens and stops working.

**Comment by free-14** [comment] 2017-09-24 19:18
You write please a clear system and the characteristics under which your system should work normally. And make a full description of the installation and restore from a backup. You yourself at least once tried to restore from a backup copy ????? just appears the window asks for a password and everything and everything ..... How can I trust passwords to such a project ?? this is not reliable. if something went wrong, it's impossible to return everything. Russian language in the update in the description of constantly becoming (??????????) .... I think until the stable version will be difficult to reach. I really want to help. because the project is very interesting ...

**Comment by nilsteampassnet** [comment] 2017-09-24 20:08
Sorry I don't understand everything you wrote, except that you are bored.
I can understand, no problem.
But if you want help or help me as you wrote, I need concrete data t o be able to reproduce.
I don't understand your point with restore ... you cannot restore a database that has been created with on old version of teampass inside a new one. The structure of database has changed.
So the result will be corrupted data for sure.

**Comment by free-14** [comment] 2017-09-24 20:30
https://github.com/nilsteampassnet/TeamPass/issues/1842  
In this topic, we asked you to remove an arbitrary symbol. And make the input of the personal key on the ENTER key. But you just removed the symbol. And did not even indicate where and how to do FIX ... Why is it so?

**Comment by free-14** [comment] 2017-09-24 20:33
[russian.zip](https://github.com/nilsteampassnet/TeamPass/files/1327725/russian.zip)
Do not mock the Russian language. Water to you a normal translation.

**Comment by nilsteampassnet** [comment] 2017-09-25 17:11
Concerning #1842, what is the problem? the issue is fixed. What do you expect from me?
There was an issue, I have fixed and committed the fix.
Now the fix is released in new version, so I don't see your point.

Concerning language, you are welcome to participate to translation from [PoEditor](https://poeditor.com/projects/view?id=16418).
The files are extracted from PoEditor.com and included in languages.

**Comment by free-14** [comment] 2017-09-26 18:54
I'm very glad that you fixed it. You do not understand the question. I asked to enter the password by pressing ENTER. You understand?

**Comment by free-14** [comment] 2017-10-05 19:31
The question is solved you can close the topic. It was necessary to go into your personal profile and change the password of personal salt to the same or new.

**Comment by free-14** [comment] 2017-10-05 20:56
There is no solution... After changing personal salt, it stops seeing passwords. ((

**Comment by free-14** [comment] 2017-10-29 20:37
You will help to solve this question? or have you already forgotten?

**Comment by free-14** [comment] 2017-10-29 20:40
You tell me which way to dig, I'll try to solve it myself. ))

**Comment by nilsteampassnet** [comment] 2017-10-30 05:41
I have found an issue in the upgrade script that forced the value of the field related to this in the user accounts to 1. I have fixed this so that now it is not the case.
In the table users, the field `upgrade_needed` is used. If value is `1` then this dialogbox is shown to ask the user to proceed. Once proceeded, the field value for the user is passed to `0`.
Can you check that when you proceed the value is set to `0`.
If not, then there must be an error in the log. Please provide it.

**Comment by free-14** [comment] 2017-10-30 18:17
You are right, it does not change this value in mysql. I'll send you an error right now.

**Comment by free-14** [comment] 2017-10-30 18:24
[:error] [pid 7884] [client 192.168.1.1:64540] PHP Notice:  Undefined index: bad_psk in /var/www/html/www/load.php on line 237, referer: https://www/index.php
[:error] [pid 7884] [client 192.168.1.1:64540] PHP Notice:  Undefined index: bad_psk_confirmation in /var/www/html/www/load.php on line 240, referer: https://www/index.php
[:error] [pid 7884] [client 192.168.1.1:64540] PHP Notice:  Undefined index: psk_required in /var/www/html/www/load.php on line 243, referer: https://www/index.php
[:error] [pid 7884] [client 192.168.1.1:64540] PHP Notice:  Undefined index: setting_disabled_by_admin in /var/www/html/www/load.php on line 346, referer: https://www/index.php

**Comment by nilsteampassnet** [comment] 2017-10-30 19:14
can you run this sql query

`SELECT * FROM `teampass_log_system` WHERE type = 'error'`

THis will permit to list mysql errors

**Comment by free-14** [comment] 2017-10-30 19:33
![error](https://user-images.githubusercontent.com/28634449/32191472-497258aa-bdc2-11e7-8545-35a378838496.jpg)

**Comment by nilsteampassnet** [comment] 2017-10-30 19:53
Can you run  `SELECT * FROM `teampass_log_system` WHERE type="error" order by date DESC`
and export the results as sql

**Comment by free-14** [comment] 2017-10-30 20:01
Say your mail.

**Comment by free-14** [comment] 2017-10-30 20:58
The problem was solved. I just deleted these errors. There were requests for non-existent items.

**Comment by nilsteampassnet** [comment] 2017-10-31 04:37
OK

**Closed by nilsteampassnet** 2017-10-31 04:37 UTC
