### ISSUE TITLE
OpenLDAP users can't login after update from 2.1.27.1 to 2.1.27.7

### ISSUE THREAD

**Issue by joaolm** [nilsteampassnet/TeamPass#1825] opened 2017-07-25 19:16 UTC
### Steps to reproduce
1. Update TeamPass from version 2.1.27.1 to 2.1.27.7 
2. Try to login with an OpenLDAP user

LDAP Conf:
![ldap-2 1 27 1](https://user-images.githubusercontent.com/26491547/28589341-061f1576-7154-11e7-8a48-e494c3d2a9be.jpg)

### Expected behaviour
Access TeamPass.

### Actual behaviour
OpenLDAP users can't login after update
Error: Login credentials do not correspond!

### Server configuration
**Operating system**:
CentOS 6
**Web server:**
Apache 2.2.15-60
**Database:**
MySQL 5.7.17
**PHP version:**
PHP 5.6.30
**Teampass version:** 
2.1.27.7
**Updated from an older Teampass or fresh install:**
Update from 2.1.27.1
** LDAP**
OpenLDAP LTB: 2.4.40-1
### Client configuration
**Browser:**
All
**Operating system:**
All
#### OpenLDAP log
Jul 25 16:11:03 server01 slapd[1345]: conn=4872 fd=21 ACCEPT from IP=127.0.0.1:38734 (IP=0.0.0.0:636)
Jul 25 16:11:03 server01 slapd[1345]: conn=4872 fd=21 TLS established tls_ssf=128 ssf=128
Jul 25 16:11:03 server01 slapd[1345]: conn=4872 op=0 BIND dn="cn=admin,dc=company,dc=local" method=128
Jul 25 16:11:03 server01 slapd[1345]: conn=4872 op=0 BIND dn="cn=admin,dc=company,dc=local" mech=SIMPLE ssf=0
Jul 25 16:11:03 server01 slapd[1345]: conn=4872 op=0 RESULT tag=97 err=0 text=
Jul 25 16:11:03 server01 slapd[1345]: conn=4872 op=1 SRCH base="ou=users,dc=company,dc=local" scope=2 deref=0 filter="(&(uid=joao)(objectClass=person))"
Jul 25 16:11:03 server01 slapd[1345]: conn=4872 op=1 SRCH attr=dn mail givenname sn
Jul 25 16:11:03 server01 slapd[1345]: conn=4872 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
Jul 25 16:11:05 server01 slapd[1345]: conn=4872 op=2 UNBIND
Jul 25 16:11:05 server01 slapd[1345]: conn=4872 fd=21 closed

#### Web server error log
```
There is no error in /var/log/httpd/error_log
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Bronken link of How to... but i found out how to take the firebug log... 

http://192.168.92.1/teampass/sources/identify.php 200 OK  2,38s
[{"value" : "false", "user_admin":"", "initial_url" : "", "error" : "", "pwd_attempts" : "1"}]

```

**Comment by nilsteampassnet** [comment] 2017-07-26 11:06
Can someone with LDAP and 2.1.27.7 confirm the issue?

**Comment by nilsteampassnet** [comment] 2017-07-29 05:50
Are the certificates correctly installed on the server?

**Comment by nilsteampassnet** [comment] 2017-07-29 06:27
Certainly duplicate of #1805

**Comment by joaolm** [comment] 2017-08-01 19:34
Hello, I've enabled log (debugLdap) in the file "sources / identify.php" and the connection to LDAP is done without problems ....
Apparently TeamPass is not being able to handle the return ...

Follows the OpenLDAP and LDAP connection log...
`
tail -f /var/log/openldap.log /var/www/html/teampass/files/ldap.debug.txt 
Get all LDAP params : 
mode : 1
type : posix-search
base_dn : dc=company,dc=local
search_base : ou=users,dc=company,dc=local
bind_dn : cn=admin,dc=company,dc=local
bind_passwd : XXXXXXXXXXXXX
user_attribute : uid
account_suffix : ou=users,dc=company,dc=local
domain_controllers : rede01.djsystem.local
port : 636
use_ssl : 1
use_tls : 0
*********

LDAP URIs : ldaps://rede01.djsystem.local:636 
LDAP connection : Connected

==> /var/log/openldap.log <==
Aug  1 16:07:03 rede01 slapd[1305]: conn=1849 fd=25 ACCEPT from IP=127.0.0.1:49339 (IP=0.0.0.0:636)
Aug  1 16:07:03 rede01 slapd[1305]: conn=1849 fd=25 TLS established tls_ssf=128 ssf=128
Aug  1 16:07:03 rede01 slapd[1305]: conn=1849 op=0 BIND dn="cn=admin,dc=company,dc=local" method=128
Aug  1 16:07:03 rede01 slapd[1305]: conn=1849 op=0 BIND dn="cn=admin,dc=company,dc=local" mech=SIMPLE ssf=0
Aug  1 16:07:03 rede01 slapd[1305]: conn=1849 op=0 RESULT tag=97 err=0 text=

==> ldap.debug.txt <==
LDAP bind : Bound

==> /var/log/openldap.log <==
Aug  1 16:07:03 rede01 slapd[1305]: conn=1849 op=1 SRCH base="ou=users,dc=company,dc=local" scope=2 deref=0 filter="(&(uid=joao)(objectClass=person))"
Aug  1 16:07:03 rede01 slapd[1305]: conn=1849 op=1 SRCH attr=dn mail givenname sn
Aug  1 16:07:03 rede01 slapd[1305]: conn=1849 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=

==> ldap.debug.txt <==
Search filter : (&(uid=joao)(objectClass=person))
Results : Array
(
    [count] => 1
    [0] => Array
        (
            [sn] => Array
                (
                    [count] => 1
                    [0] => XXXXXXXXX
                )

            [0] => sn
            [mail] => Array
                (
                    [count] => 1
                    [0] => joao@XXXXXXXX.XXX.XX
                )

            [1] => mail
            [givenname] => Array
                (
                    [count] => 1
                    [0] => Joao Luis
                )

            [2] => givenname
            [count] => 3
            [dn] => uid=joao,ou=users,dc=company,dc=local
        )

)

==> /var/log/openldap.log <==
Aug  1 16:07:06 rede01 slapd[1305]: conn=1849 op=2 UNBIND
Aug  1 16:07:06 rede01 slapd[1305]: conn=1849 fd=25 closed
`

**Comment by nilsteampassnet** [comment] 2017-08-01 19:56
Can you provide file /includes/config/tp.config.php please to see the ldap definition you have?

**Comment by nilsteampassnet** [comment] 2017-08-01 20:01
Can you please provide /includes/config/tp.config.php file to check you LDAP settings?

Thank you

**Comment by nilsteampassnet** [comment] 2017-08-01 20:04
Can you please try something to debug this?

Open file `/includes/identify.php`
Replace
```
                    if ($ldapConnection && ldap_count_entries($ldapconn, $result)) {
```
by
```
                    if (ldap_count_entries($ldapconn, $result)) {
```

**Comment by joaolm** [comment] 2017-08-02 10:42
Hi, it worked with replace.
Follows the connection log and /includes/config/tp.config.php

Is this replace enough? Or will you do anything else?

[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1193516/tp.config.php.txt)
[connection-log-20170802-0725.txt](https://github.com/nilsteampassnet/TeamPass/files/1193518/connection-log-20170802-0725.txt)

**Comment by nilsteampassnet** [comment] 2017-08-02 16:58
Happy to read this.

No the replace is the main modification.
I've just committed some general fixes but this change is the "logical" part. In your configuration, your user could never be authenticated.

SO I believe this issue is fixed.

**Comment by seidler2547** [comment] 2017-12-07 11:26
`ldap_count_entries` should always be checked with `> 0`, especially in lines 434 and 449 of `identify.php`. Otherwise it can end up in a situation where anybody can log in with any random password.

**Comment by nilsteampassnet** [comment] 2017-12-07 19:57
@seidler2547, correct.
A fix was committed in `development` branch.

**Closed by nilsteampassnet** 2017-12-07 19:57 UTC
Labels: 2.1.27, Answered, bug, Duplicate
