### ISSUE TITLE
Manage Users Empty

### ISSUE THREAD

**Issue by errano** [nilsteampassnet/TeamPass#2257] opened 2018-05-08 22:52 UTC
### Steps to reproduce
1. install teampass
2. log in as admin
3. go to manage  users 

### Expected behaviour
Users should appear

### Actual behaviour
just header, menu and background image

### Server configuration
Linux

**Web server:**
Apache2
**Database:**
Mysql 5
**PHP version:**
5.5
**Teampass version:** 
2.1.27.12
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
fresh install 

### Client configuration
any

**Operating system:**
any
#### Web server error log
mod_fcgid: stderr: PHP Catchable fatal error:  Argument 1 passed to cleanText() must be an instance of string, string given, called in /var/www/xxxx/html/xxxx/teampass/users.php on line 74 and defined in _/var/www/xxxx/html/xxxx/teampass/sources/main.functions.php_ on line 2230
#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by errano** [comment] 2018-05-08 22:53
![2](https://user-images.githubusercontent.com/35180024/39786988-a112210e-5312-11e8-9d70-a9e408489afa.PNG)

**Comment by nilsteampassnet** [comment] 2018-05-09 05:40
Duplicate of #2243.

Please follow instruction

**Closed by nilsteampassnet** 2018-05-09 05:40 UTC
Labels: Duplicate
