### ISSUE TITLE
Preparing database failing with error `At least one task has failed` on fresh install

### ISSUE THREAD

**Issue by Kyogre** [nilsteampassnet/TeamPass#3542] opened 2023-02-21 13:20 UTC
### Steps to reproduce
1. start fresh install version [3.0.0.23](https://github.com/nilsteampassnet/TeamPass/commit/bc7a0cbea7210205f3d237db31090258cc836b01) or 3.0.0.22
2. on the page http://10.81.3.139/install/install.php fill the fields:
```
---Absolute path to TeamPass folder
/var/www/teampass

---Full URL to TeamPass 
http://10.81.3.139


---Database connection Information
localhost
teampass
teampass
teampass123
3306

---Table prefix 
teampass_
---admin password:
teampass123
```
3. proceed to step "Preparing database", press Start

### Expected behaviour

Step finishes successfully as if installing version 3.0.0.21.

### Actual behaviour

At step `Preparing database` I get `At least one task has failed! Please correct and relaunch` error and no clue what is wrong.

<details>
  <summary>Preparing database operation shows this</summary>
  
  ```
    Table automatic_del created
    Table cache created
    Table cache_tree created
    Table categories created
    Table categories_folders created
    Table categories_items created
    Table defuse_passwords created
    Table emails created
    Table files created
    Table items created
    Table items_change created
    Table items_edition created
    Table kb created
    Table kb_categories created
    Table kb_items created
    Table languages created
    Table log_items created
    Table log_system created
    Table misc created
    Table nested_tree created
    Table notification created
    Table processes created
    Table processes_tasks created
    Table otv created
    Table sharekeys_fields created
    Table sharekeys_files created
    Table sharekeys_suggestions created
    Table restriction_to_roles created
    Table rights created
    Table roles_title created
    Table roles_values created
    Table suggestion created
    Table tags created
    Table templates created
    Table tokens created
    Table users created
  ```
  
</details>

### Server configuration
**Operating system**: Red OS 7.3.2 (Red Hat 8.3.1 like)

**Web server:** Apache 2.4.5.4-1.el7.3

**Database:** MariaDB 10.10.2-2.el7 (5.5.5-10.10.2-MariaDB) + mysqlnd 7.4.33

**PHP version:** 7.4.33-1.el7

**Teampass version:** 3.0.0.22 / 3.0.0.23

**Updated from an older Teampass or fresh install:** fresh install

#### Web server error log
\-

#### Log from the web-browser developer console (CTRL + SHIFT + i)

```
XHR POST http://10.81.3.139/install/install.queries.php
[HTTP/1.1 200 OK 448ms]

16:06:49.475

--- RECEPTION---
[object Object]
-------
install.js:282:17
16:06:49.476 RETOUR: install.js:289:21
16:06:49.476
Array [ {…} ]
​
0: Object { index: "40", multiple: "true", task: "users", … }
​​
activity: "table"
​​
error: ""
​​
index: "40"
​​
multiple: "true"
​​
task: "users"
```
Full log: [Preparing database browser console log.txt](https://github.com/nilsteampassnet/TeamPass/files/10793851/Preparing.database.browser.console.log.txt)

**Comment by nilsteampassnet** [comment] 2023-02-23 05:49
Latest commit shall fix this issue.
Duplicate of #3534

**Comment by nilsteampassnet** [comment] 2023-02-23 05:49
A fix has been committed.
Please reopen if needed.

**Closed by nilsteampassnet** 2023-02-23 05:49 UTC
