### ISSUE TITLE
Fresh install on Debian Stretch not working

### ISSUE THREAD

**Issue by ckatterl** [nilsteampassnet/TeamPass#1966] opened 2017-10-12 12:32 UTC
### Steps to reproduce
1. Install from source on Debian 9 (Apache 2.4, php 7)
2.
3.

### Expected behaviour
Installer works normally, first login and/or start-page should be shown for further configuration.

### Actual behaviour
After successful installation by installer, start-page is not shown. Instead strange characters like the following are shown:

PVnfWVtbW1vLcgzIwTwO5ITuPOlXDub2Kn7Gf3rJs6vUbkKTL43LkKbhwNkPPEDbPA5s5vx71Q+drAShwL8+Ady/MXrgyMoOw/987MaebA/jB7FV0JqUdcbJuW5rt2cr2TI+ESI=

On page-reload, another string like the above is generated and shown.
Install-Folder is not getting deleted too.

### Server configuration
Debian 9 (Stretch), 64bit

**Web server:**
Apache 2.4.25-3

**Database:**
MariaDB 10.1.26

**PHP version:**
PHP 7.0.19

**Teampass version:** 
2.1.27

**Teampass configuration file:**

<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/teampass/teampass',
    'cpassman_url' => 'https://pass.katterl.eu',
    'favicon' => 'https://pass.katterl.eu/favicon.ico',
    'path_to_upload_folder' => '/var/www/teampass/teampass/upload',
    'url_to_upload_folder' => 'https://pass.katterl.eu/upload',
    'path_to_files_folder' => '/var/www/teampass/teampass/files',
    'url_to_files_folder' => 'https://pass.katterl.eu/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '1',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1505218553',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/teampass/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC'
);

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

Not updated, fresh install

### Client configuration
**Browser:**
Latest Mozilla version

**Operating system:**
Ubuntu 17.03, and/or Debian 9

#### Web server error log
```
The only error shown (but regularly):
[Thu Oct 12 14:16:57.526947 2017] [:error] [pid 32141] [client 80.120.10.242:53065] PHP Notice:  Undefined index: key in /var/www/teampass/teampass/sources/main.functions.php on line 1306

Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment] 2017-10-12 13:16
Please reinstall with new 2.1.27.9 package.

Duplicate of #1961

**Closed** 2017-10-12 19:27 UTC
