### ISSUE TITLE
Announce this Item by email

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#1417] opened 2016-08-07 17:11 UTC
### Teampass version:
2.1.26.15 updated from 2.1.26.13
### Operating system (Linux / Windows):
Ubuntu 14.04.4 LTS
### Apache version:
Apache/2.4.7 (Ubuntu)
### MariaDB version:
Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3
### PHP version:
PHP 5.5.9-1ubuntu4.16 (cli) (built: Apr 20 2016 14:31:27)
### Browser and version
Mozilla Firefox
### Actual behavior
Using 2.1.26.15 version and below when creating new password and try to announce it by e-mail I do not receive any e-mail. 

FireBug receive errors when creating new item and announce:
(*)TypeError: handleObj.handler.apply is not a function http://******/includes/js/jquery-ui/external/jquery/jquery.js Line 5094
(*)TypeError: $(...).data(...) is undefined http://********/index.php?page=items Line 4784
![error](https://cloud.githubusercontent.com/assets/4628571/17463918/16d5a788-5cdb-11e6-953c-3253dbeb92ff.png)

**Comment by nilsteampassnet** [comment] 2016-08-30 18:28
Tried with last development commit, and could not reproduce.

The user has an email defined?
Can you send emails using "test email" feature in admin settings?

**Comment by reginfo** [comment] 2016-09-02 07:02
Sorry for long delay, Work exams. 
So from Admin (deniss@     .lv) I sent "Test Email Configuration"
![teampass](https://cloud.githubusercontent.com/assets/4628571/18195158/c05e17ec-70f2-11e6-8d62-77b0335a43df.PNG)
and it is successfull. 
![teampass2](https://cloud.githubusercontent.com/assets/4628571/18195249/f9abfb54-70f2-11e6-80b8-c5dffbb9e17f.png)

All users have an e-mail adresses defined. 

How I simulate:
 Login using my AD credentials as deniss. I`m having the same email adress as an administrator (denis@    .lv). 
Creating new Item, fill out all necessery info and trying to announce it, but nothing. I didn`t receive any message. 
But if I will first save it and after that open it and try to announce it again - It is OK. I receive an update statuss of this item. 

If it will be prefered for you I can try to arrange Remote Session!

**Comment by reginfo** [comment] 2016-09-02 08:32
I will try to upload video and provide a link to it.

**Comment by reginfo** [comment] 2016-09-02 09:28
Link to video located on Youtube. 
https://youtu.be/1TrZahvg2GM

**Comment by reginfo** [comment] 2016-09-02 13:33
tried on 2.1.26.17, also no luck!

**Comment by nilsteampassnet** [comment] 2016-09-11 19:13
Found a fix for this.

**Closed by nilsteampassnet** 2016-09-11 19:13 UTC
Labels: bug
