### ISSUE TITLE
Unable to delete and re-create user 

### ISSUE THREAD

**Issue by whosht** [nilsteampassnet/TeamPass#3827] opened 2023-08-14 14:03 UTC
### Steps to reproduce
1. Login as admin
2. Select "Users"
3. Select drop-down of user to delete
4. Select "Delete"

### Expected behaviour
User is removed from list and can be newly created using e.g. LDAP-Sync

### Actual behaviour
User is still listed.
LDAP-User can't be re-created.

### Additional Information
User is still in "user" table but with field "delete_at" set.
Looks like 88f7986aedf88b3bd612263cb0ce38a3bb55dd10 introduced not deleting the user to improve logging but misses everything else needed to handle the state of the user as deleted and being able to re-create that user on a fresh basis.
We synchronize against LDAP and as the user is still listed we are unable re-create the user.

### Server configuration
**Operating system**: Debian 11

**Web server:** Apache

**Database:** mariadb

**PHP version:** 7.4.33

**Teampass version:** 3d6e454dccd65813d37dae1bcb2a7cf0d496383c (3.0.9 with one fix of 3.0.10)

**Comment by nilsteampassnet** [comment] 2023-08-16 13:36
Is  aduplicate of #3784 which is closed.
Please update using latest commit

**Closed** 2023-08-20 14:31 UTC
