### ISSUE TITLE
 Admin Folders management did not list all folder

### ISSUE THREAD

**Issue by waldo2188** [nilsteampassnet/TeamPass#1510] opened 2016-09-20 09:23 UTC
I'm log as admin (the original admin of teampass).
In the admin "Folder management" I haven't all the folders, only the level 2 folders.
When I'm log as a simple user, I see all the folder tree, so, no problem for casual user.

In my research I've found that the tree list is filter with the data in `$_SESSION['groupes_visibles']`.
See `/sources/datatable/datatable.folders.php` at line 60.

```php
 if (in_array($t->id, $_SESSION['groupes_visibles']) && !in_array($t->id, $_SESSION['personal_visible_groups']) && $t->personal_folder == 0) {
        //...
```

I made a var_dump of `$_SESSION['groupes_visibles']` in `/sources/datatable/datatable.folders.php` and the ids list in this variable contains the actual folder list in "Folder management" (the level 2 folders).
I don't know where this variable is set, but lacks the ids of the parent folders.

## Steps to reproduce

I don't know how you can reproduce this behaviour

## Expected behaviour
The  "Folder management" page and the "Roles management" page must list all the foldres tree for the admin user.

## Actual behaviour
The  "Folder management" page and the "Roles management" page only list the level 2 folders.

## Server configuration

Debian : 8
Apache : 2.4.10
MySql : Ver 14.14 Distrib 5.5.52
PHP  5.6.24-0+deb8u1

Teampass :  2.1.26

## Client configuration
Google Chrome:
Windows 10:

**Comment by waldo2188** [comment] 2016-09-20 13:58
I've maybe the beginning of an answer.

I have use a "Specific Actions" -> "Actualize Personal Folders for all users (creates them if not existing)".
And in the database, all the folder with the level 1 was set to personal (nested_tree.personal_folder =1).

Maybe is there a bug in the "Actualize Personal Folders for all users (creates them if not existing)" action ?

**Comment by nilsteampassnet** [comment] 2016-09-20 17:26
I don't really understand.
Can you make some screenshots?

What pre-release version do you use? There has been a fix for a maybe similar issue in 2.1.26.18.
Perhaps can you update to last one (19) to check if it solves your issue.

Note that Admin will never see Personal Folders.

**Comment by waldo2188** [comment] 2016-09-21 07:35
I try to reproduce this issue, but I can't, my apology for that.
So, I made some screenshot to explain it.

I use the master branch of the repository (maybe not a good idea...).

In this picture you can see that a lambda user can see all the tree.
![teampass2](https://cloud.githubusercontent.com/assets/841872/18701641/01bfdc1c-7fde-11e6-9f5c-aaf074b601c5.jpg)

But in this picture, the admin user can't see all the tree. Only the level 2 node folder.
![teampass1](https://cloud.githubusercontent.com/assets/841872/18701634/f9031fee-7fdd-11e6-848e-fe0bb3d65dc7.jpg)

I don't know how, but in the database `nested_tree.personal_folder` was set to `1` for all level 1 tree node.

**Comment by qubez** [comment] 2016-09-21 13:46
The cause was recognized and fixed in https://github.com/nilsteampassnet/TeamPass/issues/1476 - however the solution is to manually edit the database and change the "personal folder" property on all named folders back to "0".

With this second report, perhaps it would be wise to include a function in the upgrade.php script to repair this database error.

**Comment by nilsteampassnet** [comment] 2016-09-21 20:05
I've provided a commit to clean up during upgrade.

Nevertheless the script will only "clean" in case of non-numeric folders.
Indeed only numeric title may be a User one, and too much cases could occur.

**Closed** 2016-09-21 20:05 UTC
Labels: bug
