### ISSUE TITLE
Backslash not properly handled by teampass edit form

### ISSUE THREAD

**Issue by finalbeta** [nilsteampassnet/TeamPass#2297] opened 2018-06-11 08:56 UTC
### Steps to reproduce
1. Create a credential in Teampass with label "test", and some password, but use the following username (without quotes): "system\testuser"
2. Save the credential
3. The credentials is saved OK. 
4. Edit the same credential and check the username field. You are missing the \
5. save the credential = the username is corrupted. 

This only happens on the username field, not in the label or description.

### Expected behaviour
The editor should show "system\testuser"

### Actual behaviour
The editor shows "systemtestuser" (Backslash is lost on edit)

### Server configuration
**Operating system**: Debian 7

**Web server:** Apache

**Database:** MySQL 

**PHP version:** 7.0

**Teampass version:** 2.1.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

I'm not including logs at this time, but if you are unable to reproduce, I will test further on my side/provide any information you need.

**Comment by nilsteampassnet** [comment] 2018-06-11 10:47
This is a duplicate of #2161
Issue solved in latest

**Closed by nilsteampassnet** 2018-06-11 10:47 UTC
Labels: Duplicate

**Comment by finalbeta** [comment] 2018-07-12 13:17
Hi Nils, 

I'm still having this issue when the item it created through the API. 
I create the credential through the API using backslashes inside it. 
It looks normal in the frontend. But when I edit it, the backslashes are gone. 

(So this is fixed when the item was not created through the API)
