### ISSUE TITLE
Update from 2.1.27.36 -> 3.0.0.9 (LDAP in Use)

### ISSUE THREAD

**Issue by mazeugs** [nilsteampassnet/TeamPass#3007] opened 2022-01-19 15:50 UTC
Hi,
I tried to update our teampass solution.
There was no problem with the update. I got the login screen after the update. 
I tried to login but this is not working. 
LDAP user - login failed
Local user - keep on the login page with the rotating icon, HTML 501 error.

Apache Log.
[Wed Jan 19 08:56:29.544430 2022] [php7:error] [pid 5354] [client 192.168.168.36:62216] PHP Fatal error:  Uncaught TypeError: base64_encode() expects parameter 1 to be string, bool given in /var/www/html/teampass/sources/main.functions.php:2435\nStack trace:\n#0 /var/www/html/teampass/sources/main.functions.php(2435): base64_encode()\n#1 /var/www/html/teampass/sources/identify.php(654): decryptPrivateKey()\n#2 /var/www/html/teampass/sources/identify.php(218): identifyUser()\n#3 {main}\n  thrown in /var/www/html/teampass/sources/main.functions.php on line 2435, referer: http://teampass-test.grassfish.tv/teampass/

Do you have an advice for me to handle the problem.

**Comment by jrubenc** [comment] 2022-01-24 16:03
https://github.com/nilsteampassnet/TeamPass/issues/2998

**Comment by nilsteampassnet** [comment] 2022-01-25 05:39
Duplicate of #2998 
If not please reopen

**Closed by nilsteampassnet** 2022-01-25 05:39 UTC
Labels: bug, Duplicate
