### ISSUE TITLE
Upgrade from 2.1.27.8 to 2.1.27.9

### ISSUE THREAD

**Issue by asgomes** [nilsteampassnet/TeamPass#1968] opened 2017-10-12 14:07 UTC
### Steps to reproduce
1.Upgrading to 2.1.27.9
2. Step 4 (running scripts)
3. ERROR: Previous Saltkey not in database.

### Expected behaviour
It should run like every other script previously ran.

### Actual behaviour
next to sucessfully ran - upgrade_run_2.1.27.php - Loop #1
- upgrade_run_defuse_for_pwds.php - Loop #1 - stops with error (ERROR : Previous Saltkey not in database.)

SELECT valeur FROM *****_misc WHERE type='admin' AND intitule = 'saltkey_ante_2127';
runs successfully in the database, and its not empty.

### Server configuration
**Operating system**:
Linux 7
**Web server:**
apache
**Database:**
mariadb
**PHP version:**
php 7
**Teampass version:** 
2.1.27.8
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
as Nothing
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by newburns** [comment] 2017-10-12 14:28
Same as #1967

**Comment by nilsteampassnet** [comment] 2017-10-12 19:26
Thank you for sharing the information that the value exists in the DB.
This eases a lot the cause of the bug you are facing.

Nevertheless I don't understand why you enter in the condition that leads to this error if the value exists in the database ... this is surprising!

As I cannot reproduce, can you please make the next test for me.

* Open file `install/upgrade_run_defuse_for_pwds.php`
* Replace
```
if (isset($db_sk['valeur']) && empty($db_sk['valeur']) === false) {
    $old_saltkey = $db_sk['valeur'];
} else {
    echo '[{"finish":"1" , "error":"Previous Saltkey not in database."}]';
    exit();
}
```
by
```
if (count($db_sk['valeur']) === 0 || empty($db_sk['valeur']) === true) {
    echo '[{"finish":"1" , "error":"Previous Saltkey not in database."}]';
    exit();
} else {
    $old_saltkey = $db_sk['valeur'];
}
```

**Comment by asgomes** [comment] 2017-10-13 10:52
Hi Nils,

It just gave me the same error.

- ERROR: Previous Saltkey not in database.

Is there any other information I can give you?
I don't say the settings.php cause the other scripts gone well.

Do you think the tp.config.php can help in this situation?

**Comment by nilsteampassnet** [comment] 2017-10-13 11:18
You confirm that when running this query:
SELECT valeur FROM teampass_misc WHERE type='admin' AND intitule = 'saltkey_ante_2127';

the answer is not null?

**Comment by asgomes** [comment] 2017-10-13 11:21
Yes, I confirm.
![image](https://user-images.githubusercontent.com/1770475/31544063-05e94df0-b011-11e7-9811-cdf2806fe161.png)

**Comment by nilsteampassnet** [comment] 2017-10-13 11:23
Then I don't understand how this can be wrong : if (count($db_sk['valeur']) === 0 || empty($db_sk['valeur']) === true) {

**Comment by nilsteampassnet** [comment] 2017-10-13 11:24
I've run this hundred times on m test server without any failure
I don't see what is wrong.

Let's investigate more

**Comment by asgomes** [comment] 2017-10-13 11:26
How can we debug this? 

How can we debug the values for the conditions and comparisons?
any echos I can made? 
I'm not an php expert...far from it, I tried to echo some variables in the "ERROR.." statement in the php file, without success.

**Comment by asgomes** [comment] 2017-10-13 11:35
Just tell me if you need remote access or something.
I've cloned this instance from production, and I've managed to upgrade it from 1.2.27.7 to 1.2.27.8.
Successfully, then I got this issue.

I've managed to copy settings.php tp.config.php,copied overwrited the upload files and copied sk.php and team-seckey.txt.
Tell me if u want/need remote access to my VM.

**Comment by nilsteampassnet** [comment] 2017-10-17 05:11
Are you using a VM?

On another user teampass instance that has the same issue, I could identify the reason but still don't understand why it occurs as I cannot reproduce on my own test environment.

The issue takes its origin in the fact that the used session variables are not propagated in the files used during the upgrade. Which leads to this error.

Until now I could not find the solution. I'm convinced it comes from the server configuration.

So it's still under investigation

**Comment by asgomes** [comment] 2017-10-17 09:27
hi Niels,

We're using a VM, well I can say that the configuration for the database changed because I've cloned our Production instance.
Though, I've done the 2.1.27.7 upgrade to 2.1.27.8 before this one, and the other scripts run fine without any problems.

anything I can provide to help?

**Comment by nilsteampassnet** [comment] 2017-10-18 16:24
I've committed today a fix for this issue.
In a qualification environment, can you overwrite the files with the content of the "development package" and run the upgrade protocol.

**Comment by nilsteampassnet** [comment] 2017-10-19 19:03
Any news?

**Comment by asgomes** [comment] 2017-10-20 10:46
sory, I can only test this on monday :\ i'll give u the feedback as soon as possible

**Comment by asgomes** [comment] 2017-10-20 16:31
hi got an opening, I've moved the files from "TeamPass-development.zip" and ran the upgrade, and it failed exactly in the same spot with the same error:
![image](https://user-images.githubusercontent.com/1770475/31831737-6c32cca2-b5bc-11e7-914e-db32c77214b4.png)

**Comment by nilsteampassnet** [comment] 2017-10-24 04:44
Could I access to your environment as I don't understand why you could have this regarding the changes I have done. (email: nils@teampass.net)

**Comment by asgomes** [comment] 2017-10-24 16:19
Sure nils, I've answered to your email and not here, tell me when you can connect.

**Comment by alchuk** [comment] 2018-03-11 22:05
I personally have never used TP before 2.1.27 (release). Today I met the same error while upgrading to 2.1.27.10. I noted that web-upgrade procedure asked me if I ever used releases prior to 2.1.27. I answered "No. 2.1.27 is the very version I started with".

What helped me is inserting new entry to make the previously said sql query return something but null.

`insert into teampass.teampass_misc (type, intitule, valeur) values ('admin', 'saltkey_ante_2127', 'HERE GOES THE SECRET KEY FROM /var/teampass/teampass-seckey.txt')`

Voila! The upgrade.php didn't even ask about 2.1.26 or older releases and finished without any further errors/warnings

**Comment by igorgoncharenko87** [comment] 2018-08-31 10:51
Hello! I have the same problem when start updating from 2.1.27.8 to 2.1.27.9 (upgrade_run_defuse_for_pwds.php - Loop #1 - stops with error (ERROR : Previous Saltkey not in database.). Do you have any ideas how to fix it? Thank's!

**Closed** 2022-10-31 04:48 UTC
Labels: Under investigation
