### ISSUE TITLE
'X-Frame-Option=SameOrigin' contains invalid character

### ISSUE THREAD

**Issue by blady214** [nilsteampassnet/TeamPass#1753] opened 2017-05-10 12:05 UTC
### Steps to reproduce
1. Open TeamPass login page

### Expected behaviour
Displayed login page.

### Actual behaviour
I get 500 error when I am trying to open the login page.
### Server configuration
**Operating system**:
Ubuntu 16.04 Server
**Web server:**
Apache/2.4.18 (Ubuntu)

**Database:**
MySQL 5.7.18-0ubuntu0.16.04.1 - (Ubuntu)
**PHP version:**
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )

**Teampass version:** 
2.1.27.1

**Updated from an older Teampass or fresh install:**
Fresh installtion. TeamPass has been installed about two months ago and since yesterday everything works properly.

### Client configuration
**Browser:**
any
**Operating system:**
any

#### Web server error log
```
[Wed May 10 13:56:00.204307 2017] [http:error] [pid 66103] [client 192.168.0.125:52496] AH02429: Response header name 'X-Frame-Option=SameOrigin' contains invalid characters, aborting request

```

**Comment by nilsteampassnet** [comment] 2017-05-10 19:36
Duplicate of #1692

**Closed by nilsteampassnet** 2017-05-10 19:36 UTC
Labels: Duplicate
