### ISSUE TITLE
Keepass Import: Malformed UTF-8 data - Undefined index: Entry in import.queries.php line 591

### ISSUE THREAD

**Issue by bananatree23** [nilsteampassnet/TeamPass#3334] opened 2022-09-23 08:01 UTC
### Page on which it happened
https://<anonym_url>/index.php?page=import

### Steps to reproduce
1. Enable the import feature
2. Export a Keepass database to xml and upload it
3. Click on Perform

### Expected behaviour
Import of Keepass entries and folders

### Actual behaviour
No import of entries or folders

### Server configuration
**Operating system**: Linux <hostname> 5.4.17-2136.310.7.1.el8uek.x86_64 #2 SMP Wed Aug 17 15:14:08 PDT 2022 x86_64

**Web server:** Apache/2.4.37 (Oracle Linux) OpenSSL/1.1.1k

**Database:** 5.5.5-10.3.35-MariaDB

**PHP version:** 7.4.19

**Teampass version:** 3.0.0.19

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '1',
'log_connections' => '1',
'log_accessed' => '0',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '0',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/teampass',
'cpassman_url' => 'https://<anonym_url>
'favicon' => 'https://<anonym_url>/favicon.ico',
'path_to_upload_folder' => '/var/www/teampass/upload',
'path_to_files_folder' => '/var/www/teampass/files',
'url_to_files_folder' => 'https://<anonym_url>/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '3.0.0.19',
'ldap_mode' => '1',
'ldap_type' => 'ActiveDirectory',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => 'samaccountname',
'ldap_ssl' => '1',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'ldap_port' => '636',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'english',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1657703943',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '1',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '25',
'email_security' => 'none',
'email_server_url' => '',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '64',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '1',
'proxy_ip' => '<removed>'
'proxy_port' => '',
'upload_maxfilesize' => '64mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '0',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '30',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/teampass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '1',
'create_item_without_password' => '1',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Berlin',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '1',
'offline_key_level' => '60',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '1',
'secure_display_image' => '1',
'upload_zero_byte_file' => '1',
'upload_all_extensions_file' => '0',
'bck_script_passkey' => '<removed>'
'admin_2fa_required' => '0',
'password_overview_delay' => '4',
'copy_to_clipboard_small_icons' => '1',
'duo_akey' => '',
'duo_ikey' => '',
'duo_skey' => '',
'duo_host' => '',
'teampass_version' => '',
'roles_allowed_to_print_select' => '',
'clipboard_life_duration' => '15',
'mfa_for_roles' => '',
'tree_counters' => '0',
'settings_offline_mode' => '0',
'settings_tree_counters' => '0',
'enable_massive_move_delete' => '1',
'email_debug_level' => '0',
'ga_reset_by_user' => '',
'onthefly-backup-key' => '<removed>'
'onthefly-restore-key' => '<removed>'
'ldap_user_dn_attribute' => 'distinguishedname',
'ldap_dn_additional_user_dn' => 'ou=<anonym>,ou=<anonym>,ou=<anonym>,ou=<anonym>',
'ldap_user_object_filter' => '(&(memberOf:1.2.840.113556.1.4.1941:=cn=<anonym>,ou=<anonym>,ou=<anonym>,ou=<anonym>,ou=<anonym>,dc=<anonym>,dc=<anonym>)(!objectClass=group))',
'ldap_bdn' => 'dc=<anonym>,dc=<anonym>',
'ldap_hosts' => '<removed>'
'ldap_password' => '<removed>'
'ldap_username' => 'cn=<anonym>,cn=<anonym>,dc=<anonym>,dc=<anonym>',
'api_token_duration' => '60',
'enable_tasks_manager' => '0',
'task_maximum_run_time' => '300',
'tasks_manager_refreshing_period' => '20',
'maximum_number_of_items_to_treat' => '100',
'ldap_new_user_role' => '13',
'can_create_root_folder' => '1',

```

**Updated from an older Teampass or fresh install:** Updated from 3.0.0.17 or .18 I believe

### Client configuration

**Browser:** Chrome, Firefox, Edge

**Operating system:**  Windows 10 & 11

### Logs

Next error occurred
Error: Malformed UTF-8 data

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
import.queries.php

<br />
<b>Notice</b>:  Undefined index: Entry in <b>/var/www/teampass/sources/import.queries.php</b> on line <b>591</b><br />
eyJjaXBoZXJ0ZXh0IjoiR1RSbVFqMjFNUTRTUDlSdlhlQkVIQ1ZtYTVJbEZRNE9pOGdWeUk2dlhCXC80eVlXMXJEWW1BdEYzR3g2aFd3SndZMksrS3FFU3hMOW83RXVnNkNreEQ4anNyMEVBTzNoVXo3WXAyOXlTUDdPSFwvTjhwNGwrNmwzRGNzV2MrZUxVbFJEdkJcL2cyaXZ1MFgwOUJQK3hVdHh0bnZuZnhkZVV5Q0syMUZuMmNcL2YzNHVCWUlWcHoyQ0dDR0tNWUlReGFoZktKQjZnOFNEdTNmVnFCTnNvWXlQMTFPZ3lRb083QWQyRGU3XC9yNHlSckJzS3hmZ1RcL2pCOGJJZExmc0UxM3lHdXpaRE53VG13Q0hOb0lLdWlTUVNwV0NRUWM5QnlXUE0zdGJ5TnVMM0VtZG53V1FcL3d1ajloYjRsVG9jTzg0dUc4S0lKcTFReGxhQklWYWRhTG5ibXd1UWRpZ3VlRW83REZQR0Z3a2pRN0dUYnZKZUdOckdHRGU4TEUrelFjWExWWXRLVmZycnd2WFdEMldKa1FVK3FYMWFHNW5jMGVzR3BOcE9ucXUxQXdEVWppUGQ5UDA1Uzg1dTZ3emVnWnVzQnl4TE9UV0F4YWF1UWI5TWN3d05QXC9OK21hNW5EVFlyZ25jeWFVcUNoTE54WXlFUWU1a0Zndm9SSHpQeGQ5bVVrNnNFeUgwXC9YTHJyT3B2S2dqV0crWlR1QkpmczJwV1ZLbklKUTBkY0IrazBieThuVWc4dmFcL2IrUUM0MnRFUitaa0VpdHpxMm9ZT25taFo2ckc4ejNwd2lXc3IyaHJPNmw5WVd4YUljYzBmdkNKekZkQlRBSlVZUDVsYXpwNXBRUXRsWjJ4M1BsNGVzaFc1TWo2TkNQMDFwVXo2TEtYVm1HenVKcXUzMDFcL0tORzhUd1hoZys1Y1NFWkl1Sk4wbFNGT3hzTm9kaHpUVnMyYWNCNnhFQkVIclFCajBURmJyUmVzNTJrN0hRZmxLY3RzRExOTk02OVROVUV6K3ZCMGhYemk2cTgwY0hUeG1sM3pSUEpNamZBbFhJbjdUbUp3XC9WREx4cTdGK0phQktsS0w1bjA4UzYyejdXS0oyWXFRNXJraUFJRlNcLzFPQUlHR2dtWGc5K2VHeVJJTEtlOUVlWERUcTgrVUlQRWRPNEFYRlhFNFVMYnB2eGFRaytzQ25GTCtMbytTM1lhSkJvakVjcUNkK0d4c05yMllLV1Rhak9VNDdqUjhOXC9kSnVIUG1kWXlZM1gxaWNFbGhJcWRvMVR1NnN2c09Kcnh4bGlPMU5pdUFsYUd3aFwvWElmXC8rRzJBcEl5dVwvT1IrN1FvR2RUaFFHTFwvMk9cL0hicWhzRDR1Y1hKcXF0Y1VBZmNrXC9WZjFBMEE1bVFqWUhkdGhid09YbTVHck9Mbk9BSmx3MEE0eU1rYzhzV1o0RmE5OW40eE51WXdyZmZRQnZyVERqTlB4dGdodCtObWR4QTRrME5FYUlYM1dQYm8yWFE3akZ3RElXd0RRUkdZZW9uVUlvV1VlMzJwXC9CMVg3aDc3WTdvakVwZmlFVEJScFwvb3plSVpOdFBtYThpMXNxdHZQOTVteVdoTHRCb2xjU1dadzF3QnpVRTM1OE9JSTd0RHV0anUyQk1hT0o2SVJHcndKbkF0bFwvWTluV1VnNTk5M1o0clV4WUl2bjRSNFo4OG9JSEdvaEIyRlFUSWp1RUVRTjA2NE8zUnlNRGk1OXRIVHdVZE1YeExIU0dwXC9OSDJVNXJcL0ZQd0xcL1ljZXBCYkh6RTdVR2JQOVpZMkN1c2FSMnhKYldSNjhhVkhSWWtXbkVVUDhWZ2M5NDBmeGN0eCtOSWdpU05KVVhvRVZFSWZsKzl4dzB4R2IwMXhrZmhCS2VPSTRrTWRuQTJNdU5jRXZWNEVtb3dZbkN6RHM5UFVsXC91SGNuajdIRkJidzM5dmdWVUczRFAwcmFmM0pKdmtna08xajI5dmg0bW5vS0lXa2pkWXZZSm5VbUFmaTR0QXhhNVA5aGcycGNQbkw0b3VNV2lJK0huV2NPbkhyQWxFMG94WWU0ayt3THRYWldNQjVEUXZYc3IxN1wvRVJpZzloYml6dFwvazkxaSt6WFBrYkhWcGlKRXFBdWl2OTB0dTI3bm5tOWlxajlTeU1rdFBhbmNManhKUUdtUTBRYmYzOVR4eDI3NXZTcWRLNkptc0EydEhxVW1Xc1M2UXQ5b3JPMllNUmEwTzlBT0xaUGxDeGl4Uk1cL2hHeDVHQklmY1pcLzE5QnB5MUhjMkRXcEVjSjZrZnRlOFwvYlBvXC9NSkpyYUZYVUVMTXpDU3dSK25SakNzVEVnc1wvVzNNUStaRFhrWURhNFlCZHlubEg4ZUhab2U4THBKajdWRWcxUzdzUlB4ZDR2MGtldVwvZThFQWphZWhLVlJLVDRvZit4bEtLZlBSQ1lHT0N2WFwvUnFjbFF1OEZiN3Q4OG9rK3c3K2U5VlNpclFvNTQ4YmV0SENmOUpXN0dtZGhNS2tJT0doZDdcLzUrN1laaWFFcFBGc3RoMXErbFFxQWVSOWE5bktBemZSdjhOeUs3anNlYkhOMis2eGMxbWtYSWVhckpaOE5FcVJBUHJLR0FCVDMzRmhRWmFxeVhsaUtBYklYVnZOVnJpZ0lpeW43SnZ5ajF1NlwvNHJtQVNaTzhqQldhS0JSRVZCUlR1cTJFd1IxQ3k5VXVKTFFPUHByRTQyakhOYnFNaXVqaCIsIml2IjoiYTNmYjA1ZDE5NzYwY2RiZjIxNTA5OTY4NjQ2MDcyYmQiLCJzYWx0IjoiY2Q0YWU2Yzk0YTliNGY1M2E5MGNhZWJhMjk2NGY0ZTJmODhkZTJlMWRkZTJlMzdjMGIyNTZhMjg0NWQxYWRjZjNhODZkMWQyNmEzMTI0NDNlOTE4ZjNjMWJmMmI4ZDE2NThjMDI3ZGYxNGVjY2RjMDVjYzJmMThjZTRiYmY0MzFiODcxMzNjMTIwZDY5MTkxMDQxOTNkOTQzNWZjZGQ5NGZkZWVlOGU1ZDI1MDUxMjVlOGI3ZGNkYWU2Y2RiYTU4YmU5NDEzMWZhN2FhMTU3NGZlYzE0NTcyMWRhMDUzNGUxMGQ4ZTgwODNiMGNhNGVjNDM2ZjI3YTdiZDdmODlmYmYwNTQ0NzgxNzc4NzVlZWM2YTJmMWZhZTU5OGQwNjE4YTM3OGQzMjJiZGFjMGRmMjc4NTcwNDRhYjQ3NjJlODNiZjdlYjU3YjA3MDM0NDMyOWQ3ZTVmNTg0YWFmMTg5ZDYxYjQ0YWE2MjhlZTBiNjAyNWFlMzE2NmFlODNmNDk1ZGZkYmRkODhmMTUzNzAzZTFhNDI2Y2ZiMDllZDExMjg4NDBjODk3YTNjNmI1ODI3MmIxYjkyNTU3MTYzYzI0YjBlODVlNDEyNjA3MWJhZWM0MzZmODVjNGQxMzVmZWQ2NDQxZmY1YjMzOTE5YjQ2OWQyYjBlOTI1YWNhOGQ4NzQiLCJpdGVyYXRpb25zIjo5OTl9
```

**Comment by nilsteampassnet** [comment] 2022-09-24 09:47
Hello
Sorry I cannot reproduce.
My Keepass file is created from 2.52 and contains hundreds of items organized into a structure of folders.
All the tests are successful.
I'm curious to get your xml file.

NOte: regarding CSV, it is by design, no folders as explain in documentation.

**Comment by TheBunnies** [comment] 2022-12-19 07:07
Hi. If you've encountered this error on "Folders" category and if it fails on lines 180, 190, 201, 202. You might want to check the table named **TeampassDatabase_nested_tree** and see if the **personal_folder** column corresponds to the correct values. After all of the shenanigans descripted above your issue should be fixed.

**Closed as completed** 2023-06-06 08:44 UTC
