### ISSUE TITLE
No AD Ldap Auth After 2.1.26.19 upgrade

### ISSUE THREAD

**Issue by drmanu33** [nilsteampassnet/TeamPass#1511] opened 2016-09-20 13:47 UTC
### Steps to reproduce
1. Upgrade to 2.1.26.19
2. Try Auth with AD Account
3. No Response / Infinite Loop
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead
### Server configuration

**Operating system**: Centos 6.8

**Web server:** Apache 2.2.x

**Database:** Mysql 5.1 (Tried with 5.6)

**PHP version:** 7.0.10

**Teampass version:** 2.1.26.19

**Updated from an older Teampass or fresh install:** Tried from fresh install and upgrade
### Client configuration

**Browser:** Firefox or Chrome

**Operating system:** Windows 7
#### Web server error log

```
Insert your webserver log here
```
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment] 2016-09-20 17:33
The LDAP library has been updated in pre-release (19).
No such impact was expected ... have you cleared up the cash of your browser? perhaps restart your web server to force the library to be reloaded?

Could you please share the errors displayed by Firebug (see how to)?

**Comment by drmanu33** [comment] 2016-09-21 06:42
I have cleared the cache, installed firebug, restarted apache.

You can find below the error displayed by firebug:

POST sources/identify.php
500 Internal Server Error
85ms	
HeadersPostResponse
Parametersapplication/x-www-form-urlencoded
data	xSriV87Ozs5fhY29HtSQsQXZ1ivq5Ah74DbobL1+yI+DYClpVxY+wuSSe/OkHM1iwmrdlTc/oNs1R3Tnh9gtY0pXsYnBqsT5FtxE6vltfYtR0liQ96V/HEYfVP4UyCru5/NBQxZZBWRY3nhNxGD9c1lA1z1WB1I3YB/ayGG2TBMfQybnpEN9QQz9e2EHQiC7nE5n3C4=
type	identify_user
Source
type=identify_user&data=xSriV87Ozs5fhY29HtSQsQXZ1ivq5Ah74DbobL1%2ByI%2BDYClpVxY%2BwuSSe%2FOkHM1iwmrdlTc%2FoNs1R3Tnh9gtY0pXsYnBqsT5FtxE6vltfYtR0liQ96V%2FHEYfVP4UyCru5%2FNBQxZZBWRY3nhNxGD9c1lA1z1WB1I3YB%2FayGG2TBMfQybnpEN9QQz9e2EHQiC7nE5n3C4%3D

**Comment by polcape** [comment] 2016-09-21 10:05
Same issue.

In the log I have

`PHP Fatal error:  Class 'LDAP\\adLDAP' not found in /teampass/sources/identify.php on line 297, referer: https://xxx/teampass/index.php?page=items`

**Comment by ImNtReal** [comment] 2016-09-21 16:41
Yep. I'm getting
`PHP Fatal error:  Class 'LDAP\\adLDAP\\adLDAP'`
I've tried disabling, and re-enabling LDAP options, but that didn't seem to help.

**Comment by reginfo** [comment] 2016-09-21 18:40
Try to read this #1486 
For now LDAP is working on Deployment. Waiting for new release when it will be in master.

**Comment by nilsteampassnet** [comment] 2016-09-21 20:10
@polcape and @ImNtReal , you are using package 2.1.26.19?

**Comment by ImNtReal** [comment] 2016-09-21 20:29
Yes, and I do have adLDAP.php v5. Is there a fix in master, yet?

**Comment by ImNtReal** [comment] 2016-09-21 20:36
Note that, I don't know how it got there, but I do have ldap_type = 'windows' in my database.

**Comment by nilsteampassnet** [comment] 2016-09-22 06:49
If you needed to perform the indicated changes in identify.php, it means you were not using package 2.1.26.19 as those changes are included.

Can you check your files and upgrade to this package, or using last commit in development branch.  Then run upgrade.php file

**Comment by reginfo** [comment] 2016-09-22 07:24
Nil, I downloaded 2.1.26.19 version and opened identity.php page I see
`$adldap = new LDAP\adLDAP\adLDAP`

If I look in deployment branch I see fix
`$adldap = new adLDAP\adLDAP`

So changes that work OK for now is in deployment branch.

**Comment by nilsteampassnet** [comment] 2016-09-22 08:46
Sorry for my confusion . You're right ! 

I'll make a new pre-release tonight.

**Comment by reginfo** [comment] 2016-09-22 10:49
Great news!

**Comment by TheKingKai** [comment] 2016-09-23 08:56
Ok, after my tests with version 2.1.26 (10) I have a bad results. I have team pass completely reinstalled  before my tests starts. There are 2 problems:

First error is after i switch the language to german I get this error massage on the settings page:
![12](https://cloud.githubusercontent.com/assets/20316918/18779983/afac4128-817b-11e6-85cd-23fa048a633a.png)

Second error is I can't login with username only or with domain suffix. Both are not working after I reinstalled the new TeamPass version :( The LogIn Screen freezes.
![13](https://cloud.githubusercontent.com/assets/20316918/18780133/6914c91e-817c-11e6-9913-3027e8a7f403.png)

**Comment by reginfo** [comment] 2016-09-23 10:06
Are you talking about 2.1.26 (10) version or about latest 2.1.26 (20)??? Try to clear all browser cache. After update to new version I do not have problems with LDAP.

**Comment by TheKingKai** [comment] 2016-09-23 10:09
Sorry, I mean 2.1.26 (20)

**Comment by TheKingKai** [comment] 2016-09-23 10:24
nothing works :( i tested it on a new computer with IE11. It's not possible to LogIn. Here are my LDAP configuration with such data to anonymize:

![domain](https://cloud.githubusercontent.com/assets/20316918/18782831/a2fdd97a-8188-11e6-94d7-f53b29255b14.png)

Is it right?

**Comment by reginfo** [comment] 2016-09-23 11:26
I have similar config, I only use IP for domain controller.
I install from fresh using DEMO environment and everything works fine.

**Comment by sedennial** [comment] 2016-09-23 23:24
I'm also experiencing this exact same issue, occurring with 2.1.26(20), on a fresh ubuntu 16.04 install. The problem only occurs with a valid AD account. With a non-valid account it fails with the appropriate error.

Running Apache/2.4.18 (Ubuntu), php 7.0.8-0ubuntu0.16.04.2

**Comment by nilsteampassnet** [comment] 2016-09-24 06:38
As some have issues and other succeed with the similar LDAP settings (see @TheKingKai scrsen capture), there must be something related the LDAP configuration itself.
Isn't there LDAP error logs or something similar that could help?

@TheKingKai, some messages before, you should a screen shot with the login page where the waiting icon never stops. At this step, there is an error. Can you catch it with Firebug please?

**Comment by TheKingKai** [comment] 2016-09-26 06:14
hmm I get no error in FireBug....

![asdf](https://cloud.githubusercontent.com/assets/20316918/18824271/d97dc57a-83c0-11e6-85a9-7b8e142dcb08.png)

Response body:

```
<br />
<font size='1'><table class='xdebug-error xe-fatal-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Call to undefined method adLDAP\adLDAP::user_info() in C:\wamp64\www\teampass\sources\identify.php on line <i>395</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0033</td><td bgcolor='#eeeeec' align='right'>461200</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\teampass\sources\identify.php' bgcolor='#eeeeec'>...\identify.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0055</td><td bgcolor='#eeeeec' align='right'>539520</td><td bgcolor='#eeeeec'>identifyUser(  )</td><td title='C:\wamp64\www\teampass\sources\identify.php' bgcolor='#eeeeec'>...\identify.php<b>:</b>91</td></tr>
</table></font>

```

`http://192.168.30.10/teampass/sources/identify.php?data=nLvoV0BAQEBDqiytbeRntgE8OKPF1nfN4V72kqiwZ7etpcrKSFGwaVf4zhlLfl%2FBsi%2BW%2FKBN1dWd8gh6OFXGHGiphl4EAg%2Fk316Ldx2%2FfBadM7BxqUQ%2B2iNtEtMUfEv%2Fh%2FNEUv6008CMU9MbFliDeK5cIC7PrbyHrGAOMZ5YwJKynDUDd%2Bt2HLwdyy1YMbDGUMT%2FK2PF&type=identify_user`

**Comment by TheKingKai** [comment] 2016-09-26 06:32
aaah I think on line 395 the script try to get an email from AD. But in my AD the users haven't any email.... is this the error, nils?

**Comment by sedennial** [comment] 2016-09-26 15:20
We do have email addresses in our AD config. Our ADC are 2008 and 2008 R2. The problem doesn't appear to be an LDAP query problem. I've done traffic capture on the query and it appears to be correct. The problem is somewhere after bind_as_user. The acutal authentication is successful, it crashes when it attempts to create a new AD based user. If the user is already exists the login is successful.

**Comment by nilsteampassnet** [comment] 2016-09-26 19:06
> aaah I think on line 395 the script try to get an email info from AD. But in my AD the users haven't any email.... is this the error, nils?

Yes email is required. Can't you just enable "email" in LDAP and leave the field empty for your users?

@sedennial, where is `bind_as_user`?

**Comment by sedennial** [comment] 2016-09-26 19:18
I was just using that to explain where the problem seem to be. It looks
like it is the code following where it binds as the user who is logging on,
then when it succeeds it attempts to create the account from the AD
information. If it fails to bind (or in other words if it fails to
authenticate as the user who is trying to log on) the problem doesn't occur.

_______________________________________________________________________________________
"Even a fool, (when he holdeth his peace) is counted wise."  -- *Solomon*

"Wealth consists not in having great possessions, but in having few wants."
-- *Epictetus*

“And that the said Constitution shall never be construed to authorize
Congress to infringe the just liberty of the press or the rights of
conscience; or to prevent the people of The United States who are peaceable
citizens from keeping their own arms…” -- *Samuel Adams, Founding Father,
United States of America*

*vive libre, veri este*

**Comment by TheKingKai** [comment] 2016-09-27 05:40
> Yes email is required. Can't you just enable "email" in LDAP and leave the field empty for your users?

What do you mean with just enable "email" in LDAP? Where can I do this?

**Comment by nilsteampassnet** [comment] 2016-09-27 05:43
Unfortunately I don't know. I have no LDAP knowledge.

**Comment by ImNtReal** [comment] 2016-09-27 14:50
After upgrading to .20, I'm not getting: PHP Fatal error:  Call to undefined method adLDAP\\adLDAP::get_last_error() in /var/www/TeamPass-2.1.26.20/sources/identify.php on line 308

**Comment by sedennial** [comment] 2016-09-27 15:28
@TheKingKai @nilsteampassnet In AD, LDAP attributes that are in the schema (such as email) are already present. They may return a null value, but they are 'enabled', so querying them will always return a result, though it may be an empty string (""). In the case of the AD email attribute it returns "" if undefined, not NULL.

@TheKingKai Have you tried creating a user in TP that matches a preexisting AD user, then logging in with that user? If you do this, does it work? If so, your problem is the same as mine and it is failing on the new user auto-creation.

**Comment by F0ob4r** [comment] 2016-09-28 07:17
With change of LDAP Library a few methods also changed

you have to patch identify.php
`--- identify.php.old    2016-09-28 09:08:36.672322593 +0200
+++ identify.php        2016-09-28 09:09:25.808320762 +0200
@@ -184,7 +184,9 @@ function identifyUser($sentData)
     /* LDAP connection */
     if ($debugLdap == 1) {
         // create temp file
-        $dbgLdap = fopen($_SESSION['settings']['path_to_files_folder']."/ldap.debug.txt", "w");
+
+
+       $dbgLdap = fopen($_SESSION['settings']['path_to_files_folder']."/ldap.debug.txt", "w");
         fputs(
             $dbgLdap,
             "Get all LDAP params : \n" .
@@ -303,9 +305,8 @@ function identifyUser($sentData)
                     'use_tls' => $_SESSION['settings']['ldap_tls']
                 )
             );
-
             if ($debugLdap == 1) {
-                fputs($dbgLdap, "Create new adldap object : ".$adldap->get_last_error()."\n\n\n"); //Debug
+            //    fputs($dbgLdap, "Create new adldap object : ".$adldap->getLastError()."\n\n\n"); //Debug
             }

             // openLDAP expects an attribute=value pair
@@ -334,7 +335,7 @@ function identifyUser($sentData)
             if ($debugLdap == 1) {
                 fputs(
                     $dbgLdap,
-                    "After authenticate : ".$adldap->get_last_error()."\n\n\n" .
+                    "After authenticate : ".$adldap->getLastError()."\n\n\n" .
                     "ldap status : ".$ldapConnection."\n\n\n"
                 ); //Debug
             }
@@ -392,7 +393,7 @@ function identifyUser($sentData)
         $data['pw'] = $pwdlib->createPasswordHash($passwordClear);  // create passwordhash

         // get user info from LDAP
-        $user_info_from_ad = $adldap->user_info($auth_username, array("mail", "givenname", "sn"));
+        $user_info_from_ad = $adldap->user()->info($auth_username, array("mail", "givenname", "sn"));

         DB::insert(
             prefix_table('users'),
@@ -842,4 +843,3 @@ function identifyUser($sentData)
         $_SESSION['settings']['cpassman_dir'] = ".";
     }
 }
-
`

**Comment by TheKingKai** [comment] 2016-09-29 06:29
@sedennial 

`@TheKingKai Have you tried creating a user in TP that matches a preexisting AD user, then logging in with that user? If you do this, does it work? If so, your problem is the same as mine and it is failing on the new user auto-creation.`

yes, I have the same problem. After I created a user in TP that matches a AD user, then I can login.

**Comment by F0ob4r** [comment] 2016-09-29 09:42
New user auto-creation fails because in identify.php is a wrong method called ($adldap->user_info()). Try my patch.

**Comment by TheKingKai** [comment] 2016-09-29 12:01
> New user auto-creation fails because in identify.php is a wrong method called ($adldap->user_info()). Try my patch.


@F0ob4r Your patch works fine!! :) Now user creation haven't any problems.

In my case I edit the code on line 402, 403:

`                //'email' => $user_info_from_ad[0]['mail'][0],
                'email' => "",`

Because in my AD the users haven't any E-Mail information. After user creation with this code the E-Mail field remains empty.

**Comment by ImNtReal** [comment] 2016-10-04 20:50
I've tried signing in from 2.1.26-final with an account already added to the TeamPass database, but I get Login credentials do not correspond! This is my ldap_debug.txt after my last test:
Get all LDAP params : 
mode : 1
type : windows
base_dn : dc=nghs,dc=com
search_base : 
bind_dn : 
bind_passwd : 
user_attribute : 
account_suffix : @nghs.com
domain_controllers : 172.20.3.102
use_ssl : 0
use_tls : 0
*********

Get all ldap params : 
base_dn : dc=nghs,dc=com
account_suffix : @nghs.com
domain_controllers : 172.20.3.102
use_ssl : 0
use_tls : 0
*********

Create new adldap object : Success


After authenticate : Can't contact LDAP server


ldap status :

**Comment by F0ob4r** [comment] 2016-10-05 08:05
It seems like you have connection problems, is IP correct? Firewall settings? Port 389,636?
Try debugging with tcpdump (tcpdump -i eth0 -vv -nn port 389 or port 636)

But I think this is not related with this issue.

**Comment by ImNtReal** [comment] 2016-10-05 12:53
Argh! On the last build of this test server, I forgot to setsebool httpd_can_connect_ldap on -P, so after troubleshooting with a bad version for a while, I rebuilt it, and when the issue was corrected in the TeamPass code, I had a SELinux issue. Thank goodness for layered security. All seems to be well, now.

**Comment by ImNtReal** [comment] 2016-10-13 18:18
As far as I can tell this issue is completely cleared up.

**Closed** 2017-07-29 06:14 UTC
