### ISSUE TITLE
Google 2FA mail for temporary code is blank

### ISSUE THREAD

**Issue by Clesur** [nilsteampassnet/TeamPass#2266] opened 2018-05-16 14:47 UTC
### Steps to reproduce
1. User request for a temporary Google Authenticator
2. Same issue with admin console
3. 

### Expected behaviour
Normaly the users should receive a temporary code in the mail that you paste in the identification code and generate a QR Code

### Actual behaviour
The mail receive didn't have any temporary code and the link is blank

### Server configuration
**Operating system**:
Debian Stretch up to date

**Web server:**
Apache2

**Database:**
5.5.5-10.1.26-MariaDB-0+deb9u1

**PHP version:**
7.0.30-1+0~20180505045735.18+stretch~1.gbpcfecb9

**Teampass version:** 
2.1.27

**Teampass configuration file:**

<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '0',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'h:m:s a',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '0',
    'cpassman_dir' => '/var/www/teampass/TeamPass',
    'cpassman_url' => 'https://deltapass.groupe-delta.com/',
    'favicon' => 'http://www.groupe-delta.com/deltapass.png',
    'path_to_upload_folder' => '/var/www/teampass/TeamPass/upload',
    'url_to_upload_folder' => 'https://deltapass.groupe-delta.com/upload',
    'path_to_files_folder' => '/var/www/teampass/TeamPass/files',
    'url_to_files_folder' => 'https://deltapass.groupe-delta.com/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '1',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '1',
    'nb_bad_authentication' => '5',
    'utf8_enabled' => '1',
    'restricted_to' => '1',
    'restricted_to_roles' => '1',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '1',
    'custom_logo' => 'http://www.groupe-delta.com/deltapass.png',
    'custom_login_text' => '',
    'default_language' => 'french',
    'send_stats' => '0',
    'send_statistics_items' => '',
    'send_stats_time' => '1519031844',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31', 
    'pwd_maximum_length' => '40',
    'google_authentication' => '1',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'DeltaPass',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '1',
    'otv_expiration_period' => '2',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/teampass/TeamPass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '1',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Paris',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'copy_to_clipboard_small_icons' => '1',
    'tree_counters' => '0',
    'bck_script_key' => 'B1t€B01$',
    'can_create_root_folder' => '1',
    'use_http_request_login' => '1',
    'ga_reset_by_user' => '1',
    'enable_massive_move_delete' => '0',
);

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
fresh install

### Client configuration
**Browser:**
IE, Edge, Chrome, FireFox

**Operating system:**
Windows10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by Clesur** [comment] 2018-05-18 09:37
Thanks for your quick answer. I performed the upgraded from 2.1.27.11 to 2.1.27.14. I have the same issue, the mail send to the user contain a link that is blank. When I request to send user temp code from admin console , I have the message "No user found"

**Comment by nilsteampassnet** [comment] 2018-05-18 11:09
As I can't reproduce I believe there is an error in the apache log.
Can you check for it ?

**Comment by Clesur** [comment] 2018-05-18 13:18
For sure. Find it:
[Fri May 18 15:14:39.271315 2018] [mpm_prefork:notice] [pid 10865] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2l configured -- resuming normal operations
[Fri May 18 15:14:39.271523 2018] [core:notice] [pid 10865] AH00094: Command line: '/usr/sbin/apache2'
[Fri May 18 15:15:15.087963 2018] [:error] [pid 10866] [client 185.37.28.146:17984] PHP Notice:  Undefined index: 2fa_authentication_selector in /var/www/teampass/TeamPass/index.php on line 749

**Comment by nilsteampassnet** [comment] 2018-05-19 05:40
Ok thank you, this is really useful.

It is a missing language string. I will provide a new package.

**Comment by nilsteampassnet** [comment] 2018-05-21 15:50
Committed in Development branch

I will create soon a new package

**Closed by nilsteampassnet** 2018-05-21 15:50 UTC
Labels: Answered, bug
