### ISSUE TITLE
Can't restore database

### ISSUE THREAD

**Issue by TheKingKai** [nilsteampassnet/TeamPass#1405] opened 2016-07-29 08:24 UTC
Hey Nils,

last days I wanted to restore my database with the TeamPass backup function. But after I selected the restore database nothing happens. I only saw a rotate gearwheel.

But I think I have a solution for this error...

### Steps to reproduce
1. Create a backup of the database (TeamPass Site -> Settings -> Backup)
2. Select the SQL File to restore the database

The problem occurs with 'One shot backup and restore' and 'Settings for Backups script'. Same problem with this two methods.

### Expected behaviour
Restore the backup database.

### Actual behaviour
Nothing happens. Only the gearwheel rotates.

### My solution
I open the backup SQL file with Notepad++ and edit it.

Original code:

```
DROP TABLE teampass_items;

CREATE TABLE `teampass_items` (
  `id` int(12) NOT NULL AUTO_INCREMENT,
  `label` varchar(500) NOT NULL,
  `description` text NOT NULL,
  `pw` text NOT NULL,
  `pw_iv` text NOT NULL,
  `pw_len` int(5) NOT NULL DEFAULT '0',
  `url` varchar(500) DEFAULT NULL,
  `id_tree` varchar(10) DEFAULT NULL,
  `perso` tinyint(1) NOT NULL DEFAULT '0',
  `login` varchar(200) DEFAULT NULL,
  `inactif` tinyint(1) NOT NULL DEFAULT '0',
  `restricted_to` varchar(200) DEFAULT NULL,
  `anyone_can_modify` tinyint(1) NOT NULL DEFAULT '0',
  `email` varchar(100) DEFAULT NULL,
  `notification` varchar(250) DEFAULT NULL,
  `viewed_no` int(12) NOT NULL DEFAULT '0',
  `complexity_level` varchar(3) NOT NULL DEFAULT '-1',
  `auto_update_pwd_frequency` tinyint(2) NOT NULL DEFAULT '0',
  `auto_update_pwd_next_date` int(15) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `restricted_inactif_idx` (`restricted_to`,`inactif`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO teampass_items VALUES("1","SERVER-NAME","local","1198f96a15b568ebc5fe6f2a12efb6bb","29ae0b22d8ed486c2f3f1ccef58fed5c","0","","2","0","admin","0","","0","","","3","49","0","");
```

Edited code:

```
DROP TABLE teampass_items;

CREATE TABLE `teampass_items` (
  `id` int(12) NOT NULL AUTO_INCREMENT,
  `label` varchar(500) NOT NULL,
  `description` text NOT NULL,
  `pw` text NOT NULL,
  `pw_iv` text NOT NULL,
  `pw_len` int(5) NOT NULL DEFAULT '0',
  `url` varchar(500) DEFAULT NULL,
  `id_tree` varchar(10) DEFAULT NULL,
  `perso` tinyint(1) NOT NULL DEFAULT '0',
  `login` varchar(200) DEFAULT NULL,
  `inactif` tinyint(1) NOT NULL DEFAULT '0',
  `restricted_to` varchar(200) DEFAULT NULL,
  `anyone_can_modify` tinyint(1) NOT NULL DEFAULT '0',
  `email` varchar(100) DEFAULT NULL,
  `notification` varchar(250) DEFAULT NULL,
  `viewed_no` int(12) NOT NULL DEFAULT '0',
  `complexity_level` varchar(3) NOT NULL DEFAULT '-1',
  `auto_update_pwd_frequency` tinyint(2) NOT NULL DEFAULT '0',
  `auto_update_pwd_next_date` int(15) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `restricted_inactif_idx` (`restricted_to`,`inactif`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO teampass_items VALUES("1","SERVER-NAME","local","1198f96a15b568ebc5fe6f2a12efb6bb","29ae0b22d8ed486c2f3f1ccef58fed5c","0","","2","0","admin","0","","0","","","3","49","0",NULL);
```

I only replace **""** with **NULL** at the end of the INSERT INTO line and it works. After that TeamPass restore the backup database successful.

### Server configuration
**Operating system:** Windows Server 2012 R2

**Web server:** apache2.4.18

**Database:** mysql5.7.11

**PHP version:** php7.0.4

**Teampass version:** TeamPass-2.1.26.14

### Client configuration
**Browser:** IE11 & FireFox

**Operating system:** Windows 7

#### TeamPass error log (TeamPass Site -> Views -> Logs -> errors)
```
Query: INSERT INTO teampass_items VALUES("1","SERVER-NAME","local","1198f96a15b568ebc5fe6f2a12efb6bb","29ae0b22d8ed486c2f3f1ccef58fed5c","0","","2","0","admin","0","","0","","","3","49","0","");<br />Error: Incorrect integer value: '' for column 'auto_update_pwd_next_date' at row 1<br />@ 
```

**Comment by nilsteampassnet** [comment] 2016-07-29 10:02
IT is something corrected and commited in Development branch.
Not yet in a release ... I will create it.

And your analysis is correct, it was the bug.

Duplicate of #1392

**Closed by nilsteampassnet** 2016-07-29 10:02 UTC
Labels: Duplicate
