### ISSUE TITLE
Error Upgrade latest version 2 to 3.1.0

### ISSUE THREAD

**Issue by Blubmann1337** [nilsteampassnet/TeamPass#3973] opened 2023-12-08 16:04 UTC
I try upgrade vom latest v2 to latest v3. But get error 500 in browser if I try to load upgrade.php and got this error in apache log:
[Fri Dec 08 17:00:54.760745 2023] [proxy_fcgi:error] [pid 579:tid 140469136725760] [client 172.31.4.43:43336] AH01071: Got error 'PHP message: PHP Warning:  include(/var/www/teampass/vendor/composer/../teampassclasses/superglobal/src/SuperGlobal.php): Failed to open stream: No such file or directory in /var/www/teampass/vendor/composer/ClassLoader.php on line 571; PHP message: PHP Warning:  include(): Failed opening '/var/www/teampass/vendor/composer/../teampassclasses/superglobal/src/SuperGlobal.php' for inclusion (include_path='/var/www/teampass/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php') in /var/www/teampass/vendor/composer/ClassLoader.php on line 571; PHP message: PHP Fatal error:  Uncaught Error: Class "TeampassClasses\\SuperGlobal\\SuperGlobal" not found in /var/www/teampass/index.php:82\nStack trace:\n#0 {main}\n  thrown in /var/www/teampass/index.php on line 82'

I using Debian 11, Apache 2.4.56, MariaDB 10.5.23 and PHP 8.2.13

**Comment by nilsteampassnet** [comment] 2023-12-10 10:29
Duplicate of #3972

**Closed** 2023-12-10 10:30 UTC
