### ISSUE TITLE
I can't edit any properties of users with administrator account.

### ISSUE THREAD

**Issue by bkszzz** [nilsteampassnet/TeamPass#3718] opened 2023-05-16 08:50 UTC
### Steps to reproduce
1.add a LDAP user
2.when we add, try to change properties of that user, you choose done and the page refresh and the settings don't save.
3.

### Expected behaviour
When we try to change any propertie with administrator account, we can change.

### Actual behaviour
when we add a user, we try to change properties of that user and the propertie don't change.

### Server configuration
**Operating system**: Linux Teampass**** 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64

**Web server:** Apache/2.4.52 (Ubuntu)

**Database:** 5.5.5-10.6.12-MariaDB-0ubuntu0.22.04.1

**PHP version:** 8.1.2-1ubuntu2.11

**Teampass version:** 3.0.7

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '0',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/html/TeamPass',
'cpassman_url' => 'http://<anonym_url>
'favicon' => 'http://<anonym_url>/favicon.ico',
'path_to_upload_folder' => '/var/www/html/TeamPass/upload',
'path_to_files_folder' => '/var/www/html/TeamPass/files',
'url_to_files_folder' => 'http://<anonym_url>/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'teampass_version' => '3.0.7',
'ldap_mode' => '1',
'ldap_type' => 'ActiveDirectory',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => '*********',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_search_base' => '0',
'ldap_port' => '***',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'english',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1681631115',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '',
'email_security' => '',
'email_server_url' => '',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '0',
'proxy_ip' => '<removed>'
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '0',
'show_only_accessible_folders' => '0',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '60',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/html/TeamPass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => '<removed>'
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '0',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'UTC',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'bck_script_passkey' => '<removed>'
'admin_2fa_required' => '1',
'password_overview_delay' => '4',
'copy_to_clipboard_small_icons' => '1',
'duo_ikey' => '<removed>'
'duo_skey' => '<removed>'
'duo_host' => '<removed>'
'duo_failmode' => 'secure',
'roles_allowed_to_print_select' => '',
'clipboard_life_duration' => '30',
'mfa_for_roles' => '',
'tree_counters' => '0',
'settings_offline_mode' => '0',
'settings_tree_counters' => '0',
'enable_massive_move_delete' => '0',
'email_debug_level' => '0',
'ga_reset_by_user' => '',
'onthefly-backup-key' => '<removed>'
'onthefly-restore-key' => '<removed>'
'ldap_user_dn_attribute' => '*********',
'ldap_dn_additional_user_dn' => '',
'ldap_user_object_filter' => '**********',
'ldap_bdn' => '****',
'ldap_hosts' => '******'
'ldap_password' => '********'
'ldap_username' => '*******',
'api_token_duration' => '60',
'enable_tasks_manager' => '1',
'task_maximum_run_time' => '300',
'tasks_manager_refreshing_period' => '20',
'maximum_number_of_items_to_treat' => '100',
'ldap_tls_certifacte_check' => '**********',
'enable_tasks_log' => '0',
'upgrade_timestamp' => '1684223115',
'enable_ad_users_with_ad_groups' => '0',
'enable_ad_user_auto_creation' => '0',
'ldap_group_object_filter' => '',
'ldap_guid_attibute' => '**********',
'sending_emails_job_frequency' => '2',
'user_keys_job_frequency' => '1',
'items_statistics_job_frequency' => '5',

```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:**  - Chrome and firefox

**Operating system:**  Windows 10  64-bits

#### Web server error log
```
 -  (don't appeaeer any error in logs)
```

#### Teampass 10 last system errors
```
don't appeaeer any error in logs
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
don't appeaeer any error in logs
```

**Comment by bkszzz** [comment] 2023-05-16 08:54
@nilsteampassnet here  i attached a video with the reproduce of the issue


https://github.com/nilsteampassnet/TeamPass/assets/128389537/4e629c3a-2227-437d-97aa-da5547c55261

**Comment by bkszzz** [comment] 2023-05-18 15:40
The yellow symbol means that the user is managed on ad.

![image](https://github.com/nilsteampassnet/TeamPass/assets/128389537/920064c7-82eb-4b9d-831a-831f64f5fab5)

**Comment by nilsteampassnet** [comment] 2023-05-18 15:56
Oops perhaps need new glasses :smile: 

Ok then check in the webconsole if you have any error in the console and network tabs.

**Comment by bkszzz** [comment] 2023-05-22 07:30
I dont have any error's in webconsole.

**Comment by Nachtlichtermeer** [comment] 2023-05-23 07:27
same problem

**Comment by Nachtlichtermeer** [comment] 2023-06-05 08:22
adding is with commit 1c0825b67eb8f8b5ecc418ff7614423a275e6a79 now not possible too

**Comment by Nachtlichtermeer** [comment] 2023-06-16 12:41
no error in webconsole

commit c03c9b597899394d1df52b1b05e830065d2f8c76 tested: no luck

**Comment by Nachtlichtermeer** [comment] 2023-07-19 14:21
still no luck with commit 6f22a379a9bc004e0285797a1043a4c08fea6006

**Comment by Nachtlichtermeer** [comment] 2023-07-19 14:48
Fresh installation of 6f22a379a9bc004e0285797a1043a4c08fea6006 has the same problem

steps to reproduce:
* install teampass
* create a user
* wait until tasks finished
* user is not editable

System:
Ubuntu 22.04 with:
* apache 2.4.52
* PHP8.1.2
* MySQL 8.0.33

so it has nothing to do with LDAP or something else

**Comment by Nachtlichtermeer** [comment] 2023-08-10 11:56
problem makes teampass unusable and still persists for more than 2 month
please fix it

**Comment by nilsteampassnet** [comment] 2023-08-10 12:27
I cannot reproduce.
If the save is not done then there must be an error in the apache logs.
Can you please check them?
No errors in the console too?
In the last video I can see the top right waiting logo still there, this is not normal.

**Comment by nilsteampassnet** [comment] 2023-08-10 15:39
I don't know what to say and to test here.
Perhaps do a new try by getting latest commit and perform upgrade.
We will see after as on the same basis.

**Comment by Nachtlichtermeer** [comment] 2023-08-11 08:38
latest commit 496d48417eba7234615678b0f16cad61f22a5251 doesn't work

**Comment by Nachtlichtermeer** [comment] 2023-08-11 08:47
tried fresh installation as described in https://github.com/nilsteampassnet/TeamPass/issues/3718#issuecomment-1642234575
same problem :-/

**Comment by Nachtlichtermeer** [comment] 2023-08-11 08:53
after editing user and clicking 'Submit' no INSERT or UPDATE is logged in the database

**Comment by Nachtlichtermeer** [comment] 2023-08-11 09:09
i tried sniffing with burpsuite:
```
POST /sources/main.queries.php HTTP/1.1
Host: passwort-dev.foo.de
Cookie: teampass_session=3sq4amjnhk2mtseq169oci2tgo; 7ac4687eff2dddad0419acb589d4e3838ffe43e30033e60cde=734c0070aee44bef2e7a96d34b1e410fd9a0af8df90859f562
Content-Length: 952
Sec-Ch-Ua: "(Not(A:Brand";v="8", "Chromium";v="99"
Accept: */*
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Sec-Ch-Ua-Mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36
Sec-Ch-Ua-Platform: "Linux"

Origin: https://passwort-dev.foo.de
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://passwort-dev.foo.de/index.php?page=users
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Connection: close

type=get_number_of_items_to_treat&type_category=action_system&data=eyJjaXBoZXJ0ZXh0IjoiN0R0aWFod1NNUkhuYlA4UGt6Q3dvdz09IiwiaXYiOiI2YTNiYjBiMWUwNTE0OGI5NDg0NTI4NWU0YTAyNDZhMyIsInNhbHQiOiI1YzEzNGU3MGQ4MzY0YjZjNjlmNzdjNDYzN2M1ZDUwNDE3YWVkNWRiNmJlYTVlYzUwMTFhMmYzNTNhMGE2OWU3MDFhZDI4MjVmMGNjYTJjNmM1NTBlNWI0ZjRiYzAzZjgwY2NjMzc2NjQyMTZjYWFmNmYwZDZlYWRjOTY3OTA2ZjE3MzFmNTlhZjBiYjFiMTdmODU2NjY5NjhmYjc1YTZjOTYxNjRmZWIyZTZkZTlkYzM1Njk2OTZjOGZhYmU1MmUzMDA1OGYwYTBhNGQzOWEzNjFhMTU3ZWJmMjM1ZGI0MWE2YzAxMzAwMTBlOTY4Yzk5MzViNjFiY2Q0ZWQyYzU0MzUxZmQzMzk3MTdlMTExNDI0ZTlhNjcxYWIxYjlhYTdhYWI1YWNiNTEzYTcwN2FmMzE1MWQ4YzhkYzI0ZjY1OTA0YjM3ZTkxMTRiZDI5YTFmZDIyYzFlYTg4YmIyMGQxN2M1NzlkN2ZlMzYyNGI0ODhjNjM1NTcxMjA1MmRjZGI5ODBjZmNhNzkyZDBhYWUzYWMwYjIzNjMyNmY5NWU3ZjU1ZmZmOTAzNGFhMzRmMTlhMGJmZjgwNjBmNDhiNGYwYjAyNzEyODJiNDMwMGY4MTJhNDI0YzczOTBkMWI3OTdlMjcwM2JkOWM3NGM3ZmNmMWQyZjJlYTUwOGQ2MWMzMSIsIml0ZXJhdGlvbnMiOjk5OX0%3D&key=rsrrubeAWKckxvvfCauuDbXT3w7p5DTr3QgQDt2R6PrFwcXUAF
```

```
POST /sources/users.queries.php HTTP/1.1
Host: passwort-dev.foo.de
Cookie: teampass_session=3sq4amjnhk2mtseq169oci2tgo; 7ac4687eff2dddad0419acb589d4e3838ffe43e30033e60cde=734c0070aee44bef2e7a96d34b1e410fd9a0af8df90859f562
Content-Length: 1600
Sec-Ch-Ua: "(Not(A:Brand";v="8", "Chromium";v="99"
Accept: */*
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Sec-Ch-Ua-Mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36
Sec-Ch-Ua-Platform: "Linux"
Origin: https://passwort-dev.foo.de

Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://passwort-dev.foo.de/index.php?page=users
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Connection: close

type=store_user_changes&data=eyJjaXBoZXJ0ZXh0IjoiVlJwUDJEODlCVVBLNCs4RmlnZE1hZVpWUE8xOXhLQVJtK01mbUpISDNKNW1Nd25WdUdzMS9lQmRKR2VUZXNuUHBFK0o0dEpKd0F3T0ppYUlQZVpVeEZHUGJyYUlXcEhPYkswRFRnbDRMcGJBdXR0ZUloWVNlT2d0eHpVMHNmaHZ5THhPZXRWamZhQVo5R0xRd1BMRVR2SFZ6QllpMFRleEpsWHVQak1ZRlMweWNrY2dFTHVySTZhd1I2WHJOWmxXNzQ3SU4zMmtibEFremRBblhEQlZZdmNlbUo4N2paTE52RTNUc3ljdkRsWXRRc1JJdm9zeDM2TUJub2ZOMWgvTGN1VGJPTnhwdTU0Q04yenRvSmRSMmd5UnNhbGkwMU5tVm9tOU5ScFBSQ2VqRHdVa2RMSWN2V2JPRzJRQ0VRS0tmWndOTGowa2FSREp0RytXTW9nUlFCT3lDTmJjQTNKYVRpWHpoRTRQaU0wdzJ2cFA3ZzBubjc0MmRUalRab2RCYXFUaFNMM0JIZDJnSi9yUndrd1JaSGNNeVNEa3N6Q3JXVHNkS01DTG1lWjZRUmtiTTlHSTRtTi9YTG1aSlJyNC9HRGVKZVcwRXZyY21UQ0lLaHlzOFNGcDBIMmlsRHdzOTl0bVhMRUQvOHlSalJ6WHZpZW9USE1nbGlxTW5TYzRSNjNCczVmY2J0eEhSUndiSzhUZStBPT0iLCJpdiI6IjFkZDk2N2NlZjZhYWFlZDk3OGRlYjI3ZjQyZGFiMDI3Iiwic2FsdCI6ImM5NDE4Mjg3NGJkY2YyYTU4OGY3MWM5NjczNzkzNjk2MWMwZDAxYTczOTM1YWMyODg2ZWU2N2I2MzAwNDI5YTk4MGMxOGQ4NDBjMzc1ZWM0YTE2MDQ5OTMwMmYzYWU3MzNkN2EzMTQ2M2U5MjA5YTk3YzMwNTVmODEwYTA5N2IzNzc3MTUyZTkwNTg1OTZkNGM2NzU3MDJjOGM1MGY2ZjcwZmMxMzM5N2I5OWZhNzcyOTk3NjU3NjIyZTMyODkzMzZiZWNmNWYzMTFmYjJiYmNlZWE2NzQ2ZWJkZGI0OWY2YWM0ODcwNmFlMDI0YTNiNjE4NWQ5N2U2ZDM5OGMyMTU1YjBiYTI2MTdhYzAyOWFhYTE0NzU3ZjhjZGRhODQxMjE3OGExMDJjZDA0NDAwNjA0MzI2MDAzMDkyOTM5MDY3NGEzOTE4N2ZhN2Y5YmFlZWIyODdmNTRmNzczMTRjMzU2MTk4ZjY5NGNhZGU0OTJkYjQzNzY3MGRmNzczNDZmZDFjNmNlNzBiNGUyMGI0NDU4NTcxOThlNjBlNzc2ZjE0OGU0OTc1ZTY1ZGE5MjY1ZDI5YjEyNWM5MWU2MDAwMDNmMjBiMTgwNTlhYTg1YmFmYzEzNTk4NWExYWJhNDA2OWI4MTAyZDk0YjUzN2RlOGM3MDExMmZiMGE5NThmN2FjIiwiaXRlcmF0aW9ucyI6OTk5fQ%3D%3D&key=rsrrubeAWKckxvvfCauuDbXT3w7p5DTr3QgQDt2R6PrFwcXUAF
```

```
GET /sources/users.datatable.php?draw=2&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=7&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=8&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=1&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1691744739475 HTTP/1.1
Host: passwort-dev.foo.de
Cookie: teampass_session=3sq4amjnhk2mtseq169oci2tgo; 7ac4687eff2dddad0419acb589d4e3838ffe43e30033e60cde=734c0070aee44bef2e7a96d34b1e410fd9a0af8df90859f562
Sec-Ch-Ua: "(Not(A:Brand";v="8", "Chromium";v="99"
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
Sec-Ch-Ua-Mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36
Sec-Ch-Ua-Platform: "Linux"
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://passwort-dev.foo.de/index.php?page=users
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Connection: close
```

maybe it helps

**Comment by Nachtlichtermeer** [comment] 2023-08-11 09:16
SOLUTION!!!:

after playing around with some changes i found out that i can change all settings after
setting Name, Last name an Email of admin-account

**Comment by Knoppix1** [comment] 2023-08-14 15:52
> SOLUTION!!!:
> 
> after playing around with some changes i found out that i can change all settings after setting Name, Last name an Email of admin-account

How did you do ?
I still have the same problem

**Comment by Nachtlichtermeer** [comment] 2023-08-15 07:32
login as 'admin', go to 'Users', edit the user 'admin', insert values for Name, Last name an Email and click 'Submit'.
After this i can change all other accounts.
i tested this with productive and fresh installation also

**Comment by nilsteampassnet** [comment] 2023-08-20 14:49
Should be fixed in recent commits

**Closed by nilsteampassnet** 2023-08-20 14:49 UTC

**Comment by Knoppix1** [comment] 2023-08-27 12:41
> Should be fixed in recent commits
Hi thanks
But it's still there
I filled in all the fields of the admin user (Name, First name, Email) and indeed it works thanks to @Nachtlichtermeer
