### ISSUE TITLE
Custom Fields - displayed in unassigned folders

### ISSUE THREAD

**Issue by go2this** [nilsteampassnet/TeamPass#2056] opened 2017-12-11 17:42 UTC
### Steps to reproduce
1. First create a custom field and assign it to one or more folders
![custom fields 1](https://user-images.githubusercontent.com/34249133/33844540-dad15c7a-dea0-11e7-8d19-9490b2d6bd50.jpg)

2. Take a look at the assigned folder.
![custom fields 2](https://user-images.githubusercontent.com/34249133/33844932-18662628-dea2-11e7-879e-0a9e169da9e2.jpg)

3. Open or create a new item in an unassigned folder.  

4. The field is still displayed here. **Or do I misunderstand the function?**
![custom fields 3](https://user-images.githubusercontent.com/34249133/33844939-20bd3b04-dea2-11e7-8179-087a02c4dd51.jpg)

### Behaviour
Custom fields are displayed in all folders. Also in folders to which they are not assigned.

### Server configuration
**Operating system**: Debian 9.2

**Web server:** Apache 2.4.25

**Database:** MariaDB

**PHP version:** 7.1.12-2

**Teampass version:** 2.1.27.10

**Teampass configuration file:** [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1542215/tp.config.php.txt)

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration
**Browser:** Firefox / Chrome

**Operating system:** Windows 7 Prof. x64

**Comment by nilsteampassnet** [comment] 2017-12-11 20:48
Yes I confirm.
It is a regression due to the fact that I wanted to get rid of functions such as `show` and `hide`, replaced by css. I missed one that has this impact.

Fix committed in development branch

**Closed** 2017-12-19 17:43 UTC
Labels: Answered, bug
