### ISSUE TITLE
Issue with Teampass 2.1.27 after updating Apache

### ISSUE THREAD

**Issue by maxallen123** [nilsteampassnet/TeamPass#1755] opened 2017-05-11 15:07 UTC
### Steps to reproduce
1. Have a Teampass 2.1.27 Install on Ubuntu Server 16.04.2 LTS
2. Update Apache from 2.4.18-2ubuntu3 to 2.4.18-2ubuntu3.2

### Expected behaviour
Teampass continues to work

### Actual behaviour
Apache throws 500 errors - error logs show AH02429: Response header name 'X-Frame-Option=SameOrigin' contains invalid characters, aborting request

### Server configuration
Ubuntu 16.04.2 LTS

**Web server:**
2.4.18-2ubuntu3.2

**Database:**
5.7.18-0ubuntu0.16.04.1

**PHP version:**
7.0.15-0ubuntu0.16.04.4

**Teampass version:** 
2,1,27 (.1 I think)

**Updated from an older Teampass or fresh install:**
Updated from .26 to .27.0 and then to .27.1

### Client configuration
**Browser:**
Both Chrome and Edget

**Operating system:**
Win 10

#### Web server error log
[Thu May 11 08:48:45.808661 2017] [http:error] [pid 19161] [client 10.100.10.27:59070] AH02429: Response header name 'X-Frame-Option=SameOrigin' contains invalid characters, aborting request

**Comment by nilsteampassnet** [comment] 2017-05-11 19:23
Please update.

Duplicate of #1692

**Closed by nilsteampassnet** 2017-05-11 19:24 UTC
