### ISSUE TITLE
All database accesible until new user create via LDAP

### ISSUE THREAD

**Issue by TomaszMru** [nilsteampassnet/TeamPass#2057] opened 2017-12-14 08:49 UTC
### Steps to reproduce
1. Create new user in ldap
2. Login to teampass(dont refresh the page)
3. 

### Expected behaviour
Only self directory available 

### Actual behaviour
All directory accesible with all passwords until press f5 despite "rights on folder" in admin panel is empty.
This user has no role assigne yet.
### Server configuration
**Operating system**:  
 Ubuntu 16.04 4.4.0-1041-aws
**Web server:** 
nginx 1.10.3-0ubuntu0.16.04.2
**Database:**
mysql 5.7.20-0ubuntu0.16.04.1
**PHP version:**
1:7.0+35ubuntu6
**Teampass version:** 
TeamPass 2.1.27
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
**Browser:**
Chrome
**Operating system:**
Winwos
#### Web server error log
no errors
Insert your webserver log here
`IP - - [14/Dec/2017:09:01:21 +0100] "GET /includes/js/jquery-ui/images/ui-icons_454545_256x240.png HTTP/1.1" 200 4431 "https://teampass.domain.com/includes/js/jquery-ui/jquery-ui.theme.min.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:01:22 +0100] "GET /logout.php?user_id=10000007 HTTP/1.1" 200 167 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
2017/12/14 09:01:22 [error] 15442#15442: *1559 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: pwComplexity in /opt/TeamPass-2.1.27.10/index.php on line 818" while reading response header from upstream, client: IP, server: teampass.domain.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "teampass.domain.com", referrer: "https://teampass.domain.com/logout.php?user_id=10000007"
IP - - [14/Dec/2017:09:01:22 +0100] "GET /index.php HTTP/1.1" 200 12813 "https://teampass.domain.com/logout.php?user_id=10000007" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:01:44 +0100] "POST /sources/checks.php HTTP/1.1" 200 32 "https://teampass.domain.com/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:01:44 +0100] "POST /sources/identify.php HTTP/1.1" 200 113 "https://teampass.domain.com/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:01:44 +0100] "GET /index.php?page=items HTTP/1.1" 200 56285 "https://teampass.domain.com/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:01:45 +0100] "POST /sources/main.queries.php HTTP/1.1" 200 188 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:01:45 +0100] "POST /sources/items.queries.php HTTP/1.1" 200 155 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:01:45 +0100] "GET /sources/tree.php HTTP/1.1" 200 1047 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:01:46 +0100] "POST /sources/items.queries.php HTTP/1.1" 200 2373 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:01:49 +0100] "POST /sources/main.queries.php HTTP/1.1" 200 80 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:01:49 +0100] "GET /index.php HTTP/1.1" 200 13096 "https://teampass.domain.com/logout.php?user_id=10000007" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:01:49 +0100] "POST /sources/main.queries.php HTTP/1.1" 200 49 "https://teampass.domain.com/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:01:53 +0100] "GET /logout.php?user_id=10000000 HTTP/1.1" 200 167 "https://teampass.domain.com/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
2017/12/14 09:01:53 [error] 15442#15442: *1559 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: pwComplexity in /opt/TeamPass-2.1.27.10/index.php on line 818" while reading response header from upstream, client: IP, server: teampass.domain.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "teampass.domain.com", referrer: "https://teampass.domain.com/logout.php?user_id=10000000"
IP - - [14/Dec/2017:09:01:53 +0100] "GET /index.php HTTP/1.1" 200 12812 "https://teampass.domain.com/logout.php?user_id=10000000" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:03:40 +0100] "POST /sources/checks.php HTTP/1.1" 200 32 "https://teampass.domain.com/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:03:40 +0100] "POST /sources/identify.php HTTP/1.1" 200 118 "https://teampass.domain.com/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:03:42 +0100] "GET /index.php HTTP/1.1" 200 12815 "https://teampass.domain.com/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:03:54 +0100] "POST /sources/checks.php HTTP/1.1" 200 32 "https://teampass.domain.com/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:03:54 +0100] "POST /sources/identify.php HTTP/1.1" 200 113 "https://teampass.domain.com/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:03:54 +0100] "GET /index.php?page=items HTTP/1.1" 200 56363 "https://teampass.domain.com/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:03:55 +0100] "POST /sources/main.queries.php HTTP/1.1" 200 81 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:03:55 +0100] "POST /sources/items.queries.php HTTP/1.1" 200 833 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:03:55 +0100] "GET /sources/tree.php HTTP/1.1" 200 1267 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:03:55 +0100] "POST /sources/items.queries.php HTTP/1.1" 200 166 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:03:56 +0100] "POST /sources/items.queries.php HTTP/1.1" 200 3224 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:03:59 +0100] "POST /sources/main.queries.php HTTP/1.1" 200 80 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:04:01 +0100] "POST /sources/items.queries.php HTTP/1.1" 200 1256 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:04:01 +0100] "POST /sources/items.queries.php HTTP/1.1" 200 3139 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:04:03 +0100] "POST /sources/main.queries.php HTTP/1.1" 200 31 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:04:03 +0100] "POST /sources/main.queries.php HTTP/1.1" 200 61 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:04:03 +0100] "POST /sources/items.queries.php HTTP/1.1" 200 898 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:04:03 +0100] "POST /sources/items.queries.php HTTP/1.1" 200 180 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:04:04 +0100] "POST /sources/main.queries.php HTTP/1.1" 200 109 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:04:09 +0100] "POST /sources/items.logs.php HTTP/1.1" 200 31 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:04:11 +0100] "POST /sources/items.logs.php HTTP/1.1" 200 31 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:04:13 +0100] "POST /sources/items.queries.php HTTP/1.1" 200 815 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:04:20 +0100] "POST /sources/items.queries.php HTTP/1.1" 200 838 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:04:20 +0100] "POST /sources/items.queries.php HTTP/1.1" 200 2460 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:01 +0100] "POST /sources/items.queries.php HTTP/1.1" 200 163 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:01 +0100] "GET /includes/js/jquery-ui/images/ui-icons_70b2e1_256x240.png HTTP/1.1" 200 4430 "https://teampass.domain.com/includes/js/jquery-ui/jquery-ui.theme.min.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:01 +0100] "GET /includes/js/jquery-ui/images/ui-bg_flat_0_eeeeee_40x100.png HTTP/1.1" 200 220 "https://teampass.domain.com/includes/js/jquery-ui/jquery-ui.theme.min.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:01 +0100] "GET /includes/js/ckeditor/config.js?t=EAPE HTTP/1.1" 200 1335 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:01 +0100] "GET /includes/js/ckeditor/skins/bootstrapck/editor.css?t=EAPE HTTP/1.1" 200 43553 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:01 +0100] "GET /includes/js/ckeditor/lang/en.js?t=EAPE HTTP/1.1" 200 5889 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:01 +0100] "GET /includes/js/ckeditor/styles.js?t=EAPE HTTP/1.1" 200 3484 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:02 +0100] "GET /includes/js/ckeditor/contents.css?t=EAPE HTTP/1.1" 200 1874 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:02 +0100] "GET /includes/js/ckeditor/skins/bootstrapck/icons.png HTTP/1.1" 200 3478 "https://teampass.domain.com/includes/js/ckeditor/skins/bootstrapck/editor.css?t=EAPE" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:14 +0100] "GET /index.php?page=items HTTP/1.1" 200 56261 "https://teampass.domain.com/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:15 +0100] "POST /sources/main.queries.php HTTP/1.1" 200 109 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:15 +0100] "POST /sources/items.queries.php HTTP/1.1" 200 144 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:15 +0100] "GET /sources/tree.php HTTP/1.1" 200 220 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:15 +0100] "POST /sources/items.queries.php HTTP/1.1" 200 212 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:19 +0100] "POST /sources/main.queries.php HTTP/1.1" 200 80 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:23 +0100] "POST /sources/main.queries.php HTTP/1.1" 200 31 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
IP - - [14/Dec/2017:09:05:23 +0100] "POST /sources/main.queries.php HTTP/1.1" 200 61 "https://teampass.domain.com/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
`

**Comment by nilsteampassnet** [comment] 2017-12-14 11:59
duplicate of #2035

**Closed by nilsteampassnet** 2017-12-14 11:59 UTC
