### ISSUE TITLE
TeamPass 3.0.0.8: Strange behaivor of filer "Only display..." at "Folders" page

### ISSUE THREAD

**Issue by Anth0nyME** [nilsteampassnet/TeamPass#2991] opened 2021-12-15 10:56 UTC
### Page on which it happened
index.php?page=folders

### Steps to reproduce
1. Add new folder OR just press "Refresh" button.
2. Look at multiple instances of "all" at "Only display folders to depth" filter. And any new refresh or new folder will adds +1 instance of "all".

### Expected behaviour
Single instance of "all" at "Only display folders to depth" filter.

### Server configuration
**Operating system**: Linux Rocky 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 15 20:49:28 UTC 2021 x86_64

**Web server:** nginx/1.20.2

**Database:** 5.5.5-10.6.5-MariaDB-log

**PHP version:** 8.0.13

**Teampass version:** 3.0.0.8

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '1',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd-M-Y',
'duplicate_folder' => '1',
'item_duplicate_in_same_folder' => '1',
'duplicate_item' => '1',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/vault/html',
'cpassman_url' => 'https://<anonym_url>
'favicon' => 'https://<anonym_url>/favicon.ico',
'path_to_upload_folder' => '/var/www/vault/html/upload',
'path_to_files_folder' => '/var/www/vault/html/files',

**'url_to_files_folder' => 'http://vault.mydomain.local/files',
WRONG: And cannot be edited via web interface.
At settings page looks as
/var/www/vault/html/files
Not as URL.**

'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '1',
'encryptClientServer' => '1',
'cpassman_version' => '3.0.0.8',
'ldap_mode' => '0',
'ldap_type' => '0',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'ldap_port' => '389',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '1',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '1',
'restricted_to_roles' => '1',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '1',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '1',
'enable_email_notification_on_item_shown' => '1',
'enable_email_notification_on_user_pw_change' => '1',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'english',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1636900932',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '0',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '',
'email_security' => 'none',
'email_server_url' => '',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '12',
'google_authentication' => '0',
'delay_item_edition' => '15',
'allow_import' => '1',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '1',
'otv_expiration_period' => '1',
'default_session_expiration_time' => '300',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/vault/html/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '1',
'create_item_without_password' => '1',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '1',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Moscow',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'offline_key_level' => '50',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'bck_script_passkey' => '<removed>'
'admin_2fa_required' => '1',
'password_overview_delay' => '15',
'copy_to_clipboard_small_icons' => '1',
'duo_akey' => '',
'duo_ikey' => '',
'duo_skey' => '',
'duo_host' => '',
'teampass_version' => '',
'roles_allowed_to_print_select' => '',
'clipboard_life_duration' => '300',
'tree_counters' => '1',
'max_last_items' => '10',

```

**Updated from an older Teampass or fresh install:**

Installation is fresh

### Client configuration

**Browser:** Chrome - 96.0.4664.45

**Operating system:** WindowsServer2008R2/7 - 64bits

#### Web server error log
```
Undefined array key "path" - /var/www/vault/html/sources/main.queries.php (1660)
```

#### Teampass 10 last system errors
```

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by Anth0nyME** [comment] 2021-12-15 11:01
![Capture](https://user-images.githubusercontent.com/33858023/146174810-d7113ecb-162e-4a67-836b-36086978d7a6.JPG)

**Comment by Anth0nyME** [comment] 2021-12-15 16:37
> I've seen this typo of behaviour while trying to install 3.0.0.8 and it failed a couple of times and then I used single file from 3.0.0.7 (install.queries.php), then it worked. But then it has as many items in many dropdowns, as I tried to install it :-) Did you try to drop/create the DB and then do a single clean install?

Clean install? :)
This is a clean install, i didn't use TP before. So, i did installation from scratch.

**Comment by elmarbransch** [comment] 2021-12-15 19:06
> > I've seen this typo of behaviour while trying to install 3.0.0.8 and it failed a couple of times and then I used single file from 3.0.0.7 (install.queries.php), then it worked. But then it has as many items in many dropdowns, as I tried to install it :-) Did you try to drop/create the DB and then do a single clean install?
> 
> Clean install? :) This is a clean install, i didn't use TP before. So, i did installation from scratch. And i need to say, what i got no problems in installation process.

Ok, then this seems to be a different effect. Amongst others problems you reported here - and I do have myself - I cannot reproduce this effect on my install.

**Comment by Anth0nyME** [comment] 2021-12-16 08:59
> 
I need to say: after full page reloading all "all" in filter are dissapiered...
So, looks like a local problem, сookie possibleю

**Comment by nilsteampassnet** [comment] 2022-01-08 15:08
Confirmed bug.

**Comment by nilsteampassnet** [comment] 2022-01-08 15:13
Fixed in next push

**Closed by nilsteampassnet** 2022-01-08 15:13 UTC
