### ISSUE TITLE
Update to 2.1.27.12 from 2.1.27.11

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#2229] opened 2018-04-24 20:57 UTC
### Steps to reproduce
1. Download TeamPass 2.1.27.12
2. Unzip
3. Move all content to /var/www/html/teampass
4. Open www.teampass.local/install/upgrade.php
5. Enter admin login and password and click Launch

### Expected behaviour
Show OK statuss and Next button needs to be available

### Actual behaviour
Progress (loading) is spining and nothing happened
![capture](https://user-images.githubusercontent.com/4628571/39213633-c50ba9f2-481a-11e8-8dce-af293b7d30df.PNG)

### Server configuration
**Operating system**:
Ubuntu 14.04.5 LTS
**Web server:**
Apache/2.4.7 (Ubuntu)
**Database:**
mysql Ver 14.14 Distrib 5.5.59, for debian-linux-gnu (x86_64) using readline 6.3
**PHP version:**
PHP 5.5.9-1ubuntu4.23 (cli) (built: Feb 8 2018 21:59:47)
**Teampass version:** 
2.1.27.11

### Client configuration
**Browser:**
IE, FF, EDGE
**Operating system:**
Windows 10 ENT 1709
#### Web server error log
```
[Mon Apr 23 06:46:13.146809 2018] [mpm_prefork:notice] [pid 1097] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.$
[Mon Apr 23 06:46:13.146833 2018] [core:notice] [pid 1097] AH00094: Command line: '/usr/sbin/apache2'
[Tue Apr 24 23:31:31.708837 2018] [mpm_prefork:notice] [pid 1099] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.$
[Tue Apr 24 23:31:31.716776 2018] [core:notice] [pid 1099] AH00094: Command line: '/usr/sbin/apache2'
[Tue Apr 24 23:50:59.860058 2018] [:error] [pid 1121] [client 192.168.10.5:58287] PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /var/www/html/teampass/sources/main.functions.php on line 2226
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
From IE : SCRIPT438: Object doesn't support property or method 'btoa' upgrade.php (48,21)
```

**Comment by nilsteampassnet** [comment] 2018-04-25 08:11
Sorry for this.
When performed test I didn't face this issue.
I'm currently off but will investigate once back from holidays

**Comment by maiconstedille** [comment] 2018-04-26 19:33
same problem. Difference is just that the operating system is CentOS 7

**Comment by AlfWa** [comment] 2018-04-27 10:15
I had the same problem with a fresh install of 2.1.27.12. The problem is line 2226 in teampass/sources/main.functions.php

This little change fixes the problem:
- function cleanText(string $string, string $type = "")
+ function cleanText(string $string, string $type = NULL)

**Comment by nilsteampassnet** [comment] 2018-05-01 08:01
I confirm it is a duplicate of #2223 

It is related to the php version. As now I'm working fully with 7.2, I missed this point.
I will recreated the 2.1.27.12 package.

**Closed by nilsteampassnet** 2018-05-01 08:01 UTC
