### ISSUE TITLE
Deleting a private folder delteted all entries except for the private folder

### ISSUE THREAD

**Issue by thymeore** [nilsteampassnet/TeamPass#1878] opened 2017-08-24 07:20 UTC
### Steps to reproduce
1. Klicking the "Delete Folder" for the selected private folder

### Expected behaviour
The private folder and the entries in this folder should be deleted.

### Actual behaviour
Everything except for the private folder and its entries were deleted.

### Server configuration
**Operating system**: Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux

**Web server:** Apache/2.4.10 (Debian)

**Database:** mysql  Ver 14.14 Distrib 5.5.57

**PHP version:** PHP 5.6.30-0+deb8u1

**Teampass version:** TeamPass 2.1.26

**Teampass configuration file:** 

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Firefox Version 55.0.2 (64-Bit)

**Operating system:** Windows 7

**Comment by nilsteampassnet** [comment] 2017-08-25 04:54
This is a duplicate of #1561

**Closed by nilsteampassnet** 2017-08-25 04:54 UTC
Labels: 2.1.26, Duplicate
