### ISSUE TITLE
Manager can't change password of other users account

### ISSUE THREAD

**Issue by thymeore** [nilsteampassnet/TeamPass#1615] opened 2017-01-12 09:36 UTC
The account with the manager role was unable to change the password of another users account.

### Steps to reproduce
1. Login as manager
2. Click "Manage users" 
3. Select user & click on "Change password"
4. Change password & Click Save Button, Button don't work

### Expected behaviour
Password changed.

### Actual behaviour
Save Button doesn't work, this whereby the password didn't change.

### Server configuration
**Operating system**: Linux <some Hostname> 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
Debian 8.6

**Web server:** 
Server version: Apache/2.4.10 (Debian)
Server built:   Sep 15 2016 20:44:43
Server's Module Magic Number: 20120211:37
Server loaded:  APR 1.5.1, APR-UTIL 1.5.4
Compiled using: APR 1.5.1, APR-UTIL 1.5.4
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"

**Database:** mysql  Ver 14.14 Distrib 5.5.52, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:** 
PHP 5.6.27-0+deb8u1 (cli) (built: Oct 15 2016 15:53:28)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Teampass version:**  TeamPass 2.1.26  2009 - 2017

### Client configuration
**Browser:** Firefox 50.1.0

**Operating system:** Windows 7 32bit

**Comment by pingax** [comment] 2017-01-13 13:17
Same here, with an admin account (same server configuration)

**Comment by nilsteampassnet** [comment] 2017-01-14 06:57
Cannot reproduce.

If the password is not changed it means an error is generated (as it should change it).
Can you please use a developer console (firebug or browser one) to get the error sent back from the server?

**Comment by pingax** [comment] 2017-01-14 09:07
Hi,

My instance is connected to our AD. I temporary disabled the link ans I was
able to change the password (it was for a local account, not member of the
AD). After re-enabling the link, login for this user works.

So the bug, for me, is resolved.

Le samedi 14 janvier 2017, Nils Laumaillé <notifications@github.com> a
écrit :
> Cannot reproduce.
>
> If the password is not changed it means an error is generated (as it
should change it).
> Can you please use a developer console (firebug or browser one) to get
the error sent back from the server?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/LD5s9Kzwz7BWmNGlbjizs9rTYbzgmG1edufNUTyukoqko_E89pDPYNLPspJdbdz0dTENKnQxJeW0D9sAhAshq7MP7qRfK6BJmRkRwv2eDg6r09WcGXmmmjOJndSypRel--jLSrwHC-73r4s3-t_kIBQmNTDZiw=s0-d-e1-ft#https://github.com/notifications/beacon/AADJ5HFye8XdOf5fLXd_rYHaP6bwhy2Tks5rSHHxgaJpZM4Lhiqx.gif>

**Comment by frankenstein91** [comment] 2017-01-17 13:53
Hi Nils
This window is not closing if i click on save.
![grafik](https://cloud.githubusercontent.com/assets/2527348/22022845/ebef4218-dcc3-11e6-8a84-ba2bb874c762.png)

the only error is "Laden von gemischten aktiven Inhalten "http://<ip>/teampass/includes/libraries/csrfp/js/csrfprotector.js" wurde blockiert.[https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content]".

**Comment by thymeore** [comment] 2017-01-17 14:25
I have the same behavior like @frankenstein91.

**Comment by nilsteampassnet** [comment] 2017-01-17 19:37
You must have log errors

Or you can use your webbrowser console to catch the error.

Without this I cannot help

**Closed** 2022-10-31 04:51 UTC
Labels: waiting
