### ISSUE TITLE
Teampass 2.1.27.0 - Admin View no Next Button (Manage Users)

### ISSUE THREAD

**Issue by userrst** [nilsteampassnet/TeamPass#1678] opened 2017-03-06 08:09 UTC
### Expected behaviour
Change Pages  with the Next or. Last Button.

### Actual behaviour
In the Admin view, it is not possible to change the pages under Managed Users by more than 10 entries with set Show entries 10.
(We have 14 entries)
![image](https://cloud.githubusercontent.com/assets/26093484/23601487/f40e7a38-024b-11e7-8889-275193639f59.png)

By change the Show entry number higher, we see all Entry.
![image](https://cloud.githubusercontent.com/assets/26093484/23601564/76b9cfa0-024c-11e7-846d-f75d71da8b16.png)

### Server configuration
**Operating system:** CentOS Linux release 7.3.1611

**Web server:** httpd 2.4.6

**Database:** mariadb 5.5.52

**PHP version:** 5.5.38

**Teampass version:** 2.1.27.0

**Updated from an older Teampass or fresh install:** Update from TeamPass-2.1.26-final-3

### Client configuration
**Browser:** Newest Firefox

**Operating system:** Windows 10 64Bit

#### Web server error log
```
We don't have any errors in the log File
```

**Comment by nilsteampassnet** [comment] 2017-03-06 19:19
Duplicate of #1654

**Closed by nilsteampassnet** 2017-03-06 19:19 UTC
