### ISSUE TITLE
View password is interpreting angle braces

### ISSUE THREAD

**Issue by daerogami** [nilsteampassnet/TeamPass#2320] opened 2018-06-27 15:48 UTC
### Steps to reproduce
1. Create password entry with a password starting with an html tag
2. Save and click view password
3. Displays password without html tag, but copies correctly

### Expected behaviour
I should be able to save any ASCII password and view it exactly as it was entered

### Actual behaviour
View password is interpreting something from the password
For example:
using the password: ```<b>bold<\b>notbold```
results in
![truncation](https://user-images.githubusercontent.com/39277958/41931076-f364052c-794a-11e8-95c0-d3b9f3d4d09a.png)

### Server configuration
**Operating system**: Azure (Windows)

**Web server:** IIS 10.0

**Database:** MySQL

**PHP version:** 5.6.33

**Teampass version:** 2.1.27

**Teampass configuration file:** [tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/1874450/tp.config.zip)

**Updated from an older Teampass or fresh install:**
Fresh

### Client configuration
**Browser:** Chrome (Version 67.0.3396.87)

**Operating system:** Windows 10 Pro

#### Web server error log
N/A

#### Log from the web-browser developer console (CTRL + SHIFT + i)
N/A

**Comment by nilsteampassnet** [comment] 2018-06-29 20:03
This is a duplicate of #2244
Fixed since 2.1.27.13

**Closed by nilsteampassnet** 2018-06-29 20:03 UTC
