### ISSUE TITLE
No add users button

### ISSUE THREAD

**Issue by hanibaluk** [nilsteampassnet/TeamPass#2260] opened 2018-05-11 11:05 UTC
### Steps to reproduce
1. log in as admin
2. click manage users icon

### Expected behaviour
There should be an option to add a user

### Actual behaviour
No menu to add users (no tool bar at all)

### Server configuration
Ubuntu
Apache
MySQL
PHP 5.5
Teampass 2.1.27.12 Clean install

/var/log/apache/errors.log last line shows:
PHP Catchable fatal error:  Argument 1 passed to cleanText() must be an instance of string, string given, called in /var/www/html/teampass/users.php on line 75 and defined in /var/www/html/teampass/sources/main.functions.php on line 2230, referer: https://[removed]/teampass/index.php?page=manage_users

**Comment by hanibaluk** [comment] 2018-05-11 11:32
I have managed to workaround this by removing the string type requirement from the cleantext function.
function cleanText($string, $type = null).

**Comment by nilsteampassnet** [comment] 2018-05-11 19:54
Duplicate of #2223

yes this is solution

**Closed by nilsteampassnet** 2018-05-11 19:54 UTC
Labels: Duplicate
