### ISSUE TITLE
New installation fail with latest sources (mcrypt_encrypt)

### ISSUE THREAD

**Issue by thefirstben** [nilsteampassnet/TeamPass#2112] opened 2018-02-04 21:05 UTC
### Steps to reproduce
1. Make a fresh install
2. Try to login

### Expected behaviour
Login ok

### Actual behaviour
Nothing happens. In the web server error log :  Call to undefined function **mcrypt_encrypt**

### Server configuration
**Operating system**:
Lastest version of Archlinux (kernel :4.14.13-1)

**Web server:**
Lighttpd 1.4.48-2

**Database:**
MariaDB 10.1.30-1

**PHP version:**
7.2.2-1

**Teampass version:** 
Lastest source from github (git clone)

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Firefox : 58.0.1

**Operating system:**
Win10

#### Web server error log
2018-02-04 21:45:25: (server.c.2005) server stopped by UID = 0 PID = 1
2018-02-04 21:45:25: (server.c.1412) server started (lighttpd/1.4.48)
2018-02-04 21:47:32: (mod_fastcgi.c.434) FastCGI-stderr: PHP Fatal error:  Uncaught Error: Call to undefined function mcrypt_encrypt() in /usr/share/webapps/TeamPass/sources/main.functions.php:114
2018-02-04 21:47:32: (mod_fastcgi.c.434) FastCGI-stderr: Stack trace:
2018-02-04 21:47:32: (mod_fastcgi.c.434) FastCGI-stderr: #0 /usr/share/webapps/TeamPass/sources/identify.php(325): encryptOld('**cleartextpassword**')
2018-02-04 21:47:32: (mod_fastcgi.c.434) FastCGI-stderr: #1 /usr/share/webapps/TeamPass/sources/identify.php(233): identifyUser('**some encrypted stuff**')
2018-02-04 21:47:32: (mod_fastcgi.c.434) FastCGI-stderr: #2 {main}
2018-02-04 21:47:32: (mod_fastcgi.c.434) FastCGI-stderr:   thrown in /usr/share/webapps/TeamPass/sources/main.functions.php on line 114

Insert your webserver log here
[04/Feb/2018:21:47:22 +0100] "POST /teampass/install/install.queries.php HTTP/1.1" 200 52 "https://website/teampass/install/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
[04/Feb/2018:21:47:26 +0100] "GET /teampass/index.php HTTP/1.1" 200 60666 "https://website/teampass/install/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
[04/Feb/2018:21:47:26 +0100] "GET /teampass/includes/js/functions.js HTTP/1.1" 304 0 "https://website/teampass/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
[04/Feb/2018:21:47:26 +0100] "GET /teampass/includes/images/canevas/logo.png HTTP/1.1" 304 0 "https://website/teampass/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
[04/Feb/2018:21:47:31 +0100] "POST /teampass/sources/checks.php HTTP/1.1" 200 1 "https://website/teampass/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
[04/Feb/2018:21:47:32 +0100] "POST /teampass/sources/identify.php HTTP/1.1" 500 0 "https://website/teampass/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by thefirstben** [comment] 2018-02-04 21:19
Hello,
For testing purpose i tried taking the development branch and was able to login but i get this as soon as i login i get a 'Requested JSON parse failed.' popup and the message "Required PHP extension mcrypt is not loaded. Please inform your administrator if you see this message. "
From what i read mcrypt is not in Php 7.2. Anything i can do about this ?

**Comment by nilsteampassnet** [comment] 2018-02-05 18:23
duplicate of #2094

**Closed by nilsteampassnet** 2018-02-05 18:23 UTC
