### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'b.body')

### ISSUE THREAD

**Issue by mreinders** [nilsteampassnet/TeamPass#1978] opened 2017-10-24 23:16 UTC
We have issues with the new installation of TeamPass. Several weeks ago we have successfully installed TeamPass and now I get errors in creditor.js when I'm looking in the console. When I register a password in my Personal Folder, then the system says not authorized, but I'm the Author of the password file. So what do I wrong with my configuration?

![js2](https://user-images.githubusercontent.com/9744940/31972640-e6abd6aa-b921-11e7-9ebd-23d3bc9cb55e.png)
![js1](https://user-images.githubusercontent.com/9744940/31972641-e6d40864-b921-11e7-8866-e6ea90334365.png)
![access denied](https://user-images.githubusercontent.com/9744940/31972643-e6fad142-b921-11e7-81b9-0c8380c84753.png)

**Comment by nilsteampassnet** [comment] 2017-10-25 05:42
This is a bug fixed in development branch.
Duplicate of #1960

**Closed** 2017-10-25 05:42 UTC

**Comment by mreinders** [comment] 2017-10-25 07:31
Thanks a lot! It worked also for me.
